--###########################################################################
--# ported from qp4/Project3/PROJ-1624-GlobalIndex/PROJ-1624-QC/PDT/Design/ALTER_TABLE/COALESCE/HashPartTable_Date.sql
--#
--# Body below is byte-identical to the original. The one line this port
--# adds is the premise: the original measures these statements on the
--# $GIT_ hidden-table implementation, this file measures the same
--# statements on the native global index (F07 -- see include/pinNative.sql).
--###########################################################################
--+LOAD_SQL ../../../../include/pinNative.sql;

--###################################################################
--# ALTER TABLE ... COALESCE PARTITION (PartKey: DATE)
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

--+APPEND_LST Schema_Hash_Date.sql;
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

--###################################################################
--+ SECTOR; BASIC TEST
--###################################################################
--##############################
--+SECTOR; 문법 체크
--##############################
DROP TABLE TEST;
CREATE TABLE TEST( I1 DATE, I2 INTEGER )
PARTITION BY HASH(I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS;

-- should be fail
ALTER TABLE TEST 
COALESCE PARTITION P1;

-- should be fail
ALTER TABLE TEST 
COALESCE PARTITION P5;

DROP TABLE TEST;

--##############################
--+SECTOR; 파티션드 테이블인지 체크
--##############################
DROP TABLE TEST;
CREATE TABLE TEST( I1 DATE, I2 INTEGER );

-- should be fail
ALTER TABLE TEST 
COALESCE PARTITION;

DROP TABLE TEST;


--##############################
--+SECTOR; 남은 파티션 개수 체크
--##############################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

-- result: 13
SELECT COUNT(*) FROM T1;

-- should be success
ALTER TABLE T1 
COALESCE PARTITION;

-- should be success
ALTER TABLE T1 
COALESCE PARTITION;

-- should be success
ALTER TABLE T1 
COALESCE PARTITION;

-- should be fail
ALTER TABLE T1 
COALESCE PARTITION;

-- result: 13
SELECT COUNT(*) FROM T1;


-- result: 13
SELECT COUNT(*) FROM T2;

-- should be success
ALTER TABLE T2 
COALESCE PARTITION;

-- should be success
ALTER TABLE T2 
COALESCE PARTITION;

-- should be success
ALTER TABLE T2 
COALESCE PARTITION;

-- should be fail
ALTER TABLE T2 
COALESCE PARTITION;

-- result: 13
SELECT COUNT(*) FROM T2;



--##############################
--+SECTOR; DstPart의 TBS 체크
--##############################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

ALTER TABLE T1 
COALESCE PARTITION;

-- Result: PDT_TBS2, PDT_TBS3, PDT_TBS
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND 
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T1'
ORDER BY A.PARTITION_NAME;


ALTER TABLE T2 
COALESCE PARTITION;

-- Result: PDT_TBS2, PDT_TBS3, PDT_TBS
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND 
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T2'
ORDER BY A.PARTITION_NAME;



--##############################
--+SECTOR; LOB 컬럼이 있는 경우의 COALESCE
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 DATE, I2 BLOB, I3 CLOB )
PARTITION BY HASH (I1) 
( PARTITION P1 TABLESPACE PDT_TBS 
                        LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ), 
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

INSERT INTO T1 VALUES ( TO_DATE('2007-05-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-06-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-07-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-08-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );

ALTER TABLE T1
COALESCE PARTITION;

-- result: 4
SELECT COUNT(*) FROM T1;


DROP TABLE T2;
CREATE TABLE T2 ( I1 DATE, I2 BLOB, I3 CLOB )
PARTITION BY HASH (I1) 
( PARTITION P1 TABLESPACE PDT_TBS 
                        LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ), 
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

INSERT INTO T2 VALUES ( TO_DATE('2007-05-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T2 VALUES ( TO_DATE('2007-06-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T2 VALUES ( TO_DATE('2007-07-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T2 VALUES ( TO_DATE('2007-08-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );

ALTER TABLE T2
COALESCE PARTITION;

-- result: 4
SELECT COUNT(*) FROM T2;


--##################################################################
--+SECTOR; DATA 비교
--# ( create 4 partition VS. create 5 partition + coalesce partition )
--##################################################################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

CREATE TABLE TEST( I1 DATE, I2 DATE, I3 INTEGER )
PARTITION BY HASH (I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4,
    PARTITION P5
) TABLESPACE PDT_TBS;

INSERT INTO TEST VALUES (NULL, TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-05-01', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-05-15', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-05-30', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-06-01', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-06-15', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-06-30', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-07-01', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-07-15', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-07-30', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-08-01', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-08-15', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-08-30', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);

ALTER TABLE TEST COALESCE PARTITION;

SELECT COUNT(*) FROM TEST PARTITION (P1);
SELECT COUNT(*) FROM TEST PARTITION (P2);
SELECT COUNT(*) FROM TEST PARTITION (P3);
SELECT COUNT(*) FROM TEST PARTITION (P4);

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

SELECT COUNT(*) FROM T2 PARTITION (P1) WHERE I1 < TO_DATE('2008-1-1', 'YYYY-MM-DD') OR I1 IS NULL;
SELECT COUNT(*) FROM T2 PARTITION (P2) WHERE I1 < TO_DATE('2008-1-1', 'YYYY-MM-DD') OR I1 IS NULL;
SELECT COUNT(*) FROM T2 PARTITION (P3) WHERE I1 < TO_DATE('2008-1-1', 'YYYY-MM-DD') OR I1 IS NULL;
SELECT COUNT(*) FROM T2 PARTITION (P4) WHERE I1 < TO_DATE('2008-1-1', 'YYYY-MM-DD') OR I1 IS NULL;


DROP TABLE TEST;


--##################################################################
--+SECTOR; ADD PARTITION + COALESCE PARTITION
--##################################################################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

ALTER TABLE T1 ADD PARTITION P1_1;
ALTER TABLE T1 ADD PARTITION P1_2;
ALTER TABLE T1 ADD PARTITION P1_3;
ALTER TABLE T1 ADD PARTITION P1_4;
ALTER TABLE T1 ADD PARTITION P1_5;
ALTER TABLE T1 ADD PARTITION P1_6;
ALTER TABLE T1 ADD PARTITION P1_7;
ALTER TABLE T1 ADD PARTITION P1_8;
ALTER TABLE T1 ADD PARTITION P1_9;

ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;
ALTER TABLE T1 COALESCE PARTITION;

-- should be fail
ALTER TABLE T1 COALESCE PARTITION;

-- result: 13
SELECT COUNT(*) FROM T1;


ALTER TABLE T2 ADD PARTITION P1_1;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 ADD PARTITION P1_2;
ALTER TABLE T2 ADD PARTITION P1_3;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 ADD PARTITION P1_4;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 ADD PARTITION P1_5;
ALTER TABLE T2 ADD PARTITION P1_6;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 ADD PARTITION P1_7;
ALTER TABLE T2 ADD PARTITION P1_8;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 ADD PARTITION P1_9;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 COALESCE PARTITION;
ALTER TABLE T2 COALESCE PARTITION;

-- should be fail
ALTER TABLE T2 COALESCE PARTITION;

-- result: 13
SELECT COUNT(*) FROM T2;



--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;
