--#######################################################################
--# BUG-35155 Partial CNF
--#######################################################################

--################################
--# PREPARATION
--################################

--+SKIP BEGIN;
DROP TABLE M1;
DROP TABLE D1;
DROP TABLE PDT1;
DROP VIEW  V1;
DROP TABLESPACE VOL_TBS INCLUDING CONTENTS AND DATAFILES;
--+SKIP END;

create volatile data tablespace VOL_TBS size 12M autoextend on maxsize 1G;

CREATE TABLE M1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER ) ;

CREATE TABLE D1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER ) TABLESPACE SYS_TBS_DISK_DATA;

CREATE TABLE PDT1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I2) ( PARTITION P1 VALUES DEFAULT ) TABLESPACE SYS_TBS_DISK_DATA;

CREATE VIEW V1 AS 
SELECT M1.I1, D1.I2, PDT1.I3 FROM M1, D1, PDT1 WHERE M1.I3 = D1.I3 AND D1.I3 = PDT1.I3;

create table VOL1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER ) tablespace VOL_TBS;


INSERT INTO M1 VALUES( 1, 1, 1 );
INSERT INTO M1 VALUES( 1, 2, 3 );

INSERT INTO D1 VALUES( 1, 1, 1 );
INSERT INTO D1 VALUES( 1, 2, 3 );

INSERT INTO PDT1 VALUES( 1, 1, 1 );
INSERT INTO PDT1 VALUES( 1, 2, 3 );

--INSERT INTO VOL1 VALUES( 1, 1, 1 );
--INSERT INTO VOL1 VALUES( 1, 2, 3 );

CREATE INDEX M1_IDX1 ON M1 ( I1, I2, I3 );
CREATE INDEX D1_IDX1 ON D1 ( I1, I2, I3 );
CREATE INDEX VOL1_IDX1 ON VOL1 ( I1, I2, I3 );

-- //+SET_ENV ALTIBASE_NORMALFORM_MAXIMUM = 10;
-- //+SET_ENV ALTIBASE_OPTIMIZER_PARTIAL_NORMALIZE = 1;
-- //+SYSTEM server stop;
-- //+SYSTEM server start;
--+SYSTEM is -f alter_partial_on.sql;

ALTER SYSTEM SET TRCLOG_DETAIL_PREDICATE=1;
