--###########################################################################
--# ported from qp4/Project3/PROJ-1624-GlobalIndex/PROJ-1624-QC/PDT/Design/UPDATE/integer_list.sql
--#
--# Body below is byte-identical to the original. The one line this port
--# adds is the premise: the original measures these statements on the
--# $GIT_ hidden-table implementation, this file measures the same
--# statements on the native global index (F07 -- see include/pinNative.sql).
--###########################################################################
--+LOAD_SQL ../../../include/pinNative.sql;

--######################################################
-- UPDATE LIST PARTITIOIN ( PK:INTEGER )
--######################################################

--###################################
--+SECTOR; INTIALIZE
--###################################

--+SKIP BEGIN;
DROP TABLE PDT_LIST;
--+SKIP END;

--#########################################
--+SECTOR; DO JOB #1 (1. Basic Test)
--#########################################

CREATE TABLE PDT_LIST
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY LIST( F1 )
(
    PARTITION P1 VALUES ( 10, 15 ),
    PARTITION P2 VALUES ( 20, 25 ),
    PARTITION P3 VALUES ( 30, 35 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

UPDATE PDT_LIST PARTITION( P1 ) SET F2 = F2;
UPDATE PDT_LIST PARTITION( P2 ) SET F2 = F2;
UPDATE PDT_LIST PARTITION( P3 ) SET F2 = F2;
UPDATE PDT_LIST PARTITION( P4 ) SET F2 = F2;


--#########################################
--+SECTOR; DO JOB #2 (2. Validation Test)
--#########################################

DROP TABLE PDT_LIST;
CREATE TABLE PDT_LIST
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY LIST( F1 )
(
    PARTITION P1 VALUES ( 10, 15 ),
    PARTITION P2 VALUES ( 20, 25 ),
    PARTITION P3 VALUES ( 30, 35 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

-- should be fail
UPDATE PDT_LIST PARTITION( P5 ) SET F2 = F2;


--#########################################
--+SECTOR; DO JOB #3 (3. Execution Test)
--#########################################

-------------------------------------
-- 3.1 Partition Pruning ( User )
-------------------------------------
DROP TABLE PDT_LIST;
CREATE TABLE PDT_LIST
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY LIST( F1 )
(
    PARTITION P1 VALUES ( 10, 15 ),
    PARTITION P2 VALUES ( 20, 25 ),
    PARTITION P3 VALUES ( 30, 35 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

-- please check plan
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_LIST PARTITION( P1 ) SET F2 = F2;
UPDATE PDT_LIST PARTITION( P2 ) SET F2 = F2;
UPDATE PDT_LIST PARTITION( P3 ) SET F2 = F2;
UPDATE PDT_LIST PARTITION( P4 ) SET F2 = F2;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

ALTER SESSION SET EXPLAIN PLAN = ON;
-- no need execution
UPDATE PDT_LIST PARTITION( P1 ) SET F2 = F2 
WHERE F1 >= 10 AND F1 < 20;
UPDATE PDT_LIST PARTITION( P2 ) SET F2 = F2 
WHERE F1 >= 20 AND F1 < 30;
ALTER SESSION SET EXPLAIN PLAN = OFF;

-------------------------------------
-- 3.2 Partition Pruning ( System )
-------------------------------------
DROP TABLE PDT_LIST;
CREATE TABLE PDT_LIST
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY LIST( F1 )
(
    PARTITION P1 VALUES ( 10, 15 ),
    PARTITION P2 VALUES ( 20, 25 ),
    PARTITION P3 VALUES ( 30, 35 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

-- less than 
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 < 10;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 < 20;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 < 30;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 < 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

-- equal
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 = 10;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 = 20;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 = 30;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 = 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

-- greater than
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 > 10;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 > 20;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 > 30;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 > 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

-- less equal than
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 <= 10;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 <= 20;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 <= 30;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 <= 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

-- greater equal than
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 >= 10;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 >= 20;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 >= 30;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 >= 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 >= 10 AND F1 < 20;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 >= 20 AND F1 < 30;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

-- not equal
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_LIST SET F2 = F2;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 != 10;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 != 20;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 != 30;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 != 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

-------------------------------------
-- 3.3 Partition filtering
-------------------------------------
DROP TABLE PDT_LIST;
CREATE TABLE PDT_LIST
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY LIST( F1 )
(
    PARTITION P1 VALUES ( 10, 15 ),
    PARTITION P2 VALUES ( 20, 25 ),
    PARTITION P3 VALUES ( 30, 35 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_LIST VALUES( 10, 0 );
INSERT INTO PDT_LIST VALUES( 20, 0 );
INSERT INTO PDT_LIST VALUES( 30, 0 );
INSERT INTO PDT_LIST VALUES( 40, 0 );

ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_LIST SET F2 = F2;
UPDATE PDT_LIST SET F2 = F2 WHERE F2 = 0;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 = F1;
UPDATE PDT_LIST SET F2 = F2 WHERE F1 = F2;
ALTER SESSION SET EXPLAIN PLAN = OFF;


--###################################
--+SECTOR; FINALIZE
--###################################

DROP TABLE PDT_LIST;
