TestSuiteDescription  = Simple TEMP Tablespace Regression (Expanded 62-case matrix)
###############################################################################
createCatalog.tc
addDropTempfile.tc
alterSizeAutoextend.tc
runtimeAutoextend.tc
runtimeResizeRestart.tc
dropReuse.tc
activeDataAliasReuse.tc
activeTempAliasReuse.tc
restartRecreate.tc
unsupportedDdl.tc
dataRoutingIsolation.tc
create_01.tc
create_02.tc
create_03.tc
create_04.tc
create_05.tc
create_06.tc
create_07.tc
create_08.tc
resize_01.tc
resize_02.tc
resize_03.tc
resize_04.tc
resize_05.tc
resize_06.tc
resize_07.tc
resize_08.tc
auto_01.tc
auto_02.tc
auto_03.tc
auto_04.tc
auto_05.tc
auto_06.tc
auto_07.tc
auto_08.tc
adddrop_01.tc
adddrop_02.tc
adddrop_03.tc
adddrop_04.tc
adddrop_05.tc
adddrop_06.tc
adddrop_07.tc
adddrop_08.tc
reject_01.tc
reject_02.tc
reject_03.tc
reject_04.tc
reject_05.tc
reject_06.tc
reject_07.tc
reject_08.tc
restart_01.tc
restart_02.tc
restart_03.tc
restart_04.tc
restart_05.tc
restart_06.tc
restart_07.tc
route_01.tc
route_02.tc
route_03.tc
route_04.tc
-------------------------------------------------------------------------------
