--######################################################
-- MOVE RANGE PARTITIOIN ( PK:INTEGER )
--######################################################

--###################################
--+SECTOR; INTIALIZE
--###################################

--+SKIP BEGIN;
DROP TABLE PDT_RANGE;
DROP TABLE PDT_RANGE_SRC;
--+SKIP END;

CREATE TABLE PDT_RANGE_SRC
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_RANGE_SRC VALUES( 0, 0 );
INSERT INTO PDT_RANGE_SRC VALUES( 10, 0 );
INSERT INTO PDT_RANGE_SRC VALUES( 20, 0 );
INSERT INTO PDT_RANGE_SRC VALUES( 30, 0 );

--#########################################
--+SECTOR; DO JOB #1 (1. Basic Test)
--#########################################

CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

MOVE INTO PDT_RANGE PARTITION( P1 ) FROM PDT_RANGE_SRC PARTITION( P1 );
MOVE INTO PDT_RANGE PARTITION( P2 ) FROM PDT_RANGE_SRC PARTITION( P2 );
MOVE INTO PDT_RANGE PARTITION( P3 ) FROM PDT_RANGE_SRC PARTITION( P3 );
MOVE INTO PDT_RANGE PARTITION( P4 ) FROM PDT_RANGE_SRC PARTITION( P4 );

-- should be [0]
SELECT F1 FROM PDT_RANGE PARTITION( P1 );
-- should be [10]
SELECT F1 FROM PDT_RANGE PARTITION( P2 );
-- should be [20]
SELECT F1 FROM PDT_RANGE PARTITION( P3 );
-- should be [30]
SELECT F1 FROM PDT_RANGE PARTITION( P4 );

MOVE INTO PDT_RANGE FROM PDT_RANGE_SRC PARTITION( P1 );
MOVE INTO PDT_RANGE FROM PDT_RANGE_SRC PARTITION( P2 );
MOVE INTO PDT_RANGE FROM PDT_RANGE_SRC PARTITION( P3 );
MOVE INTO PDT_RANGE FROM PDT_RANGE_SRC PARTITION( P4 );

-- should be [0,0]
SELECT F1 FROM PDT_RANGE PARTITION( P1 );
-- should be [10,10]
SELECT F1 FROM PDT_RANGE PARTITION( P2 );
-- should be [20,20]
SELECT F1 FROM PDT_RANGE PARTITION( P3 );
-- should be [30,30]
SELECT F1 FROM PDT_RANGE PARTITION( P4 );


--#########################################
--+SECTOR; DO JOB #2 (2. Validation Test)
--#########################################

INSERT INTO PDT_RANGE_SRC VALUES( 0, 0 );
INSERT INTO PDT_RANGE_SRC VALUES( 10, 0 );
INSERT INTO PDT_RANGE_SRC VALUES( 20, 0 );
INSERT INTO PDT_RANGE_SRC VALUES( 30, 0 );

DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
MOVE INTO PDT_RANGE PARTITION( P1 ) FROM PDT_RANGE_SRC;

-- should be fail
MOVE INTO PDT_RANGE PARTITION( P1 ) FROM PDT_RANGE_SRC PARTITION( P2 );
-- should be fail
MOVE INTO PDT_RANGE PARTITION( P2 ) FROM PDT_RANGE_SRC PARTITION( P3 );
-- should be fail
MOVE INTO PDT_RANGE PARTITION( P3 ) FROM PDT_RANGE_SRC PARTITION( P4 );
-- should be fail
MOVE INTO PDT_RANGE PARTITION( P4 ) FROM PDT_RANGE_SRC PARTITION( P1 );

-- should be 0
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P1 );
-- should be 0
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P2 );
-- should be 0
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P3 );
-- should be 0
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P4 );
-- should be 0
SELECT COUNT(*) FROM PDT_RANGE;

-- should be fail
MOVE INTO PDT_RANGE PARTITION( P1 ) FROM PDT_RANGE_SRC WHERE F1 < 20 AND F1 >= 10;
-- should be fail
MOVE INTO PDT_RANGE PARTITION( P2 ) FROM PDT_RANGE_SRC WHERE F1 < 30 AND F1 >= 20;
-- should be fail
MOVE INTO PDT_RANGE PARTITION( P3 ) FROM PDT_RANGE_SRC WHERE F1 < 40 AND F1 >= 30;
-- should be fail
MOVE INTO PDT_RANGE PARTITION( P4 ) FROM PDT_RANGE_SRC WHERE F1 < 10;

-- should be 0
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P1 );
-- should be 0
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P2 );
-- should be 0
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P3 );
-- should be 0
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P4 );
-- should be 0
SELECT COUNT(*) FROM PDT_RANGE;


--#########################################
--+SECTOR; DO JOB #3 (3. Execution Test)
--#########################################

DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
MOVE INTO PDT_RANGE PARTITION( P1 ) FROM PDT_RANGE_SRC WHERE F1 < 10;
-- should be success
MOVE INTO PDT_RANGE PARTITION( P2 ) FROM PDT_RANGE_SRC WHERE F1 < 20 AND F1 >= 10;
-- should be success
MOVE INTO PDT_RANGE PARTITION( P3 ) FROM PDT_RANGE_SRC WHERE F1 < 30 AND F1 >= 20;
-- should be success
MOVE INTO PDT_RANGE PARTITION( P4 ) FROM PDT_RANGE_SRC WHERE F1 < 100 AND F1 >= 30;

-- should be 1
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P1 );
-- should be 1
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P2 );
-- should be 1
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P3 );
-- should be 1
SELECT COUNT(*) FROM PDT_RANGE PARTITION( P4 );


--###################################
--+SECTOR; FINALIZE
--###################################

DROP TABLE PDT_RANGE;
DROP TABLE PDT_RANGE_SRC;
