--######################################################
-- MOVE HASH PARTITIOIN ( PK:INTEGER )
--######################################################

--###################################
--+SECTOR; INTIALIZE
--###################################

--+SKIP BEGIN;
DROP TABLE PDT_HASH;
DROP TABLE PDT_HASH_SRC;
--+SKIP END;

CREATE TABLE PDT_HASH_SRC
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY HASH( F1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO PDT_HASH_SRC VALUES( 0, 0 );
INSERT INTO PDT_HASH_SRC VALUES( 1, 0 );
INSERT INTO PDT_HASH_SRC VALUES( 2, 0 );
INSERT INTO PDT_HASH_SRC VALUES( 3, 0 );


--#########################################
--+SECTOR; DO JOB #1 (1. Basic Test)
--#########################################

CREATE TABLE PDT_HASH
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY HASH( F1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS;

MOVE INTO PDT_HASH PARTITION( P1 ) FROM PDT_HASH_SRC PARTITION( P1 );
MOVE INTO PDT_HASH PARTITION( P2 ) FROM PDT_HASH_SRC PARTITION( P2 );
MOVE INTO PDT_HASH PARTITION( P3 ) FROM PDT_HASH_SRC PARTITION( P3 );
MOVE INTO PDT_HASH PARTITION( P4 ) FROM PDT_HASH_SRC PARTITION( P4 );

-- should be [0]
SELECT F1 FROM PDT_HASH PARTITION( P1 );
-- should be [1]
SELECT F1 FROM PDT_HASH PARTITION( P2 );
-- should be [2]
SELECT F1 FROM PDT_HASH PARTITION( P3 );
-- should be [3]
SELECT F1 FROM PDT_HASH PARTITION( P4 );

MOVE INTO PDT_HASH FROM PDT_HASH_SRC PARTITION( P1 );
MOVE INTO PDT_HASH FROM PDT_HASH_SRC PARTITION( P2 );
MOVE INTO PDT_HASH FROM PDT_HASH_SRC PARTITION( P3 );
MOVE INTO PDT_HASH FROM PDT_HASH_SRC PARTITION( P4 );

-- should be [0,0]
SELECT F1 FROM PDT_HASH PARTITION( P1 );
-- should be [1,1]
SELECT F1 FROM PDT_HASH PARTITION( P2 );
-- should be [2,2]
SELECT F1 FROM PDT_HASH PARTITION( P3 );
-- should be [3,3]
SELECT F1 FROM PDT_HASH PARTITION( P4 );


--#########################################
--+SECTOR; DO JOB #2 (2. Validation Test)
--#########################################

INSERT INTO PDT_HASH_SRC VALUES( 0, 0 );
INSERT INTO PDT_HASH_SRC VALUES( 1, 0 );
INSERT INTO PDT_HASH_SRC VALUES( 2, 0 );
INSERT INTO PDT_HASH_SRC VALUES( 3, 0 );

DROP TABLE PDT_HASH;
CREATE TABLE PDT_HASH
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY HASH( F1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS;

-- should be fail
MOVE INTO PDT_HASH PARTITION( P1 ) FROM PDT_HASH_SRC;

-- should be fail
MOVE INTO PDT_HASH PARTITION( P1 ) FROM PDT_HASH_SRC PARTITION( P2 );
-- should be fail
MOVE INTO PDT_HASH PARTITION( P2 ) FROM PDT_HASH_SRC PARTITION( P3 );
-- should be fail
MOVE INTO PDT_HASH PARTITION( P3 ) FROM PDT_HASH_SRC PARTITION( P4 );
-- should be fail
MOVE INTO PDT_HASH PARTITION( P4 ) FROM PDT_HASH_SRC PARTITION( P1 );

-- should be 0
SELECT COUNT(*) FROM PDT_HASH PARTITION( P1 );
-- should be 0
SELECT COUNT(*) FROM PDT_HASH PARTITION( P2 );
-- should be 0
SELECT COUNT(*) FROM PDT_HASH PARTITION( P3 );
-- should be 0
SELECT COUNT(*) FROM PDT_HASH PARTITION( P4 );
-- should be 0
SELECT COUNT(*) FROM PDT_HASH;

-- should be fail
MOVE INTO PDT_HASH PARTITION( P1 ) FROM PDT_HASH_SRC WHERE F1 = 1;
-- should be fail
MOVE INTO PDT_HASH PARTITION( P2 ) FROM PDT_HASH_SRC WHERE F1 = 2;
-- should be fail
MOVE INTO PDT_HASH PARTITION( P3 ) FROM PDT_HASH_SRC WHERE F1 = 3;
-- should be fail
MOVE INTO PDT_HASH PARTITION( P4 ) FROM PDT_HASH_SRC WHERE F1 = 0;

-- should be 0
SELECT COUNT(*) FROM PDT_HASH PARTITION( P1 );
-- should be 0
SELECT COUNT(*) FROM PDT_HASH PARTITION( P2 );
-- should be 0
SELECT COUNT(*) FROM PDT_HASH PARTITION( P3 );
-- should be 0
SELECT COUNT(*) FROM PDT_HASH PARTITION( P4 );
-- should be 0
SELECT COUNT(*) FROM PDT_HASH;


--#########################################
--+SECTOR; DO JOB #3 (3. Execution Test)
--#########################################

DROP TABLE PDT_HASH;
CREATE TABLE PDT_HASH
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY HASH( F1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS;

-- should be success
MOVE INTO PDT_HASH PARTITION( P1 ) FROM PDT_HASH_SRC WHERE F1 = 0;
-- should be success
MOVE INTO PDT_HASH PARTITION( P2 ) FROM PDT_HASH_SRC WHERE F1 = 1;
-- should be success
MOVE INTO PDT_HASH PARTITION( P3 ) FROM PDT_HASH_SRC WHERE F1 = 2;
-- should be success
MOVE INTO PDT_HASH PARTITION( P4 ) FROM PDT_HASH_SRC WHERE F1 = 3;

-- should be 1
SELECT COUNT(*) FROM PDT_HASH PARTITION( P1 );
-- should be 1
SELECT COUNT(*) FROM PDT_HASH PARTITION( P2 );
-- should be 1
SELECT COUNT(*) FROM PDT_HASH PARTITION( P3 );
-- should be 1
SELECT COUNT(*) FROM PDT_HASH PARTITION( P4 );


--###################################
--+SECTOR; FINALIZE
--###################################

DROP TABLE PDT_HASH;
DROP TABLE PDT_HASH_SRC;
