--###################################################################
--# ALTER TABLE ... ALTER COLUMN LOB
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
--+SKIP END;

CREATE TABLE T1( I1 INTEGER, I2 CLOB DEFAULT 'DEFAULT', I3 BLOB )
PARTITION BY HASH (I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE SYS_TBS_DISK_DATA;

INSERT INTO T1 VALUES ( 1, 'CLOB1', 'FF' );
INSERT INTO T1 VALUES ( 2, 'CLOB2', 'FFFF' );
INSERT INTO T1 VALUES ( 3, 'CLOB3', 'FFFFFF' );
INSERT INTO T1 VALUES ( 4, 'CLOB4', 'FFFFFFFF' );
INSERT INTO T1 VALUES ( 5, 'CLOB5', 'FFFFFFFFFF' );

CREATE TABLE T2( I1 INTEGER, I2 CLOB DEFAULT 'DEFAULT', I3 BLOB )
PARTITION BY RANGE (I1)
(
    PARTITION P1 VALUES LESS THAN (2),
    PARTITION P2 VALUES LESS THAN (3),
    PARTITION P3 VALUES LESS THAN (4),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE SYS_TBS_DISK_DATA;

INSERT INTO T2 VALUES ( 1, 'CLOB1', 'FF' );
INSERT INTO T2 VALUES ( 2, 'CLOB2', 'FFFF' );
INSERT INTO T2 VALUES ( 3, 'CLOB3', 'FFFFFF' );
INSERT INTO T2 VALUES ( 4, 'CLOB4', 'FFFFFFFF' );
INSERT INTO T2 VALUES ( 5, 'CLOB5', 'FFFFFFFFFF' );


--#########################################################################
--+ SECTOR; 1. ADD PARTITION
--#########################################################################

---------------------------------------------------
-- 1.1 LOB STORE
---------------------------------------------------
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( NOLOGGING );
ALTER TABLE T1 ADD PARTITION P5;
-- {(P5,F,T), (P5,F,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T1 COALESCE PARTITION;

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 1.2 LOB( clob_column ) STORE
---------------------------------------------------
ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( NOLOGGING );
ALTER TABLE T1 ADD PARTITION P5;
-- {(P5,F,T), (P5,T,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T1 COALESCE PARTITION;

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 1.3 LOB( blob_column ) STORE
---------------------------------------------------
ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( NOLOGGING );
ALTER TABLE T1 ADD PARTITION P5;
-- {(P5,T,T), (P5,F,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T1 COALESCE PARTITION;

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 1.4 LOB( * ) STORE
---------------------------------------------------
ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( NOLOGGING );
ALTER TABLE T1 ADD PARTITION P5;
-- {(P5,F,T), (P5,F,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T1 COALESCE PARTITION;


--#########################################################################
--+ SECTOR; 2. SPLIT PARTITION
--#########################################################################

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 2.1 LOB STORE
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( NOLOGGING );
ALTER TABLE T2 SPLIT PARTITION P4 AT(5) INTO ( PARTITION P4, PARTITION P5 );
-- {(P5,F,T), (P5,F,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T2' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T2 MERGE PARTITIONS P4, P5 INTO PARTITION P4;

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 2.2 LOB( clob_column ) STORE
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB(I2) STORE AS ( NOLOGGING );
ALTER TABLE T2 SPLIT PARTITION P4 AT(5) INTO ( PARTITION P4, PARTITION P5 );
-- {(P5,F,T), (P5,T,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T2' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T2 MERGE PARTITIONS P4, P5 INTO PARTITION P4;

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 2.3 LOB( blob_column ) STORE
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB(I3) STORE AS ( NOLOGGING );
ALTER TABLE T2 SPLIT PARTITION P4 AT(5) INTO ( PARTITION P4, PARTITION P5 );
-- {(P5,T,T), (P5,F,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T2' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T2 MERGE PARTITIONS P4, P5 INTO PARTITION P4;

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 2.4 LOB( * ) STORE
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB(I2, I3) STORE AS ( NOLOGGING );
ALTER TABLE T2 SPLIT PARTITION P4 AT(5) INTO ( PARTITION P4, PARTITION P5 );
-- {(P5,F,T), (P5,F,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T2' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T2 MERGE PARTITIONS P4, P5 INTO PARTITION P4;

--#########################################################################
--+ SECTOR; 3. MERGE PARTITION
--#########################################################################

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 2.1 LOB STORE
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( NOLOGGING );
ALTER TABLE T2 MERGE PARTITIONS P3, P4 INTO PARTITION P5;
-- {(P5,F,T), (P5,F,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T2' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T2 SPLIT PARTITION P5 AT(4) INTO ( PARTITION P3, PARTITION P4 );

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 2.2 LOB( clob_column ) STORE
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB(I2) STORE AS ( NOLOGGING );
ALTER TABLE T2 MERGE PARTITIONS P3, P4 INTO PARTITION P5;
-- {(P5,F,T), (P5,T,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T2' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T2 SPLIT PARTITION P5 AT(4) INTO ( PARTITION P3, PARTITION P4 );

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 2.3 LOB( blob_column ) STORE
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB(I3) STORE AS ( NOLOGGING );
ALTER TABLE T2 MERGE PARTITIONS P3, P4 INTO PARTITION P5;
-- {(P5,T,T), (P5,F,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T2' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T2 SPLIT PARTITION P5 AT(4) INTO ( PARTITION P3, PARTITION P4 );

---------------------------------------------------
-- 초기화
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );

---------------------------------------------------
-- 2.4 LOB( * ) STORE
---------------------------------------------------
ALTER TABLE T2 ALTER COLUMN LOB(I2, I3) STORE AS ( NOLOGGING );
ALTER TABLE T2 MERGE PARTITIONS P3, P4 INTO PARTITION P5;
-- {(P5,F,T), (P5,F,T)}
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T2' AND 
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      PART.PARTITION_NAME = 'P5'
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;
ALTER TABLE T2 SPLIT PARTITION P5 AT(4) INTO ( PARTITION P3, PARTITION P4 );

--###################################################################
--+ SECTOR; FINALIZATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
--+SKIP END;

