--###################################################################
--# ALTER TABLE ... ADD PARTITIONS (PartKey: DATE)
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

--+APPEND_LST Schema_Hash_Date.sql;
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

--###################################################################
--+ SECTOR; BASIC TEST
--###################################################################
--##############################
--+SECTOR; 문법 체크
--##############################
DROP TABLE TEST;
CREATE TABLE TEST( I1 DATE, I2 INTEGER )
PARTITION BY HASH(I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS;

-- should be fail
ALTER TABLE TEST 
ADD PARTITION P1_1 TABLESPACE PDT_TBS2, P1_2;

DROP TABLE TEST;

--##############################
--+SECTOR; 파티션드 테이블인지 체크
--##############################
DROP TABLE TEST;
CREATE TABLE TEST( I1 DATE, I2 INTEGER );

-- should be fail
ALTER TABLE TEST 
ADD PARTITION P1_1 TABLESPACE PDT_TBS2;

DROP TABLE TEST;


--##############################
--+SECTOR; DstPart 파티션 이름 체크
--##############################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

-- should be fail
ALTER TABLE T1 
ADD PARTITION P1;

-- should be fail
ALTER TABLE T1 
ADD PARTITION P2;

-- should be fail
ALTER TABLE T1 
ADD PARTITION P3;

-- should be fail
ALTER TABLE T1 
ADD PARTITION P4;

-- should be success 
ALTER TABLE T1 
ADD PARTITION P5;

-- should be fail
ALTER TABLE T1 
ADD PARTITION P5;

-- should be fail
ALTER TABLE T1 
ADD PARTITION P5 TABLESPACE PDT_TBS3;

-- should be fail
ALTER TABLE T1 
ADD PARTITION P4 TABLESPACE PDT_TBS2;

-- should be fail
ALTER TABLE T1 
ADD PARTITION P3 TABLESPACE PDT_TBS;


--##############################
--+SECTOR; DstPart의 TBS 체크
--##############################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

ALTER TABLE T1 
ADD PARTITION P5;

-- Result: PDT_TBS
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND 
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T1' AND
      A.PARTITION_NAME = 'P5';

ALTER TABLE T1 
ADD PARTITION P6 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND 
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T1' AND
      A.PARTITION_NAME = 'P5';


ALTER TABLE T2 
ADD PARTITION P5;

-- Result: PDT_TBS
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND 
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T2' AND
      A.PARTITION_NAME = 'P5';

ALTER TABLE T2 
ADD PARTITION P6 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND 
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T2' AND
      A.PARTITION_NAME = 'P6';



--##############################
--+SECTOR; DstPart의 LOB 컬럼의 TBS 체크
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 DATE, I2 BLOB, I3 CLOB )
PARTITION BY HASH (I1) 
( PARTITION P1 TABLESPACE PDT_TBS 
                        LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ), 
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

INSERT INTO T1 VALUES ( TO_DATE('2007-05-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-06-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-07-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-08-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );

ALTER TABLE T1
ADD PARTITION P4;

-- result: 4
SELECT COUNT(*) FROM T1;

-- result: PDT_TBS4
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T1' AND
      A.PARTITION_NAME='P4';

-- Result: PDT_TBS4, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P4'
ORDER BY LOBS.COLUMN_ID ASC;


DROP TABLE T1;
CREATE TABLE T1 ( I1 DATE, I2 BLOB, I3 CLOB )
PARTITION BY HASH (I1) 
( PARTITION P1 TABLESPACE PDT_TBS 
                            LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ), 
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

INSERT INTO T1 VALUES ( TO_DATE('2007-05-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-06-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-07-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-08-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );

ALTER TABLE T1
ADD PARTITION P4 TABLESPACE PDT_TBS2 LOB(I2) STORE AS ( TABLESPACE PDT_TBS3 );

-- result: 4
SELECT COUNT(*) FROM T1;

-- result: PDT_TBS2
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T1' AND
      A.PARTITION_NAME='P4';

-- Result: PDT_TBS3, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P4'
ORDER BY LOBS.COLUMN_ID ASC;


DROP TABLE T1;
CREATE TABLE T1 ( I1 DATE, I2 BLOB, I3 CLOB )
PARTITION BY HASH (I1)
( PARTITION P1 TABLESPACE PDT_TBS                  
                            LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ),  
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

INSERT INTO T1 VALUES ( TO_DATE('2007-05-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-06-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-07-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-08-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );

ALTER TABLE T1
ADD PARTITION P4 TABLESPACE PDT_TBS2;

-- result: 4
SELECT COUNT(*) FROM T1;

-- result: PDT_TBS2
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T1' AND
      A.PARTITION_NAME='P4';

-- Result: PDT_TBS2, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P4'
ORDER BY LOBS.COLUMN_ID ASC;


DROP TABLE T1;
CREATE TABLE T1 ( I1 DATE, I2 BLOB, I3 CLOB )
PARTITION BY HASH (I1)
( PARTITION P1 TABLESPACE PDT_TBS                  
                            LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ),  
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

INSERT INTO T1 VALUES ( TO_DATE('2007-05-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-06-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-07-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( TO_DATE('2007-08-01', 'YYYY-MM-DD'),   'ABC', 'DEF' );

ALTER TABLE T1
ADD PARTITION P4 LOB STORE AS ( TABLESPACE PDT_TBS3 );

-- result: 4
SELECT COUNT(*) FROM T1;

-- result: PDT_TBS4
SELECT C.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A, SYSTEM_.SYS_TABLES_ B, V$TABLESPACES C
WHERE A.TABLE_ID = B.TABLE_ID AND
      A.TBS_ID = C.ID AND
      B.TABLE_NAME = 'T1' AND
      A.PARTITION_NAME='P4';

-- Result: PDT_TBS3, PDT_TBS3
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P4'
ORDER BY LOBS.COLUMN_ID ASC;



--##################################################################
--+SECTOR; DATA 비교(create 5 partition VS. create 4 partition + add partition)
--##################################################################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

CREATE TABLE TEST( I1 DATE, I2 DATE, I3 INTEGER )
PARTITION BY HASH (I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4,
    PARTITION P5
) TABLESPACE PDT_TBS;

INSERT INTO TEST VALUES (NULL, TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-05-01', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-05-15', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-05-30', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-06-01', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-06-15', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-06-30', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-07-01', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-07-15', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-07-30', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-08-01', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-08-15', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);
INSERT INTO TEST VALUES (TO_DATE('2007-08-30', 'YYYY-MM-DD'), TO_DATE('2007-05-01', 'YYYY-MM-DD'), 100);


SELECT COUNT(*) FROM TEST PARTITION (P1);
SELECT COUNT(*) FROM TEST PARTITION (P2);
SELECT COUNT(*) FROM TEST PARTITION (P3);
SELECT COUNT(*) FROM TEST PARTITION (P4);
SELECT COUNT(*) FROM TEST PARTITION (P5);

ALTER TABLE T1 ADD PARTITION P5;

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);
SELECT COUNT(*) FROM T1 PARTITION (P5);

ALTER TABLE T2 ADD PARTITION P5;

SELECT COUNT(*) FROM T2 PARTITION (P1) WHERE I1 < TO_DATE('2008-1-1', 'YYYY-MM-DD') OR I1 IS NULL;
SELECT COUNT(*) FROM T2 PARTITION (P2) WHERE I1 < TO_DATE('2008-1-1', 'YYYY-MM-DD') OR I1 IS NULL;
SELECT COUNT(*) FROM T2 PARTITION (P3) WHERE I1 < TO_DATE('2008-1-1', 'YYYY-MM-DD') OR I1 IS NULL;
SELECT COUNT(*) FROM T2 PARTITION (P4) WHERE I1 < TO_DATE('2008-1-1', 'YYYY-MM-DD') OR I1 IS NULL;
SELECT COUNT(*) FROM T2 PARTITION (P5) WHERE I1 < TO_DATE('2008-1-1', 'YYYY-MM-DD') OR I1 IS NULL;

DROP TABLE TEST;


--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;
