--######################################################
-- ADD PARTITIOIN ( PK:INTEGER )
--######################################################

--###################################
--+SECTOR; INTIALIZE
--###################################

--+SKIP BEGIN;
DROP TABLE PDT_HASH;
--+SKIP END;

--#########################################
--+SECTOR; DO JOB #1 (1. Basic Test)
--#########################################

------------------------------------------
-- 1.1 ADD PARTITION WITH 4 PARTITON
--     VS. PARTITIONED TABLE WITH 5 PARTITON
------------------------------------------
CREATE TABLE PDT_HASH
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY HASH( F1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO PDT_HASH VALUES( 0, 0 );
INSERT INTO PDT_HASH VALUES( 1, 0 );
INSERT INTO PDT_HASH VALUES( 2, 0 );
INSERT INTO PDT_HASH VALUES( 3, 0 );
INSERT INTO PDT_HASH VALUES( 4, 0 );
INSERT INTO PDT_HASH VALUES( 5, 0 );
INSERT INTO PDT_HASH VALUES( 6, 0 );
INSERT INTO PDT_HASH VALUES( 7, 0 );
INSERT INTO PDT_HASH VALUES( 8, 0 );
INSERT INTO PDT_HASH VALUES( 9, 0 );

SELECT F1 FROM PDT_HASH PARTITION( P1 );
SELECT F1 FROM PDT_HASH PARTITION( P2 );
SELECT F1 FROM PDT_HASH PARTITION( P3 );
SELECT F1 FROM PDT_HASH PARTITION( P4 );

-- should be 10
SELECT COUNT(*) FROM PDT_HASH;

ALTER TABLE PDT_HASH
ADD PARTITION P5;

SELECT F1 FROM PDT_HASH PARTITION( P1 );
SELECT F1 FROM PDT_HASH PARTITION( P2 );
SELECT F1 FROM PDT_HASH PARTITION( P3 );
SELECT F1 FROM PDT_HASH PARTITION( P4 );
SELECT F1 FROM PDT_HASH PARTITION( P5 );

-- should be 10
SELECT COUNT(*) FROM PDT_HASH;

DROP TABLE PDT_HASH;
CREATE TABLE PDT_HASH
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY HASH( F1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4,
    PARTITION P5
) TABLESPACE PDT_TBS;

INSERT INTO PDT_HASH VALUES( 0, 0 );
INSERT INTO PDT_HASH VALUES( 1, 0 );
INSERT INTO PDT_HASH VALUES( 2, 0 );
INSERT INTO PDT_HASH VALUES( 3, 0 );
INSERT INTO PDT_HASH VALUES( 4, 0 );
INSERT INTO PDT_HASH VALUES( 5, 0 );
INSERT INTO PDT_HASH VALUES( 6, 0 );
INSERT INTO PDT_HASH VALUES( 7, 0 );
INSERT INTO PDT_HASH VALUES( 8, 0 );
INSERT INTO PDT_HASH VALUES( 9, 0 );

SELECT F1 FROM PDT_HASH PARTITION( P1 );
SELECT F1 FROM PDT_HASH PARTITION( P2 );
SELECT F1 FROM PDT_HASH PARTITION( P3 );
SELECT F1 FROM PDT_HASH PARTITION( P4 );
SELECT F1 FROM PDT_HASH PARTITION( P5 );

-- should be 10
SELECT COUNT(*) FROM PDT_HASH;

------------------------------------------
-- 1.2 ADD PARTITION WITH 4 PARTITON(INDEX)
--     VS. PARTITIONED TABLE WITH 5 PARTITON
------------------------------------------
DROP TABLE PDT_HASH;

CREATE TABLE PDT_HASH
(
    F1   INTEGER PRIMARY KEY,
    F2   INTEGER
) 
PARTITION BY HASH( F1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO PDT_HASH VALUES( 0, 0 );
INSERT INTO PDT_HASH VALUES( 1, 0 );
INSERT INTO PDT_HASH VALUES( 2, 0 );
INSERT INTO PDT_HASH VALUES( 3, 0 );
INSERT INTO PDT_HASH VALUES( 4, 0 );
INSERT INTO PDT_HASH VALUES( 5, 0 );
INSERT INTO PDT_HASH VALUES( 6, 0 );
INSERT INTO PDT_HASH VALUES( 7, 0 );
INSERT INTO PDT_HASH VALUES( 8, 0 );
INSERT INTO PDT_HASH VALUES( 9, 0 );

SELECT F1 FROM PDT_HASH PARTITION( P1 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P2 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P3 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P4 ) WHERE F1 < 10;

-- should be 10
SELECT COUNT(*) FROM PDT_HASH;

ALTER TABLE PDT_HASH
ADD PARTITION P5;

SELECT F1 FROM PDT_HASH PARTITION( P1 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P2 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P3 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P4 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P5 ) WHERE F1 < 10;

-- should be 10
SELECT COUNT(*) FROM PDT_HASH;


DROP TABLE PDT_HASH;

CREATE TABLE PDT_HASH
(
    F1   INTEGER PRIMARY KEY,
    F2   INTEGER
) 
PARTITION BY HASH( F1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4,
    PARTITION P5
) TABLESPACE PDT_TBS;

INSERT INTO PDT_HASH VALUES( 0, 0 );
INSERT INTO PDT_HASH VALUES( 1, 0 );
INSERT INTO PDT_HASH VALUES( 2, 0 );
INSERT INTO PDT_HASH VALUES( 3, 0 );
INSERT INTO PDT_HASH VALUES( 4, 0 );
INSERT INTO PDT_HASH VALUES( 5, 0 );
INSERT INTO PDT_HASH VALUES( 6, 0 );
INSERT INTO PDT_HASH VALUES( 7, 0 );
INSERT INTO PDT_HASH VALUES( 8, 0 );
INSERT INTO PDT_HASH VALUES( 9, 0 );

SELECT F1 FROM PDT_HASH PARTITION( P1 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P2 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P3 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P4 ) WHERE F1 < 10;
SELECT F1 FROM PDT_HASH PARTITION( P5 ) WHERE F1 < 10;

-- should be 10
SELECT COUNT(*) FROM PDT_HASH;

--#########################################
--+SECTOR; DO JOB #2 (2. Validation Test)
--#########################################

------------------------------------------
-- 2.1 파티션 이름 중복 검사
------------------------------------------
-- should be fail
ALTER TABLE PDT_HASH
ADD PARTITION P1;

------------------------------------------
-- 2.2 메모리 테이블스페이스 검사
------------------------------------------
-- should be fail
ALTER TABLE PDT_HASH
ADD PARTITION P6 
TABLESPACE SYS_TBS_MEM_DATA;


--#########################################
--+SECTOR; DO JOB #3 (3. Execution Test)
--#########################################

-- nothing to do


--###################################
--+SECTOR; FINALIZE
--###################################

DROP TABLE PDT_HASH;
