DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

CREATE TABLE T3 ( I1 INTEGER, I2 BLOB, I3 CLOB, I4 INTEGER )
PARTITION BY HASH(I1)
( PARTITION P1 TABLESPACE PDT_TBS2 
                                LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS3 ), 
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3
) TABLESPACE PDT_TBS LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

INSERT INTO T3 VALUES (0,   'ABC', 'DEF', 100);
INSERT INTO T3 VALUES (50,  'ABC', 'DEF', 100);
INSERT INTO T3 VALUES (100, 'ABC', 'DEF', 100);
INSERT INTO T3 VALUES (150, 'ABC', 'DEF', 100);
INSERT INTO T3 VALUES (200, 'ABC', 'DEF', 100);
INSERT INTO T3 VALUES (250, 'ABC', 'DEF', 100);
INSERT INTO T3 VALUES (300, 'ABC', 'DEF', 100);
INSERT INTO T3 VALUES (350, 'ABC', 'DEF', 100);

CREATE INDEX IDX1 ON T3(I1);

CREATE INDEX IDX2 ON T3(I4);

CREATE INDEX IDX3 ON T3(I1, I4);