--###################################################################
--# DROP TABLESPACE
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS5
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;
--+SKIP END;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS2
DATAFILE 'TBS2.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS3
DATAFILE 'TBS3.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS4
DATAFILE 'TBS4.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS5
DATAFILE 'TBS5.dbf'
SIZE 10M
AUTOEXTEND ON;



--###################################################################
--+ SECTOR; LOB 컬럼이 없는 경우
--###################################################################

--##############################
--+SECTOR; 인덱스 파티션 없는 경우
--##############################

--------------------------------
-- 테이블 파티션이 하나의 TBS에 다 들어가 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

--------------------------------
-- 테이블 파티션이 다른 TBS에 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS2,
    PARTITION P3 VALUES LESS THAN (300) TABLESPACE TBS3,
    PARTITION P4 VALUES DEFAULT TABLESPACE TBS4
) TABLESPACE TBS1;

-- should be fail
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;


--##############################
--+SECTOR; 인덱스 파티션이 있는 경우
--##############################

--------------------------------
-- 테이블 파티션, 인덱스 파티션이 하나의 TBS에 다 들어가 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1;

CREATE INDEX IDX1 ON T1(I1) LOCAL;
CREATE INDEX IDX2 ON T1(I2) LOCAL;
CREATE INDEX IDX3 ON T1(I1, I2) LOCAL;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

--------------------------------
-- 인덱스 파티션이 다른 TBS에 들어가 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1;

CREATE INDEX IDX1 ON T1(I1) LOCAL
(
    PARTITION P1_IDX1 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX1 ON P2 TABLESPACE TBS2,
    PARTITION P3_IDX1 ON P3 TABLESPACE TBS3,
    PARTITION P4_IDX1 ON P4 TABLESPACE TBS4
);

CREATE INDEX IDX2 ON T1(I2) LOCAL
(
    PARTITION P1_IDX2 ON P1 TABLESPACE TBS4,
    PARTITION P2_IDX2 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX2 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX2 ON P4 TABLESPACE TBS1
);

CREATE INDEX IDX3 ON T1(I1, I2) LOCAL
(
    PARTITION P1_IDX3 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX3 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX3 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX3 ON P4 TABLESPACE TBS4
);

-- should be fail
DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

--------------------------------
-- 테이블 파티션, 인덱스 파티션이 모두 다른 TBS에 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS2,
    PARTITION P3 VALUES LESS THAN (300) TABLESPACE TBS3,
    PARTITION P4 VALUES DEFAULT TABLESPACE TBS4
) TABLESPACE TBS1;

CREATE INDEX IDX1 ON T1(I1) LOCAL
(
    PARTITION P1_IDX1 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX1 ON P2 TABLESPACE TBS2,
    PARTITION P3_IDX1 ON P3 TABLESPACE TBS3,
    PARTITION P4_IDX1 ON P4 TABLESPACE TBS4
);

CREATE INDEX IDX2 ON T1(I2) LOCAL
(
    PARTITION P1_IDX2 ON P1 TABLESPACE TBS4,
    PARTITION P2_IDX2 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX2 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX2 ON P4 TABLESPACE TBS1
);

CREATE INDEX IDX3 ON T1(I1, I2) LOCAL
(
    PARTITION P1_IDX3 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX3 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX3 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX3 ON P4 TABLESPACE TBS4
);

-- should be fail
DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;


--##############################
--+SECTOR; 외래키가 있는 경우
--##############################
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

CREATE TABLE T1 ( I1 INTEGER UNIQUE, I2 INTEGER )
PARTITION BY RANGE(I1)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1;
CREATE INDEX IDX1 ON T1(I2) LOCAL;
CREATE INDEX IDX2 ON T1(I1, I2) LOCAL;

CREATE TABLE T2 ( I1 INTEGER UNIQUE, I2 INTEGER ) TABLESPACE TBS2;
CREATE INDEX IDX3 ON T2(I2);
CREATE INDEX IDX4 ON T2(I1, I2);

CREATE TABLE T3 ( I1 INTEGER UNIQUE, I2 INTEGER )
PARTITION BY RANGE(I1)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS3;
CREATE INDEX IDX5 ON T3(I2) LOCAL;
CREATE INDEX IDX6 ON T3(I1, I2) LOCAL;


ALTER TABLE T2 ADD CONSTRAINT T2_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T3 ADD CONSTRAINT T3_FK FOREIGN KEY(I2) REFERENCES T2(I1);


-- should be success
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS2
DATAFILE 'TBS2.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS3
DATAFILE 'TBS3.dbf'
SIZE 10M
AUTOEXTEND ON;

DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;


--###################################################################
--+ SECTOR; LOB 컬럼이 있는 경우
--###################################################################

--##############################
--+SECTOR; 인덱스 파티션 없는 경우
--##############################

--------------------------------
-- 테이블 파티션이 하나의 TBS에 다 들어가 있는 경우
--------------------------------
DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 BLOB, I4 CLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE TBS4
                                    LOB(I3, I4) STORE AS ( TABLESPACE TBS2 ), 
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS3,
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1 LOB(I4) STORE AS ( TABLESPACE TBS5 );

CREATE INDEX IDX1 ON T1(I1) LOCAL
(
    PARTITION P1_IDX1 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX1 ON P2 TABLESPACE TBS2,
    PARTITION P3_IDX1 ON P3 TABLESPACE TBS3,
    PARTITION P4_IDX1 ON P4 TABLESPACE TBS4
);

CREATE INDEX IDX2 ON T1(I2) LOCAL
(
    PARTITION P1_IDX2 ON P1 TABLESPACE TBS4,
    PARTITION P2_IDX2 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX2 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX2 ON P4 TABLESPACE TBS1
);

CREATE INDEX IDX3 ON T1(I1, I2) LOCAL
(
    PARTITION P1_IDX3 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX3 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX3 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX3 ON P4 TABLESPACE TBS4
);

-- should be success
DROP TABLESPACE TBS5
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

-- should be success
DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;


--##############################
--+SECTOR; 외래키가 있는 경우
--##############################
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS2
DATAFILE 'TBS2.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS3
DATAFILE 'TBS3.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS4
DATAFILE 'TBS4.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS5
DATAFILE 'TBS5.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLE T1 ( I1 INTEGER UNIQUE, I2 INTEGER, I3 BLOB, I4 CLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE TBS4
                                    LOB(I3, I4) STORE AS ( TABLESPACE TBS2 ), 
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS3,
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1 LOB(I4) STORE AS ( TABLESPACE TBS5 );
CREATE INDEX IDX1 ON T1(I2) LOCAL;
CREATE INDEX IDX2 ON T1(I1, I2) LOCAL;

CREATE TABLE T2 ( I1 INTEGER UNIQUE, I2 INTEGER ) TABLESPACE TBS2;
CREATE INDEX IDX3 ON T2(I2);
CREATE INDEX IDX4 ON T2(I1, I2);

CREATE TABLE T3 ( I1 INTEGER UNIQUE, I2 INTEGER, I3 BLOB, I4 CLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE TBS4
                                    LOB(I3, I4) STORE AS ( TABLESPACE TBS2 ), 
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS1,
  PARTITION P3 VALUES DEFAULT
) TABLESPACE TBS3 LOB(I4) STORE AS ( TABLESPACE TBS5 );
CREATE INDEX IDX5 ON T3(I2) LOCAL;
CREATE INDEX IDX6 ON T3(I1, I2) LOCAL;


ALTER TABLE T2 ADD CONSTRAINT T2_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T3 ADD CONSTRAINT T3_FK FOREIGN KEY(I2) REFERENCES T2(I1);

-- should be success
DROP TABLESPACE TBS5
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

-- should be success
DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS2
DATAFILE 'TBS2.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS3
DATAFILE 'TBS3.dbf'
SIZE 10M
AUTOEXTEND ON;



--###################################################################
--+ SECTOR; FINALIZATION
--###################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS5
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;
--+SKIP END;


