###########################################################################
# pk/uk without prefix constraint; Initialize tablespace
###########################################################################

--+SKIP BEGIN;
DROP TABLESPACE PDT_TBS 
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE PMT_TBS 
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE PVT_TBS 
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

--+SKIP END;

CREATE DISK TABLESPACE PDT_TBS DATAFILE 'PDT_TBS.dbf' SIZE 50M AUTOEXTEND ON;

CREATE MEMORY TABLESPACE PMT_TBS SIZE 32M AUTOEXTEND ON CHECKPOINT PATH 'dbs';

CREATE VOLATILE TABLESPACE PVT_TBS SIZE 32M AUTOEXTEND ON;

