--###################################################################
--# DELETE TEST
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T4 CASCADE;
--+SKIP END;



--###################################################################
--+SECTOR; 각 데이터 타입별 DELETE
--###################################################################

--##############################
--+SECTOR; INTEGER, BIGINT, SMALLINT
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER UNIQUE, I2 BIGINT , I3 SMALLINT )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN (300) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 100, 100);
INSERT INTO T1 VALUES (100, 110, 110);
INSERT INTO T1 VALUES (200, 120, 120);
INSERT INTO T1 VALUES (300, 130, 130);

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be {}
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; BIT(10), BIT(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 BIT(10), I2 BIT(1000) )
PARTITION BY RANGE (I1, I2)
( PARTITION P1 VALUES LESS THAN ( BIT'100' ) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN ( BIT'110' ) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN ( BIT'111' ) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, BIT'100');
INSERT INTO T1 VALUES (BIT'100', BIT'100');
INSERT INTO T1 VALUES (BIT'110', BIT'100');
INSERT INTO T1 VALUES (BIT'111', BIT'100');

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be {}
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; BLOB, CLOB
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 BLOB, I3 CLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN ( 100 ) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN ( 200 ) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN ( 300 ) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 'ABC', 'ABC');
INSERT INTO T1 VALUES (100, 'ABC', 'ABC');
INSERT INTO T1 VALUES (200, 'ABC', 'ABC');
INSERT INTO T1 VALUES (300, 'ABC', 'ABC');

DELETE FROM T1 PARTITION(P1) WHERE I1 < 100;
DELETE FROM T1 PARTITION(P2) WHERE I1 < 200;
DELETE FROM T1 PARTITION(P3) WHERE I1 < 300;
DELETE FROM T1 PARTITION(P4);

-- should be 0
SELECT COUNT(*) FROM T1;


--##############################
--+SECTOR; BYTE(1000), NIBBLE(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 BYTE(1000), I3 NIBBLE(254) )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN ( 100 ) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN ( 200 ) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN ( 300 ) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 'ABC', 'ABC');
INSERT INTO T1 VALUES (100, 'ABC', 'ABC');
INSERT INTO T1 VALUES (200, 'ABC', 'ABC');
INSERT INTO T1 VALUES (300, 'ABC', 'ABC');

DELETE FROM T1 WHERE I1 > 0;

-- should be 1
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; CHAR(10), CHAR(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 CHAR(10), I2 CHAR(1000) )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN ( '100' ) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN ( '200' ) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN ( '300' ) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 'ABC');
INSERT INTO T1 VALUES ('100', 'ABC');
INSERT INTO T1 VALUES ('200', 'ABC');
INSERT INTO T1 VALUES ('300', 'ABC');

DELETE FROM T1 WHERE I1 > '000';

-- should be 1
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; DATE
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 DATE )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN ( TO_DATE('2007-05-05', 'YYYY-MM-DD') ) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN ( TO_DATE('2007-06-05', 'YYYY-MM-DD') ) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN ( TO_DATE('2007-07-05', 'YYYY-MM-DD') ) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD') );
INSERT INTO T1 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD') );
INSERT INTO T1 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD') );

DELETE FROM T1 WHERE I1 > TO_DATE('2006-12-25', 'YYYY-MM-DD');

-- should be 1
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; DOUBLE, FLOAT, REAL
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 DOUBLE, I2 FLOAT, I3 REAL )
PARTITION BY RANGE (I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100.5) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN (200.5) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN (300.5) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 100.5, 100.5);
INSERT INTO T1 VALUES (100.5, 100.5, 100.5);
INSERT INTO T1 VALUES (200.5, 100.5, 100.5);
INSERT INTO T1 VALUES (300.5, 100.5, 100.5);

DELETE FROM T1 WHERE I1 = I1;

-- should be 1
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; NUMERIC
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 NUMERIC(20, 5) )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100.505) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN (200.505) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN (300.505) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (100.505);
INSERT INTO T1 VALUES (200.505);
INSERT INTO T1 VALUES (300.505);

-- should be {100.505, 200.505, 300.505, NULL}
SELECT * FROM T1 ORDER BY I1;

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be 0
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; VARBIT(10), VARBIT(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 VARBIT(10), I2 VARBIT(1000) )
PARTITION BY RANGE (I1, I2)
( PARTITION P1 VALUES LESS THAN (VARBIT'100') TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN (VARBIT'110') TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN (VARBIT'111') TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, VARBIT'100');
INSERT INTO T1 VALUES (VARBIT'100', VARBIT'100');
INSERT INTO T1 VALUES (VARBIT'110', VARBIT'100');
INSERT INTO T1 VALUES (VARBIT'111', VARBIT'100');

-- should be {'100', '110', '111', NULL}
SELECT * FROM T1 ORDER BY I1;

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be 0
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; VARCHAR(10), VARCHAR(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 VARCHAR(10), I2 VARCHAR(1000) )
PARTITION BY RANGE (I1, I2)
( PARTITION P1 VALUES LESS THAN ('100') TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN ('200') TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN ('300') TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, '100');
INSERT INTO T1 VALUES ('100', '100');
INSERT INTO T1 VALUES ('200', '100');
INSERT INTO T1 VALUES ('300', '100');

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be 0
SELECT * FROM T1 ORDER BY I1;




--###################################################################
--+SECTOR; DATATYPE MIX
--###################################################################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 FLOAT, I3 VARCHAR(1000) )
PARTITION BY RANGE (I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN (300) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL,1.5, 'ABC');
INSERT INTO T1 VALUES (100, 2.5, 'DEF');
INSERT INTO T1 VALUES (200, 3.5, 'GHI');
INSERT INTO T1 VALUES (300, 4.5, 'JKL');

ALTER TABLE T1 ENABLE ROW MOVEMENT;
UPDATE T1 SET I1 = 999;

DELETE FROM T1;

-- should be 0
SELECT * FROM T1 ORDER BY I1;


--###################################################################
--+SECTOR; LOB 컬럼에 INSERT
--###################################################################

--##############################
--+SECTOR; BLOB, CLOB
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 BLOB, I3 CLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN ( 100 ) TABLESPACE PDT_TBS2
                        LOB (I2, I3) STORE AS ( TABLESPACE PDT_TBS3 ),
  PARTITION P2 VALUES LESS THAN ( 200 ) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN ( 300 ) TABLESPACE PDT_TBS4
                        LOB (I3) STORE AS ( TABLESPACE PDT_TBS2 ),
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 'ABC', 'ABC');
INSERT INTO T1 VALUES (100, 'ABC', 'ABC');
INSERT INTO T1 VALUES (200, 'ABC', 'ABC');
INSERT INTO T1 VALUES (300, 'ABC', 'ABC');

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be 0
SELECT COUNT(*) FROM T1;


--##################################################################
--+SECTOR; 외래키
--##################################################################

--##############################
--+SECTOR; UNIQUE KEY: INTEGER
--##############################

DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;

-- should be success
CREATE TABLE T1 ( I1 INTEGER UNIQUE, I2 VARCHAR(1000), I3 VARCHAR(10), I4 BLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE PDT_TBS2
                        LOB STORE AS ( TABLESPACE PDT_TBS3 ),
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE PDT_TBS3
                        LOB STORE AS ( TABLESPACE PDT_TBS4 ),
  PARTITION P3 VALUES LESS THAN (300) TABLESPACE PDT_TBS4
                        LOB STORE AS ( TABLESPACE PDT_TBS5 ),
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

CREATE TABLE T2 ( I1 INTEGER UNIQUE, I2 INTEGER )
PARTITION BY LIST (I1)
(
    PARTITION P1 VALUES (50, 100),
    PARTITION P2 VALUES (150, 200),
    PARTITION P3 VALUES DEFAULT
) TABLESPACE PDT_TBS;

CREATE TABLE T3 ( I1 INTEGER UNIQUE, I2 INTEGER )
TABLESPACE PDT_TBS2;

CREATE TABLE T4 ( I1 INTEGER, I2 INTEGER )
PARTITION BY HASH (I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3
) TABLESPACE PDT_TBS3;

ALTER TABLE T2 ADD CONSTRAINT T2_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T3 ADD CONSTRAINT T3_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);

ALTER TABLE T2 ADD CONSTRAINT T2_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);

ALTER TABLE T4 ADD CONSTRAINT T4_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);

-- self reference
ALTER TABLE T2 ADD CONSTRAINT T2_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);


-- should be fail
INSERT INTO T3 VALUES (100, 100);
-- should be fail
INSERT INTO T2 VALUES (100, 100);
-- should be fail
INSERT INTO T4 VALUES (100, 100);

-- should be success
INSERT INTO T1 VALUES (100, 'ABC', 'ABC', 'ABC');
-- should be success
INSERT INTO T1 VALUES (150, 'ABC', 'ABC', 'ABC');
-- should be success
INSERT INTO T1 VALUES (200, 'ABC', 'ABC', 'ABC');

-- should be fail
INSERT INTO T2 VALUES (100, 100);
-- should be fail
INSERT INTO T4 VALUES (100, 100);

-- should be success
INSERT INTO T3 VALUES (100, 100);
-- should be success
INSERT INTO T3 VALUES (150, 150);
-- should be success
INSERT INTO T3 VALUES (200, 200);

-- should be fail
INSERT INTO T4 VALUES (100, 100);

-- should be fail(self ref.)
INSERT INTO T2 VALUES (100, 150);
-- should be fail(self ref.)
INSERT INTO T2 VALUES (150, 200);
-- should be fail(self ref.)
INSERT INTO T2 VALUES (200, 100);

-- should be success
INSERT INTO T2 VALUES (100, 100);
-- should be success
INSERT INTO T2 VALUES (150, 150);
-- should be success
INSERT INTO T2 VALUES (200, 200);

-- should be success
INSERT INTO T4 VALUES (100, 100);
-- should be success
INSERT INTO T4 VALUES (150, 150);
-- should be success
INSERT INTO T4 VALUES (200, 200);

--##############################
--+SECTOR; DELETE TEST
--##############################
-- should be fail
DELETE FROM T1;
-- should be fail
DELETE FROM T2;
-- should be fail
DELETE FROM T3;

-- should be success
DELETE FROM T4;
-- should be success
DELETE FROM T2;
-- should be success
DELETE FROM T3;
-- should be success
DELETE FROM T1;

SELECT COUNT(*) FROM T1;
SELECT COUNT(*) FROM T2;
SELECT COUNT(*) FROM T3;
SELECT COUNT(*) FROM T4;


DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;


--##############################
--+SECTOR; UNIQUE KEY: VARCHAR(10)
--##############################

DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;

-- should be success
CREATE TABLE T1 ( I1 VARCHAR(10) UNIQUE, I2 VARCHAR(1000), I3 VARCHAR(10) )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN (300) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

CREATE TABLE T2 ( I1 VARCHAR(10) UNIQUE, I2 VARCHAR(10) )
PARTITION BY LIST (I1)
(
    PARTITION P1 VALUES (50, 100),
    PARTITION P2 VALUES (150, 200),
    PARTITION P3 VALUES DEFAULT
) TABLESPACE PDT_TBS;

CREATE TABLE T3 ( I1 VARCHAR(10) UNIQUE, I2 VARCHAR(10) )
TABLESPACE PDT_TBS2;

CREATE TABLE T4 ( I1 VARCHAR(10), I2 VARCHAR(10) )
PARTITION BY HASH (I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3
) TABLESPACE PDT_TBS3;

ALTER TABLE T2 ADD CONSTRAINT T2_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T3 ADD CONSTRAINT T3_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);

ALTER TABLE T2 ADD CONSTRAINT T2_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);

ALTER TABLE T4 ADD CONSTRAINT T4_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);

-- self reference
ALTER TABLE T2 ADD CONSTRAINT T2_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);


-- should be fail
INSERT INTO T3 VALUES ('100', '100');
-- should be fail
INSERT INTO T2 VALUES ('100', '100');
-- should be fail
INSERT INTO T4 VALUES ('100', '100');

-- should be success
INSERT INTO T1 VALUES ('100', 'ABC', 'ABC');
-- should be success
INSERT INTO T1 VALUES ('150', 'ABC', 'ABC');
-- should be success
INSERT INTO T1 VALUES ('200', 'ABC', 'ABC');

-- should be fail
INSERT INTO T2 VALUES ('100', '100');
-- should be fail
INSERT INTO T4 VALUES ('100', '100');

-- should be success
INSERT INTO T3 VALUES ('100', '100');
-- should be success
INSERT INTO T3 VALUES ('150', '150');
-- should be success
INSERT INTO T3 VALUES ('200', '200');

-- should be fail
INSERT INTO T4 VALUES ('100', '100');

-- should be fail(self ref.)
INSERT INTO T2 VALUES ('100', '150');
-- should be fail(self ref.)
INSERT INTO T2 VALUES ('150', '200');
-- should be fail(self ref.)
INSERT INTO T2 VALUES ('200', '100');

-- should be success
INSERT INTO T2 VALUES ('100', '100');
-- should be success
INSERT INTO T2 VALUES ('150', '150');
-- should be success
INSERT INTO T2 VALUES ('200', '200');

-- should be success
INSERT INTO T4 VALUES ('100', '100');
-- should be success
INSERT INTO T4 VALUES ('150', '150');
-- should be success
INSERT INTO T4 VALUES ('200', '200');


--##############################
--+SECTOR; DELETE TEST
--##############################
-- should be fail
DELETE FROM T1;
-- should be fail
DELETE FROM T2;
-- should be fail
DELETE FROM T3;

-- should be success
DELETE FROM T4 PARTITION(P1);
DELETE FROM T4 PARTITION(P2);
DELETE FROM T4 PARTITION(P3);
-- should be success
DELETE FROM T2 PARTITION(P1);
DELETE FROM T2 PARTITION(P2);
DELETE FROM T2 PARTITION(P3);
-- should be success
DELETE FROM T3;
-- should be success
DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

SELECT COUNT(*) FROM T1;
SELECT COUNT(*) FROM T2;
SELECT COUNT(*) FROM T3;
SELECT COUNT(*) FROM T4;


DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;


--##############################
--+SECTOR; UNIQUE KEY: VARCHAR(1000)
--##############################

DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;

-- should be success
CREATE TABLE T1 ( I1 VARCHAR(1000) UNIQUE, I2 VARCHAR(1000), I3 VARCHAR(10) )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN (300) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

CREATE TABLE T2 ( I1 VARCHAR(1000) UNIQUE, I2 VARCHAR(10) )
PARTITION BY LIST (I1)
(
    PARTITION P1 VALUES (50, 100),
    PARTITION P2 VALUES (150, 200),
    PARTITION P3 VALUES DEFAULT
) TABLESPACE PDT_TBS;

CREATE TABLE T3 ( I1 VARCHAR(1000) UNIQUE, I2 VARCHAR(10) )
TABLESPACE PDT_TBS2;

CREATE TABLE T4 ( I1 VARCHAR(1000), I2 VARCHAR(10) )
PARTITION BY HASH (I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3
) TABLESPACE PDT_TBS3;

ALTER TABLE T2 ADD CONSTRAINT T2_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T3 ADD CONSTRAINT T3_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);

ALTER TABLE T2 ADD CONSTRAINT T2_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);

ALTER TABLE T4 ADD CONSTRAINT T4_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);

-- self reference
ALTER TABLE T2 ADD CONSTRAINT T2_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);


-- should be fail
INSERT INTO T3 VALUES ('100', '100');
-- should be fail
INSERT INTO T2 VALUES ('100', '100');
-- should be fail
INSERT INTO T4 VALUES ('100', '100');

-- should be success
INSERT INTO T1 VALUES ('100', 'ABC', 'ABC');
-- should be success
INSERT INTO T1 VALUES ('150', 'ABC', 'ABC');
-- should be success
INSERT INTO T1 VALUES ('200', 'ABC', 'ABC');

-- should be fail
INSERT INTO T2 VALUES ('100', '100');
-- should be fail
INSERT INTO T4 VALUES ('100', '100');

-- should be success
INSERT INTO T3 VALUES ('100', '100');
-- should be success
INSERT INTO T3 VALUES ('150', '150');
-- should be success
INSERT INTO T3 VALUES ('200', '200');

-- should be fail
INSERT INTO T4 VALUES ('100', '100');

-- should be fail(self ref.)
INSERT INTO T2 VALUES ('100', '150');
-- should be fail(self ref.)
INSERT INTO T2 VALUES ('150', '200');
-- should be fail(self ref.)
INSERT INTO T2 VALUES ('200', '100');

-- should be success
INSERT INTO T2 VALUES ('100', '100');
-- should be success
INSERT INTO T2 VALUES ('150', '150');
-- should be success
INSERT INTO T2 VALUES ('200', '200');

-- should be success
INSERT INTO T4 VALUES ('100', '100');
-- should be success
INSERT INTO T4 VALUES ('150', '150');
-- should be success
INSERT INTO T4 VALUES ('200', '200');


--##############################
--+SECTOR; DELETE TEST
--##############################
-- should be fail
DELETE FROM T1;
-- should be fail
DELETE FROM T2;
-- should be fail
DELETE FROM T3;

-- should be success
DELETE FROM T4 PARTITION(P1);
DELETE FROM T4 PARTITION(P2);
DELETE FROM T4 PARTITION(P3);
-- should be success
DELETE FROM T2 PARTITION(P1);
DELETE FROM T2 PARTITION(P2);
DELETE FROM T2 PARTITION(P3);
-- should be success
DELETE FROM T3;
-- should be success
DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

SELECT COUNT(*) FROM T1;
SELECT COUNT(*) FROM T2;
SELECT COUNT(*) FROM T3;
SELECT COUNT(*) FROM T4;

DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;


--##############################
--+SECTOR; UNIQUE KEY: DATE
--##############################

DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;

-- should be success
CREATE TABLE T1 ( I1 DATE UNIQUE, I2 VARCHAR(1000), I3 VARCHAR(10) )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (TO_DATE('2007-05-05', 'YYYY-MM-DD')) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN (TO_DATE('2007-06-05', 'YYYY-MM-DD')) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN (TO_DATE('2007-07-05', 'YYYY-MM-DD')) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

CREATE TABLE T2 ( I1 DATE UNIQUE, I2 DATE )
PARTITION BY LIST (I1)
(
    PARTITION P1 VALUES (TO_DATE('2007-05-01', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') ),
    PARTITION P2 VALUES (TO_DATE('2007-06-01', 'YYYY-MM-DD'), TO_DATE('2007-06-05', 'YYYY-MM-DD') ),
    PARTITION P3 VALUES DEFAULT
) TABLESPACE PDT_TBS;

CREATE TABLE T3 ( I1 DATE UNIQUE, I2 DATE )
TABLESPACE PDT_TBS2;

CREATE TABLE T4 ( I1 DATE, I2 DATE )
PARTITION BY HASH (I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3
) TABLESPACE PDT_TBS3;

ALTER TABLE T2 ADD CONSTRAINT T2_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T3 ADD CONSTRAINT T3_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);

ALTER TABLE T2 ADD CONSTRAINT T2_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);

ALTER TABLE T4 ADD CONSTRAINT T4_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);

-- self reference
ALTER TABLE T2 ADD CONSTRAINT T2_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);


-- should be fail
INSERT INTO T3 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );
-- should be fail
INSERT INTO T2 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );
-- should be fail
INSERT INTO T4 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );

-- should be success
INSERT INTO T1 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), '123', '123');
-- should be success
INSERT INTO T1 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD'), '123', '123');
-- should be success
INSERT INTO T1 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD'), '123', '123');

-- should be fail
INSERT INTO T2 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );
-- should be fail
INSERT INTO T4 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );

-- should be success
INSERT INTO T3 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );
-- should be success
INSERT INTO T3 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD'), TO_DATE('2007-06-05', 'YYYY-MM-DD') );
-- should be success
INSERT INTO T3 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD'), TO_DATE('2007-07-05', 'YYYY-MM-DD') );

-- should be fail
INSERT INTO T4 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );

-- should be fail(self ref.)
INSERT INTO T2 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-06-05', 'YYYY-MM-DD') );
-- should be fail(self ref.)
INSERT INTO T2 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD'), TO_DATE('2007-07-05', 'YYYY-MM-DD') );
-- should be fail(self ref.)
INSERT INTO T2 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );

-- should be success
INSERT INTO T2 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );
-- should be success
INSERT INTO T2 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD'), TO_DATE('2007-06-05', 'YYYY-MM-DD') );
-- should be success
INSERT INTO T2 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD'), TO_DATE('2007-07-05', 'YYYY-MM-DD') );

-- should be success
INSERT INTO T4 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD'), TO_DATE('2007-05-05', 'YYYY-MM-DD') );
-- should be success
INSERT INTO T4 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD'), TO_DATE('2007-06-05', 'YYYY-MM-DD') );
-- should be success
INSERT INTO T4 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD'), TO_DATE('2007-07-05', 'YYYY-MM-DD') );


--##############################
--+SECTOR; DELETE TEST
--##############################
-- should be fail
DELETE FROM T1;
-- should be fail
DELETE FROM T2;
-- should be fail
DELETE FROM T3;

-- should be success
DELETE FROM T4 PARTITION(P1);
DELETE FROM T4 PARTITION(P2);
DELETE FROM T4 PARTITION(P3);
-- should be success
DELETE FROM T2 PARTITION(P1);
DELETE FROM T2 PARTITION(P2);
DELETE FROM T2 PARTITION(P3);
-- should be success
DELETE FROM T3;
-- should be success
DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

SELECT COUNT(*) FROM T1;
SELECT COUNT(*) FROM T2;
SELECT COUNT(*) FROM T3;
SELECT COUNT(*) FROM T4;


DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;


--##############################
--+SECTOR; UNIQUE KEY: NUMERIC(10,5)
--##############################

DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;

-- should be success
CREATE TABLE T1 ( I1 NUMERIC(10,5) UNIQUE, I2 VARCHAR(1000), I3 VARCHAR(10) )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100.505) TABLESPACE PDT_TBS2,
  PARTITION P2 VALUES LESS THAN (200.505) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES LESS THAN (300.505) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

CREATE TABLE T2 ( I1 NUMERIC(10,5) UNIQUE, I2 NUMERIC(10,5) )
PARTITION BY LIST (I1)
(
    PARTITION P1 VALUES (50, 100),
    PARTITION P2 VALUES (150, 200),
    PARTITION P3 VALUES DEFAULT
) TABLESPACE PDT_TBS;

CREATE TABLE T3 ( I1 NUMERIC(10,5) UNIQUE, I2 NUMERIC(10,5) )
TABLESPACE PDT_TBS2;

CREATE TABLE T4 ( I1 NUMERIC(10,5), I2 NUMERIC(10,5) )
PARTITION BY HASH (I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3
) TABLESPACE PDT_TBS3;

ALTER TABLE T2 ADD CONSTRAINT T2_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T3 ADD CONSTRAINT T3_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T1_FK FOREIGN KEY(I2) REFERENCES T1(I1);

ALTER TABLE T2 ADD CONSTRAINT T2_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);
ALTER TABLE T4 ADD CONSTRAINT T4_T3_FK FOREIGN KEY(I2) REFERENCES T3(I1);

ALTER TABLE T4 ADD CONSTRAINT T4_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);

-- self reference
ALTER TABLE T2 ADD CONSTRAINT T2_T2_FK FOREIGN KEY(I2) REFERENCES T2(I1);


-- should be fail
INSERT INTO T3 VALUES (100.505, 100.505);
-- should be fail
INSERT INTO T2 VALUES (100.505, 100.505);
-- should be fail
INSERT INTO T4 VALUES (100.505, 100.505);

-- should be success
INSERT INTO T1 VALUES (100.505, 'ABC', 'ABC');
-- should be success
INSERT INTO T1 VALUES (150.505, 'ABC', 'ABC');
-- should be success
INSERT INTO T1 VALUES (200.505, 'ABC', 'ABC');

-- should be fail
INSERT INTO T2 VALUES (100.505, 100.505);
-- should be fail
INSERT INTO T4 VALUES (100.505, 100.505);

-- should be success
INSERT INTO T3 VALUES (100.505, 100.505);
-- should be success
INSERT INTO T3 VALUES (150.505, 150.505);
-- should be success
INSERT INTO T3 VALUES (200.505, 200.505);

-- should be fail
INSERT INTO T4 VALUES (100.505, 100.505);

-- should be fail(self ref.)
INSERT INTO T2 VALUES (100.505, 150.505);
-- should be fail(self ref.)
INSERT INTO T2 VALUES (150.505, 200.505);
-- should be fail(self ref.)
INSERT INTO T2 VALUES (200.505, 100.505);

-- should be success
INSERT INTO T2 VALUES (100.505, 100.505);
-- should be success
INSERT INTO T2 VALUES (150.505, 150.505);
-- should be success
INSERT INTO T2 VALUES (200.505, 200.505);

-- should be success
INSERT INTO T4 VALUES (100.505, 100.505);
-- should be success
INSERT INTO T4 VALUES (150.505, 150.505);
-- should be success
INSERT INTO T4 VALUES (200.505, 200.505);


--##############################
--+SECTOR; DELETE TEST
--##############################
-- should be fail
DELETE FROM T1;
-- should be fail
DELETE FROM T2;
-- should be fail
DELETE FROM T3;

-- should be success
DELETE FROM T4 PARTITION(P1);
DELETE FROM T4 PARTITION(P2);
DELETE FROM T4 PARTITION(P3);
-- should be success
DELETE FROM T2 PARTITION(P1);
DELETE FROM T2 PARTITION(P2);
DELETE FROM T2 PARTITION(P3);
-- should be success
DELETE FROM T3;
-- should be success
DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

SELECT COUNT(*) FROM T1;
SELECT COUNT(*) FROM T2;
SELECT COUNT(*) FROM T3;
SELECT COUNT(*) FROM T4;

DROP TABLE T4 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T1 CASCADE;



--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T4 CASCADE;
--+SKIP END;
