--###########################################################################
--# ported from qp4/Project3/PROJ-1624-GlobalIndex/PROJ-1624-QC/PDT/Design/DELETE/HashPartTable.sql
--#
--# Body below is byte-identical to the original. The one line this port
--# adds is the premise: the original measures these statements on the
--# $GIT_ hidden-table implementation, this file measures the same
--# statements on the native global index (F07 -- see include/pinNative.sql).
--###########################################################################
--+LOAD_SQL ../../../include/pinNative.sql;

--###################################################################
--# DELETE TEST
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
DROP TABLE T4;
--+SKIP END;



--###################################################################
--+SECTOR; 각 데이터 타입별 DELETE
--###################################################################

--##############################
--+SECTOR; INTEGER, BIGINT, SMALLINT
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER UNIQUE, I2 BIGINT , I3 SMALLINT )
PARTITION BY HASH (I1)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 100, 100);
INSERT INTO T1 VALUES (100, 110, 110);
INSERT INTO T1 VALUES (200, 120, 120);
INSERT INTO T1 VALUES (300, 130, 130);

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be {}
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; BIT(10), BIT(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 BIT(10), I2 BIT(1000) )
PARTITION BY HASH (I1, I2)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, BIT'100');
INSERT INTO T1 VALUES (BIT'100', BIT'100');
INSERT INTO T1 VALUES (BIT'110', BIT'100');
INSERT INTO T1 VALUES (BIT'111', BIT'100');

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be {}
SELECT * FROM T1 ORDER BY I1;


--##############################
--+SECTOR; BLOB, CLOB
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 BLOB, I3 CLOB )
PARTITION BY HASH (I1)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 'ABC', 'ABC');
INSERT INTO T1 VALUES (100, 'ABC', 'ABC');
INSERT INTO T1 VALUES (200, 'ABC', 'ABC');
INSERT INTO T1 VALUES (300, 'ABC', 'ABC');

DELETE FROM T1 PARTITION(P1) WHERE I1 < 100;
DELETE FROM T1 PARTITION(P2) WHERE I1 < 200;
DELETE FROM T1 PARTITION(P3) WHERE I1 < 300;
DELETE FROM T1 PARTITION(P4);

-- should be 3
SELECT COUNT(*) FROM T1;


--##############################
--+SECTOR; BYTE(1000), NIBBLE(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 BYTE(1000), I3 NIBBLE(254) )
PARTITION BY HASH (I1)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 'ABC', 'ABC');
INSERT INTO T1 VALUES (100, 'ABC', 'ABC');
INSERT INTO T1 VALUES (200, 'ABC', 'ABC');
INSERT INTO T1 VALUES (300, 'ABC', 'ABC');

DELETE FROM T1 WHERE I1 > 0;

-- should be 1
SELECT COUNT(*) FROM T1;


--##############################
--+SECTOR; CHAR(10), CHAR(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 CHAR(10), I2 CHAR(1000) )
PARTITION BY HASH (I1)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 'ABC');
INSERT INTO T1 VALUES ('100', 'ABC');
INSERT INTO T1 VALUES ('200', 'ABC');
INSERT INTO T1 VALUES ('300', 'ABC');

DELETE FROM T1 WHERE I1 > '000';

-- should be 1
SELECT COUNT(*) FROM T1;


--##############################
--+SECTOR; DATE
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 DATE )
PARTITION BY HASH (I1)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD') );
INSERT INTO T1 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD') );
INSERT INTO T1 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD') );

DELETE FROM T1 WHERE I1 > TO_DATE('2006-12-25', 'YYYY-MM-DD');

-- should be 1
SELECT COUNT(*) FROM T1;


--##############################
--+SECTOR; DOUBLE, FLOAT, REAL
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 DOUBLE, I2 FLOAT, I3 REAL )
PARTITION BY HASH (I1, I2, I3)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 100.5, 100.5);
INSERT INTO T1 VALUES (100.5, 100.5, 100.5);
INSERT INTO T1 VALUES (200.5, 100.5, 100.5);
INSERT INTO T1 VALUES (300.5, 100.5, 100.5);

DELETE FROM T1 WHERE I1 = I1;

-- should be 1
SELECT COUNT(*) FROM T1;


--##############################
--+SECTOR; NUMERIC
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 NUMERIC(20, 5) )
PARTITION BY HASH (I1)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (100.505);
INSERT INTO T1 VALUES (200.505);
INSERT INTO T1 VALUES (300.505);

-- should be {100.505, 200.505, 300.505, NULL}
SELECT * FROM T1 ORDER BY I1;

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be 0
SELECT COUNT(*) FROM T1;


--##############################
--+SECTOR; VARBIT(10), VARBIT(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 VARBIT(10), I2 VARBIT(1000) )
PARTITION BY HASH (I1, I2)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, VARBIT'100');
INSERT INTO T1 VALUES (VARBIT'100', VARBIT'100');
INSERT INTO T1 VALUES (VARBIT'110', VARBIT'100');
INSERT INTO T1 VALUES (VARBIT'111', VARBIT'100');

-- should be {'100', '110', '111', NULL}
SELECT * FROM T1 ORDER BY I1;

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be 0
SELECT COUNT(*) FROM T1;


--##############################
--+SECTOR; VARCHAR(10), VARCHAR(1000)
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 VARCHAR(10), I2 VARCHAR(1000) )
PARTITION BY HASH (I1, I2)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, '100');
INSERT INTO T1 VALUES ('100', '100');
INSERT INTO T1 VALUES ('200', '100');
INSERT INTO T1 VALUES ('300', '100');

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be 0
SELECT COUNT(*) FROM T1;



--###################################################################
--+SECTOR; DATATYPE MIX
--###################################################################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 FLOAT, I3 VARCHAR(1000) )
PARTITION BY HASH (I1, I2, I3)
( PARTITION P1 TABLESPACE PDT_TBS2,
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL,1.5, 'ABC');
INSERT INTO T1 VALUES (100, 2.5, 'DEF');
INSERT INTO T1 VALUES (200, 3.5, 'GHI');
INSERT INTO T1 VALUES (300, 4.5, 'JKL');

ALTER TABLE T1 ENABLE ROW MOVEMENT;
UPDATE T1 SET I1 = 999;

DELETE FROM T1;

-- should be 0
SELECT COUNT(*) FROM T1;


--###################################################################
--+SECTOR; LOB 컬럼에 INSERT
--###################################################################

--##############################
--+SECTOR; BLOB, CLOB
--##############################
DROP TABLE T1;

-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 BLOB, I3 CLOB )
PARTITION BY HASH (I1)
( PARTITION P1 TABLESPACE PDT_TBS2
                        LOB (I2, I3) STORE AS ( TABLESPACE PDT_TBS3 ),
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4
                        LOB (I3) STORE AS ( TABLESPACE PDT_TBS2 ),
  PARTITION P4 TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL, 'ABC', 'ABC');
INSERT INTO T1 VALUES (100, 'ABC', 'ABC');
INSERT INTO T1 VALUES (200, 'ABC', 'ABC');
INSERT INTO T1 VALUES (300, 'ABC', 'ABC');

DELETE FROM T1 PARTITION(P1);
DELETE FROM T1 PARTITION(P2);
DELETE FROM T1 PARTITION(P3);
DELETE FROM T1 PARTITION(P4);

-- should be 0
SELECT COUNT(*) FROM T1;



--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1 CASCADE;
DROP TABLE T2 CASCADE;
DROP TABLE T3 CASCADE;
DROP TABLE T4 CASCADE;
--+SKIP END;
