--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
DROP TABLE T4;
--+SKIP END;

CREATE TABLE T1 ( I1 VARCHAR(3) VARIABLE, I2 VARCHAR(3) FIXED ) PARTITION BY RANGE(I1) ( PARTITION P1 VALUES DEFAULT TABLESPACE PDT_TBS ) TABLESPACE SYS_TBS_DISK_DATA;
CREATE TABLE T2 ( I1 VARCHAR(3) VARIABLE, I2 VARCHAR(3) FIXED ) PARTITION BY RANGE(I1) ( PARTITION P1 VALUES DEFAULT TABLESPACE PDT_TBS ) TABLESPACE SYS_TBS_DISK_DATA;
CREATE TABLE T3 ( I1 VARCHAR(3) VARIABLE, I2 VARCHAR(3) FIXED ) PARTITION BY RANGE(I1) ( PARTITION P1 VALUES DEFAULT TABLESPACE PDT_TBS ) TABLESPACE SYS_TBS_DISK_DATA;
CREATE TABLE T4 ( I1 VARCHAR(3) VARIABLE, I2 VARCHAR(3) FIXED ) PARTITION BY RANGE(I1) ( PARTITION P1 VALUES DEFAULT TABLESPACE PDT_TBS ) TABLESPACE SYS_TBS_DISK_DATA;


CREATE INDEX T1_I1 ON T1(I1);
CREATE INDEX T1_I2 ON T1(I2);

INSERT INTO T1 VALUES (1, 1);
INSERT INTO T1 VALUES (2, 2);
INSERT INTO T1 VALUES (0, 3);
INSERT INTO T1 VALUES (2, 4);
INSERT INTO T1 VALUES (3, 1);
INSERT INTO T1 VALUES (3, 1);
INSERT INTO T1 VALUES (4, 2);
INSERT INTO T1 VALUES (2, NULL);

INSERT INTO T2 VALUES (1, 1);
INSERT INTO T2 VALUES (2, 2);
INSERT INTO T2 VALUES (1, NULL);
INSERT INTO T2 VALUES (2, 4);
INSERT INTO T2 VALUES (3, 2);
INSERT INTO T2 VALUES (4, 8);
INSERT INTO T2 VALUES (2, 2);
INSERT INTO T2 VALUES (5, 4);

INSERT INTO T3 VALUES (1, 1);
INSERT INTO T3 VALUES (0, 3);
INSERT INTO T3 VALUES (3, 1);
INSERT INTO T3 VALUES (4, 1);
INSERT INTO T3 VALUES (3, NULL);

INSERT INTO T4 VALUES (1, NULL);
INSERT INTO T4 VALUES (2, 1);
INSERT INTO T4 VALUES (3, 2);
INSERT INTO T4 VALUES (2, 2);
INSERT INTO T4 VALUES (5, 4);

ALTER SESSION SET EXPLAIN PLAN=ON;
ALTER SESSION SET TRCLOG_DETAIL_PREDICATE=1;

SELECT * FROM T1, T2, T3 
              WHERE T1.I1 = T2.I1 AND T1.I1 = T3.I1 
              AND T1.I1 > '0' AND T1.I2 > '0';


SELECT * FROM T1, T2, T3, T4 
              WHERE T1.I1 = T2.I1 AND T1.I1 = T3.I1 
              AND T1.I1 > '0' AND T1.I2 > '0';


SELECT * FROM T1, T2, T3 
              WHERE T1.I1 = T3.I2 AND T2.I1 = T3.I1 
              AND T3.I2 > '0' AND T3.I1 > '0';

SELECT * FROM T1, T2, T3, T4
              WHERE T1.I1 = T3.I2 AND T2.I1 = T3.I1 AND T1.I2 = T4.I2
              AND T3.I2 > '0' AND T3.I1 > '0';

ALTER SESSION SET EXPLAIN PLAN=OFF;
ALTER SESSION SET TRCLOG_DETAIL_PREDICATE=0;

DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
DROP TABLE T4;

