--+DECLARE SERVER REPL_SERVER1 DB1;
--+DECLARE SERVER REPL_SERVER2 DB2;

--+DECLARE CLIENT DEFAULT P1 (SERVER=DB1);
--+DECLARE CLIENT DEFAULT P2 (SERVER=DB2);

--+PROCESS P1;
alter system set REPLICATION_TIMESTAMP_RESOLUTION = 1;

    --+PROCESS P2;
    alter system set REPLICATION_TIMESTAMP_RESOLUTION = 1;

--+PWAIT;
