[DEFAULT]
ALTIBASE_NLS_USE=KO16KSC5601
ALTIBASE_NLS_NCHAR_LITERAL_REPLACE=0

[REPL_CLIENT1]
ALTIBASE_SID = altibase1
ALTIBASE_PORT_NO = %PORT_NO1
ALTIBASE_CHECK_POINT_INTERVAL_IN_LOG=3
ALTIBASE_CHECK_POINT_INTERVAL_IN_SEC=3600
ALTIBASE_AUTO_REMOVE_ARCHIVE_LOG=1
ALTIBASE_REPLICATION_PORT_NO = %REPLICATION_PORT_NO1
ALTIBASE_REPLICATION_CONNECT_TIMEOUT = 10
ALTIBASE_REPLICATION_MAX_LOGFILE=0
ALTIBASE_REPLICATION_LOCK_TIMEOUT = 30 
ALTIBASE_AUTO_COMMIT=1
ALTIBASE_ISOLATION_LEVEL=0
ALTIBASE_LOG_FILE_SIZE=1M
ALTIBASE_DB_FILE_SIZE=10M
ALTIBASE_HOME=$ATC_HOME/TC/Server/repl4/db1
ALTIBASE___SHOW_ERROR_STACK = 0
ALTIBASE_SOURCE_INFO  = 0
ALTIBASE_REPLICATION_ENABLE_ADD_COLUMN = 1 
ALTIBASE_MIN_LOG_RECORD_SIZE_FOR_COMPRESS = 1
ALTIBASE_PREPARE_LOG_FILE_COUNT = 2
ALTIBASE_REPLICATION_LOG_BUFFER_SIZE = 1
ALTIBASE_REPLICATION_PREFETCH_LOGFILE_COUNT=3
ALTIBASE_TRX_UPDATE_MAX_LOGSIZE=100000000

[REPL_CLIENT2]
ALTIBASE_SID = altibase2
ALTIBASE_PORT_NO = %PORT_NO2
ALTIBASE_CHECK_POINT_INTERVAL_IN_LOG=3
ALTIBASE_CHECK_POINT_INTERVAL_IN_SEC=3600
ALTIBASE_AUTO_REMOVE_ARCHIVE_LOG=1
ALTIBASE_REPLICATION_PORT_NO = %REPLICATION_PORT_NO2
ALTIBASE_REPLICATION_CONNECT_TIMEOUT = 10
ALTIBASE_REPLICATION_MAX_LOGFILE=0 
ALTIBASE_REPLICATION_LOCK_TIMEOUT = 30 
ALTIBASE_AUTO_COMMIT=1
ALTIBASE_ISOLATION_LEVEL=0
ALTIBASE_LOG_FILE_SIZE=1M
ALTIBASE_DB_FILE_SIZE=10M
ALTIBASE_HOME=$ATC_HOME/TC/Server/repl4/db2
ALTIBASE___SHOW_ERROR_STACK = 0
ALTIBASE_SOURCE_INFO  = 0
ALTIBASE_REPLICATION_ENABLE_ADD_COLUMN = 1 
ALTIBASE_MIN_LOG_RECORD_SIZE_FOR_COMPRESS = 1
ALTIBASE_PREPARE_LOG_FILE_COUNT = 2
ALTIBASE_REPLICATION_LOG_BUFFER_SIZE = 1
ALTIBASE_REPLICATION_PREFETCH_LOGFILE_COUNT=3
ALTIBASE_TRX_UPDATE_MAX_LOGSIZE=100000000

[REPL_CLIENT3]
ALTIBASE_SID = altibase3
ALTIBASE_PORT_NO = %PORT_NO3
ALTIBASE_CHECK_POINT_INTERVAL_IN_LOG=3
ALTIBASE_CHECK_POINT_INTERVAL_IN_SEC=3600
ALTIBASE_AUTO_REMOVE_ARCHIVE_LOG=1
ALTIBASE_REPLICATION_PORT_NO = %REPLICATION_PORT_NO3
ALTIBASE_REPLICATION_CONNECT_TIMEOUT = 10
ALTIBASE_REPLICATION_MAX_LOGFILE=0 
ALTIBASE_REPLICATION_LOCK_TIMEOUT = 30 
ALTIBASE_AUTO_COMMIT=1
ALTIBASE_ISOLATION_LEVEL=0
ALTIBASE_LOG_FILE_SIZE=1M
ALTIBASE_DB_FILE_SIZE=10M
ALTIBASE_HOME=$ATC_HOME/TC/Server/repl4/db3
ALTIBASE___SHOW_ERROR_STACK = 0
ALTIBASE_SOURCE_INFO  = 0
ALTIBASE_MIN_LOG_RECORD_SIZE_FOR_COMPRESS = 1
ALTIBASE_PREPARE_LOG_FILE_COUNT = 2
ALTIBASE_REPLICATION_LOG_BUFFER_SIZE = 1
ALTIBASE_REPLICATION_PREFETCH_LOGFILE_COUNT=3
ALTIBASE_TRX_UPDATE_MAX_LOGSIZE=100000000
