[DDLServer]
ATAF_SQL_PREFIX=STARTUP,SHUTDOWN,CONNECT,DISCONNECT,AUDIT,NOAUDIT,CREATE,ALTER,DROP,COMMENT,GRANT,REVOKE,RENAME TABLE,TRUNCATE TABLE,SET TRANSACTION,AUTOCOMMIT ON,AUTOCOMMIT OFF,ROLLBACK WORK,COMMIT WORK,CREATE ROLE
ALTIBASE_HOME=$ATC_HOME/TC/Common/db1
ALTIBASE_PORT_NO=%PORT_NO1
ALTIBASE_CLUSTER_PORT_NO=%CLUSTER_PORT_NO1
ALTIBASE_CLUSTER_DATABASE=1
ALTIBASE_SID=altibase1
ALTIBASE_SPFILE=?/conf/altibase.sproperties

[NonDDLServer]
ATAF_SQL_PREFIX=STARTUP,SHUTDOWN,CONNECT,DISCONNECT,AUDIT,NOAUDIT,DROP USER,CREATE TABLESPACE,CREATE DISK,CREATE MEMORY,CREATE VOLATILE,ALTER TABLESPACE,DROP TABLESPACE,CREATE OR REPLACE PROCEDURE,CREATE PROCEDURE,ALTER PROCEDURE,DROP PROCEDURE,CREATE OR REPLACE FUNCTION,CREATE FUNCTION,ALTER FUNCTION,DROP FUNCTION,CREATE OR REPLACE PACKAGE,CREATE PACKAGE,ALTER PACKAGE,DROP PACKAGE,CREATE OR REPLACE TYPESET,CREATE TYPESET,DROP TYPESET,ALTER SYSTEM,ALTER SESSION,INSERT,DELETE,UPDATE,MOVE,MERGE,ENQUEUE,DEQUEUE,LOCK TABLE,SELECT,(,SAVEPOINT,ROLLBACK,COMMIT,DESC,EXEC,EXECUTE,AUTOCOMMIT,SET,SPOOL,START,@,!,SAVE,LOAD,SHOW,VAR,VARIABLE,PRINT,PREPARE,SET LINESIZE, DROP ROLE
ALTIBASE_HOME=$ATC_HOME/TC/Common/db2
ALTIBASE_PORT_NO=%PORT_NO2
ALTIBASE_CLUSTER_PORT_NO=%CLUSTER_PORT_NO2
ALTIBASE_CLUSTER_DATABASE=1
ALTIBASE_SID=altibase2
ALTIBASE_SPFILE=?/conf/altibase.sproperties

[ATAF_CLUSTER_TEST_1]
ATAF_SQL_PREFIX=STARTUP,SHUTDOWN,CONNECT,DISCONNECT,AUDIT,NOAUDIT,CREATE,ALTER,DROP,COMMENT,GRANT,REVOKE,RENAME TABLE,TRUNCATE TABLE
ALTIBASE_HOME=$ATC_HOME/TC/ATAF/Function/PROJ-2384/db1
ALTIBASE_PORT_NO=%PORT_NO1
ALTIBASE_CLUSTER_PORT_NO=%CLUSTER_PORT_NO1
ALTIBASE_CLUSTER_DATABASE=1
ALTIBASE_SID=altibase0
ALTIBASE_SPFILE=?/conf/altibase.sproperties
 
[ATAF_CLUSTER_TEST_2]
ATAF_SQL_PREFIX=STARTUP,SHUTDOWN,CONNECT,DISCONNECT,AUDIT,NOAUDIT,DROP USER,GRANT,REVOKE,CREATE TABLESPACE,CREATE DISK TABLESPACE,CREATE MEMORY TABLESPACE,CREATE VOLATILE TABLESPACE,CREATE TEMPORARY TABLESPACE,ALTER TABLESPACE,DROP TABLESPACE,CREATE OR REPLACE PROCEDURE,CREATE PROCEDURE,ALTER PROCEDURE,DROP PROCEDURE,CREATE OR REPLACE FUNCTION,CREATE FUNCTION,ALTER FUNCTION,DROP FUNCTION,CREATE OR REPLACE PACKAGE,CREATE PACKAGE,ALTER PACKAGE,DROP PACKAGE,CREATE OR REPLACE TYPESET,CREATE TYPESET,DROP TYPESET,ALTER SYSTEM,ALTER SESSION,INSERT,DELETE,UPDATE,MOVE,MERGE,ENQUEUE,DEQUEUE,LOCK TABLE,SELECT,(,SAVEPOINT,ROLLBACK,COMMIT,DESC,EXEC,EXECUTE,AUTOCOMMIT,SET,SPOOL,START,@,!,SAVE,LOAD,SHOW,VAR,VARIABLE,PRINT,PREPARE,CREATE MEMORY DATA
ALTIBASE_HOME=$ATC_HOME/TC/ATAF/Function/PROJ-2384/db2
ALTIBASE_PORT_NO=%PORT_NO2
ALTIBASE_CLUSTER_PORT_NO=%CLUSTER_PORT_NO2
ALTIBASE_CLUSTER_DATABASE=1
ALTIBASE_SID=altibase1
ALTIBASE_SPFILE=?/conf/altibase.sproperties

