--+SKIP BEGIN;
DROP TABLE RANGE_TAB;
DROP TABLE HASH_TAB;

CREATE TABLE RANGE_TAB
(
    I1 INTEGER,
    I2 VARCHAR(10) VARIABLE
)
PARTITION BY RANGE( I1 )
(
    PARTITION P1 VALUES LESS THAN (10),
    PARTITION P2 VALUES LESS THAN (20),
    PARTITION P3 VALUES LESS THAN (30),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE SYS_TBS_DISK_DATA;

ALTER TABLE RANGE_TAB ENABLE ROW MOVEMENT;

CREATE INDEX IDX1 ON RANGE_TAB(I1);

INSERT INTO RANGE_TAB VALUES(5 , 'ABC');
INSERT INTO RANGE_TAB VALUES(15 , 'ABC');
INSERT INTO RANGE_TAB VALUES(25 , 'ABC');
INSERT INTO RANGE_TAB VALUES(35 , 'ABC');

CREATE TABLE HASH_TAB
(
    I1 INTEGER,
    I2 VARCHAR(10) VARIABLE
)
PARTITION BY HASH( I1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE SYS_TBS_DISK_DATA;

ALTER TABLE HASH_TAB ENABLE ROW MOVEMENT;

CREATE INDEX IDX2 ON HASH_TAB(I1);

INSERT INTO HASH_TAB VALUES(1 , 'ABC');
INSERT INTO HASH_TAB VALUES(2 , 'ABC');
INSERT INTO HASH_TAB VALUES(3 , 'ABC');
INSERT INTO HASH_TAB VALUES(4 , 'ABC');
--+SKIP END;
