--###########################################################################
--# ported from qp4/Project3/PROJ-1624-GlobalIndex/PROJ-1624-QC/PDT/Design/ALTER_TABLE/ROW_MOVEMENT/HashPartTable_Date.sql
--#
--# Body below is byte-identical to the original. The one line this port
--# adds is the premise: the original measures these statements on the
--# $GIT_ hidden-table implementation, this file measures the same
--# statements on the native global index (F07 -- see include/pinNative.sql).
--###########################################################################
--+LOAD_SQL ../../../../include/pinNative.sql;

--###################################################################
--# ALTER TABLE ... ENABLE/DISABLE ROWMOVEMENT(PartKey: DATE)
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

--+APPEND_LST Schema_Hash_Date.sql;
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

--###################################################################
--+ SECTOR; BASIC TEST
--###################################################################
--##############################
--+SECTOR; 문법 체크
--##############################
DROP TABLE TEST;

-- should be fail
CREATE TABLE TEST( I1 DATE, I2 INTEGER )
PARTITION BY HASH(I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS ENABLE ROW MOVEMENT;

-- should be fail
CREATE TABLE TEST( I1 DATE, I2 INTEGER )
PARTITION BY HASH(I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3 ENABLE ROW MOVEMENT,
    PARTITION P4
) TABLESPACE PDT_TBS;

-- should be success
CREATE TABLE TEST( I1 DATE, I2 INTEGER )
PARTITION BY HASH(I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) ENABLE ROW MOVEMENT TABLESPACE PDT_TBS;


--##############################
--+SECTOR; 파티션의 개수
--##############################
--#############
--# 4개
--#############
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + 30;

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = I1 + 30;

SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);

--#############
--# 1개
--#############
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

ALTER TABLE T1 
COALESCE PARTITION;

ALTER TABLE T1 
COALESCE PARTITION;

ALTER TABLE T1 
COALESCE PARTITION;

UPDATE T1 SET I1 = I1 + 30;

-- result: 13
SELECT COUNT(*) FROM T1;


ALTER TABLE T2
ENABLE ROW MOVEMENT;

ALTER TABLE T2 
COALESCE PARTITION;

ALTER TABLE T2 
COALESCE PARTITION;

ALTER TABLE T2 
COALESCE PARTITION;

UPDATE T2 SET I1 = I1 + 30;

-- result: 13
SELECT COUNT(*) FROM T2;


--##############################
--+SECTOR; LOB 컬럼이 있는 경우
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 DATE, I2 BLOB, I3 CLOB )
PARTITION BY HASH(I1) 
( PARTITION P1 TABLESPACE PDT_TBS 
                        LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ), 
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

CREATE INDEX IDX_LOB ON T1(I1);

INSERT INTO T1 VALUES (NULL, 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-05-01', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-05-15', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-05-30', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-06-01', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-06-15', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-06-30', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-07-01', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-07-15', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-07-30', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-08-01', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-08-15', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-08-30', 'YYYY-MM-DD'), 'ABC', 'ABC');


ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + 30;

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);



--##################################################################
--+SECTOR; UPDATE 조건에 따른 검사
--##################################################################
--##############################
--+SECTOR; 여러 파티션으로 분산
--##############################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + 30;

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = I1 + 30;

SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);


--##############################
--+SECTOR; 모두 같은 파티션으로 이동
--##############################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = TO_DATE('2007-05-05', 'YYYY-MM-DD');
SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

UPDATE T1 SET I1 = TO_DATE('2007-05-06', 'YYYY-MM-DD');
SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

UPDATE T1 SET I1 = TO_DATE('2007-05-07', 'YYYY-MM-DD');
SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

UPDATE T1 SET I1 = TO_DATE('2007-05-08', 'YYYY-MM-DD');
SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = TO_DATE('2007-05-05', 'YYYY-MM-DD');
SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);

UPDATE T2 SET I1 = TO_DATE('2007-05-06', 'YYYY-MM-DD');
SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);

UPDATE T2 SET I1 = TO_DATE('2007-05-07', 'YYYY-MM-DD');
SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);

UPDATE T2 SET I1 = TO_DATE('2007-05-08', 'YYYY-MM-DD');
SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);


--##############################
--+SECTOR; 현재 파티션에 그대로 있는 경우
--##############################
--+SYSTEM is -silent -f Schema_Hash_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + 1;

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = I1 + 1;

SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);



--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;
