--###################################################################
--# 인덱스 파티션을 직접 지정하는 경우
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

--+LOAD_SQL Schema_Index_Partition.sql;

--###################################################################
--+ SECTOR; 문법 체크
--###################################################################
-- should be fail
ALTER TABLE T1 
MERGE PARTITIONS P1, P2 INTO
PARTITION P5 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4 )
    LOB STORE AS ( TABLESPACE PDT_TBS2 );
    
-- should be fail
ALTER TABLE T1 
MERGE PARTITIONS P1, P2 INTO
PARTITION P6 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4 
                LOB STORE AS ( TABLESPACE PDT_TBS2 ) );


--##############################
--+SECTOR; 파티션드 테이블인지 체크
--##############################
DROP TABLE TEST;
CREATE TABLE TEST( I1 INTEGER, I2 INTEGER );

-- should be fail
ALTER TABLE TEST 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS2
        INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4 );

DROP TABLE TEST;


--##############################
--+SECTOR; 지정한 인덱스가 있는지 체크
--##############################
--+LOAD_SQL Schema_Index_Partition.sql;

-- should be fail
ALTER TABLE T1 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS2
        INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4 );

-- should be fail
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS2
        INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
                IDX4 PARTITION P5_IDX2 TABLESPACE PDT_TBS4 );

-- should be fail
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX4 PARTITION P6_IDX4 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4 );

-- should be fail
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P6_IDX3 TABLESPACE PDT_TBS4,
                IDX4 PARTITION P6_IDX4 TABLESPACE PDT_TBS4 );


--##############################
--+SECTOR; 인덱스 파티션 이름 중복 체크
--##############################
--+LOAD_SQL Schema_Index_Partition.sql;

-- 파티션드 인덱스 이름 중복
-- should be fail
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX1 PARTITION P6_IDX3 TABLESPACE PDT_TBS4 );

-- 인덱스 파티션 이름 중복
-- should be fail
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P6_IDX1 TABLESPACE PDT_TBS4 );

-- 이미 있는 인덱스 파티션 이름
-- should be fail
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P1_IDX3 TABLESPACE PDT_TBS4 );

-- 이미 있는 인덱스 파티션 이름
-- should be fail
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P2_IDX3 TABLESPACE PDT_TBS4 );

-- 이미 있는 인덱스 파티션 이름
-- should be fail
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P7
        INDEX ( IDX1 PARTITION P7_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P7_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P4_IDX3 TABLESPACE PDT_TBS4 );



--##################################################################
--+SECTOR; 인덱스 파티션 지정
--##################################################################
--+LOAD_SQL Schema_Index_Partition.sql;

-- Result: PDT_TBS2, PDT_TBS5, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P1'
ORDER BY B.INDEX_PARTITION_NAME;

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P2'
ORDER BY B.INDEX_PARTITION_NAME;

-- Result: PDT_TBS4, PDT_TBS3, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- Result: PDT_TBS5, PDT_TBS2, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P4'
ORDER BY B.INDEX_PARTITION_NAME;


--##############################
--+SECTOR; LOB COLUMN이 없는 경우(인덱스 파티션에 TBS지정할 경우)
--##############################
--##############
--# Left In-place
--##############
--+LOAD_SQL Schema_Index_Partition.sql;

-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P1;

-- Result: PDT_TBS2, PDT_TBS5, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P1'
ORDER BY B.INDEX_PARTITION_NAME;


--##############
--# Right In-place
--##############
--+LOAD_SQL Schema_Index_Partition.sql;

-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P2;

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P2'
ORDER BY B.INDEX_PARTITION_NAME;


--##############
--# Out-place
--##############
--+LOAD_SQL Schema_Index_Partition.sql;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P5_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P3, P4 INTO
    PARTITION P3 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P3_IDX1 TABLESPACE PDT_TBS2,
            IDX2 PARTITION P3_IDX2 TABLESPACE PDT_TBS3,
            IDX3 PARTITION P3_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS3, PDT_TBS4
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P5, P3 INTO
    PARTITION P3 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P3_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P3_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P3_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;


--+LOAD_SQL Schema_Index_Partition.sql;
-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P6_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P3, P4 INTO
    PARTITION P3 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P3_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P3_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P5, P3 INTO
    PARTITION P3 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P3_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P3_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;


--+LOAD_SQL Schema_Index_Partition.sql;
-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P3, P4 INTO
    PARTITION P3 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P5, P3 INTO
    PARTITION P3 TABLESPACE PDT_TBS;

-- Result: PDT_TBS, PDT_TBS, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;


--##############################
--+SECTOR; LOB COLUMN이 없는 경우(인덱스 파티션에 TBS지정하지 않을 경우)
--##############################
--##############
--# Left In-place
--##############
--+LOAD_SQL Schema_Index_Partition.sql;

-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P1;

-- Result: PDT_TBS2, PDT_TBS5, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P1'
ORDER BY B.INDEX_PARTITION_NAME;


--##############
--# Right In-place
--##############
--+LOAD_SQL Schema_Index_Partition.sql;

-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P2;

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P2'
ORDER BY B.INDEX_PARTITION_NAME;


--##############
--# Out-place
--##############
--+LOAD_SQL Schema_Index_Partition.sql;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P5_IDX2,
            IDX3 PARTITION P5_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS2, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P3, P4 INTO
    PARTITION P3 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P3_IDX1 TABLESPACE PDT_TBS2,
            IDX2 PARTITION P3_IDX2,
            IDX3 PARTITION P3_IDX3 );

-- Result: PDT_TBS2, PDT_TBS2, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P5, P3 INTO
    PARTITION P3
    INDEX ( IDX1 PARTITION P3_IDX1,
            IDX2 PARTITION P3_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P3_IDX3 );

-- Result: PDT_TBS, PDT_TBS4, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;


--+LOAD_SQL Schema_Index_Partition.sql;
-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P6_IDX3 );

-- Result: PDT_TBS2, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P3, P4 INTO
    PARTITION P3
    INDEX ( IDX1 PARTITION P3_IDX1,
            IDX3 PARTITION P3_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS, PDT_TBS4, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P5, P3 INTO
    PARTITION P3
    INDEX ( IDX1 PARTITION P3_IDX1,
            IDX3 PARTITION P3_IDX3 );

-- Result: PDT_TBS, PDT_TBS, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;


--+LOAD_SQL Schema_Index_Partition.sql;
-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5;

-- Result: PDT_TBS, PDT_TBS, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;


--##############################
--+SECTOR; LOB COLUMN이 있는 경우(인덱스 파티션에 TBS지정할 경우)
--##############################
--##############
--# Left In-place
--##############
--+LOAD_SQL Schema_Index_Partition_Lob.sql;

-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P1;

-- Result: PDT_TBS2, PDT_TBS5, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P1'
ORDER BY B.INDEX_PARTITION_NAME;


--##############
--# Right In-place
--##############
--+LOAD_SQL Schema_Index_Partition_Lob.sql;

-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P2;

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P2'
ORDER BY B.INDEX_PARTITION_NAME;


--##############
--# Out-place
--##############
--+LOAD_SQL Schema_Index_Partition_Lob.sql;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P5_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P3, P4 INTO
    PARTITION P3 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P3_IDX1 TABLESPACE PDT_TBS2,
            IDX2 PARTITION P3_IDX2 TABLESPACE PDT_TBS3,
            IDX3 PARTITION P3_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS3, PDT_TBS4
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P5, P3 INTO
    PARTITION P3 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P3_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P3_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P3_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;


--+LOAD_SQL Schema_Index_Partition_Lob.sql;
-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P6_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P3, P4 INTO
    PARTITION P3 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P3_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P3_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P5, P3 INTO
    PARTITION P3 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P3_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P3_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;


--+LOAD_SQL Schema_Index_Partition_Lob.sql;
-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P1, P2 INTO
    PARTITION P5 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P3, P4 INTO
    PARTITION P3 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T3 
MERGE PARTITIONS P5, P3 INTO
    PARTITION P3 TABLESPACE PDT_TBS;

-- Result: PDT_TBS, PDT_TBS, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;



--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;
