--+SYSTEM clean;
--+SYSTEM server start;

CREATE OR REPLACE PROCEDURE WAIT_LOGICAL_AGER_PROC( )
AS
BEGIN
    DECLARE
    CURSOR C1 IS SELECT AGING_REQUEST_OID_CNT, AGING_PROCESSED_OID_CNT
    FROM V$MEMGC
    WHERE GC_NAME = 'MEM_LOGICAL_AGER';
    IDX_REC C1%ROWTYPE;
    BEGIN
        LOOP
            OPEN C1;
            FETCH C1 INTO IDX_REC;
            EXIT WHEN C1%NOTFOUND;
            IF IDX_REC.AGING_REQUEST_OID_CNT = IDX_REC.AGING_PROCESSED_OID_CNT THEN
                EXIT;
            END IF;
            CLOSE C1;
        END LOOP;
    END;
END;
/
 
CREATE OR REPLACE PROCEDURE WAIT_PHYSICAL_AGER_PROC( )
AS
BEGIN
    DECLARE
    CURSOR C1 IS SELECT AGING_REQUEST_OID_CNT, AGING_PROCESSED_OID_CNT
    FROM V$MEMGC
    WHERE GC_NAME = 'MEM_DELTHR';
    IDX_REC C1%ROWTYPE;
    BEGIN
        LOOP
            OPEN C1;
            FETCH C1 INTO IDX_REC;
            EXIT WHEN C1%NOTFOUND;
            IF IDX_REC.AGING_REQUEST_OID_CNT = IDX_REC.AGING_PROCESSED_OID_CNT THEN
                EXIT;
            END IF;
            CLOSE C1;
        END LOOP;
    END;
END;
/
 
CREATE OR REPLACE PROCEDURE WAIT_MEMGC_PROC( )
AS
BEGIN
    WAIT_LOGICAL_AGER_PROC;
    WAIT_PHYSICAL_AGER_PROC;
END;
/
 
CREATE TABLE T1 ( I1 INTEGER, I2 CHAR(16000) );
CREATE INDEX T1X ON T1 ( I1 );
INSERT INTO T1 VALUES( 1, 1 );
INSERT INTO T1 VALUES( 1, 2 );
INSERT INTO T1 VALUES( 2, 3 );
INSERT INTO T1 VALUES( 1, 4 );
INSERT INTO T1 VALUES( 2, 5 );
INSERT INTO T1 VALUES( 1, 6 );
INSERT INTO T1 VALUES( 1, 7 );
INSERT INTO T1 VALUES( 1, 8 );

DELETE FROM T1 WHERE I1 = 2;

EXEC WAIT_MEMGC_PROC;

ALTER SYSTEM CHECKPOINT;
ALTER SYSTEM CHECKPOINT;

INSERT INTO T1 VALUES( 2, 9 );
INSERT INTO T1 VALUES( 2, 01);
INSERT INTO T1 VALUES( 2, 02);
INSERT INTO T1 VALUES( 2, 03);

SELECT I1 FROM T1;
SELECT PAGE_ID, OFFSET, USED_FLAG, VALUE24B FROM D$MEM_TABLE_RECORD( T1 ) WHERE NTH_COLUMN=0;

--+SKIP BEGIN;
DROP PROCEDURE WAIT_MEMGC_PROC;
DROP PROCEDURE WAIT_LOGICAL_AGER_PROC;
DROP PROCEDURE WAIT_PHYSICAL_AGER_PROC;
--+SKIP END;

--+SYSTEM server kill;
--+SYSTEM rm -rf $ALTIBASE_HOME/dbs2
--+SYSTEM rm -rf $ALTIBASE_HOME/logs2
--+SYSTEM cp -rf $ALTIBASE_HOME/dbs $ALTIBASE_HOME/dbs2 
--+SYSTEM cp -rf $ALTIBASE_HOME/logs $ALTIBASE_HOME/logs2 
--+SYSTEM source gensh.sh
