--###################################################################
--# ALTER TABLE ... ENABLE/DISABLE ROWMOVEMENT(PartKey: VARCHAR)
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

--+APPEND_LST Schema_Hash_Varchar.sql;
--+SYSTEM is -silent -f Schema_Hash_Varchar.sql;

--###################################################################
--+ SECTOR; BASIC TEST
--###################################################################
--##############################
--+SECTOR; 문법 체크
--##############################
DROP TABLE TEST;

-- should be fail
CREATE TABLE TEST( I1 VARCHAR(10), I2 INTEGER )
PARTITION BY HASH(I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS ENABLE ROW MOVEMENT;

-- should be fail
CREATE TABLE TEST( I1 VARCHAR(10), I2 INTEGER )
PARTITION BY HASH(I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3 ENABLE ROW MOVEMENT,
    PARTITION P4
) TABLESPACE PDT_TBS;

-- should be success
CREATE TABLE TEST( I1 VARCHAR(1000), I2 INTEGER )
PARTITION BY HASH(I1)
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) ENABLE ROW MOVEMENT TABLESPACE PDT_TBS;


--##############################
--+SECTOR; 파티션의 개수
--##############################
--#############
--# 4개
--#############
--+SYSTEM is -silent -f Schema_Hash_Varchar.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + '050';

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = I1 + '050';

SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);

--#############
--# 1개
--#############
--+SYSTEM is -silent -f Schema_Hash_Varchar.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

ALTER TABLE T1 
COALESCE PARTITION;

ALTER TABLE T1 
COALESCE PARTITION;

ALTER TABLE T1 
COALESCE PARTITION;

UPDATE T1 SET I1 = I1 + '050';

-- result: 13
SELECT COUNT(*) FROM T1;


ALTER TABLE T2
ENABLE ROW MOVEMENT;

ALTER TABLE T2 
COALESCE PARTITION;

ALTER TABLE T2 
COALESCE PARTITION;

ALTER TABLE T2 
COALESCE PARTITION;

UPDATE T2 SET I1 = I1 + '050';

-- result: 13
SELECT COUNT(*) FROM T2;


--##############################
--+SECTOR; LOB 컬럼이 있는 경우
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 VARCHAR(1000), I2 BLOB, I3 CLOB )
PARTITION BY HASH(I1) 
( PARTITION P1 TABLESPACE PDT_TBS 
                        LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ), 
  PARTITION P2 TABLESPACE PDT_TBS3,
  PARTITION P3 TABLESPACE PDT_TBS4,
  PARTITION P4
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

CREATE INDEX IDX_LOB ON T1(I1);

INSERT INTO T1 VALUES (NULL, '100', 100);
INSERT INTO T1 VALUES ('000', '100', 100);
INSERT INTO T1 VALUES ('050', '100', 100);
INSERT INTO T1 VALUES ('075', '100', 100);
INSERT INTO T1 VALUES ('100', '100', 100);
INSERT INTO T1 VALUES ('150', '100', 100);
INSERT INTO T1 VALUES ('175', '100', 100);
INSERT INTO T1 VALUES ('200', '100', 100);
INSERT INTO T1 VALUES ('250', '100', 100);
INSERT INTO T1 VALUES ('275', '100', 100);
INSERT INTO T1 VALUES ('300', '100', 100);
INSERT INTO T1 VALUES ('350', '100', 100);
INSERT INTO T1 VALUES ('375', '100', 100);

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + '050';

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);



--##################################################################
--+SECTOR; UPDATE 조건에 따른 검사
--##################################################################
--##############################
--+SECTOR; 여러 파티션으로 분산
--##############################
--+SYSTEM is -silent -f Schema_Hash_Varchar.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + '050';

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = I1 + '050';

SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);


--##############################
--+SECTOR; 모두 같은 파티션으로 이동
--##############################
--+SYSTEM is -silent -f Schema_Hash_Varchar.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = '050';
SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

UPDATE T1 SET I1 = '150';
SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

UPDATE T1 SET I1 = '250';
SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

UPDATE T1 SET I1 = '1000';
SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = '050';
SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);

UPDATE T2 SET I1 = '150';
SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);

UPDATE T2 SET I1 = '250';
SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);

UPDATE T2 SET I1 = '1000';
SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);


--##############################
--+SECTOR; 현재 파티션에 그대로 있는 경우
--##############################
--+SYSTEM is -silent -f Schema_Hash_Varchar.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + '001';

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = I1 + '001';

SELECT COUNT(*) FROM T2 PARTITION (P1);
SELECT COUNT(*) FROM T2 PARTITION (P2);
SELECT COUNT(*) FROM T2 PARTITION (P3);
SELECT COUNT(*) FROM T2 PARTITION (P4);



--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;
