--###################################################################
--# ALTER TABLE ... ENABLE/DISABLE ROWMOVEMENT(PartKey: DATE)
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

--+APPEND_LST Schema_List_Date.sql;
--+SYSTEM is -silent -f Schema_List_Date.sql;

--###################################################################
--+ SECTOR; BASIC TEST
--###################################################################
--##############################
--+SECTOR; 문법 체크
--##############################
DROP TABLE TEST;

-- should be fail
CREATE TABLE TEST( I1 DATE, I2 INTEGER )
PARTITION BY LIST(I1)
(
    PARTITION P1 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD')),
    PARTITION P2 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD')),
    PARTITION P3 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD')),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS ENABLE ROW MOVEMENT;

-- should be fail
CREATE TABLE TEST( I1 DATE, I2 INTEGER )
PARTITION BY LIST(I1)
(
    PARTITION P1 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD')),
    PARTITION P2 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD')),
    PARTITION P3 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD')) ENABLE ROW MOVEMENT,
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE TABLE TEST( I1 DATE, I2 INTEGER )
PARTITION BY LIST(I1)
(
    PARTITION P1 VALUES (TO_DATE('2007-05-05', 'YYYY-MM-DD')),
    PARTITION P2 VALUES (TO_DATE('2007-06-05', 'YYYY-MM-DD')),
    PARTITION P3 VALUES (TO_DATE('2007-07-05', 'YYYY-MM-DD')),
    PARTITION P4 VALUES DEFAULT
) ENABLE ROW MOVEMENT TABLESPACE PDT_TBS;


--##############################
--+SECTOR; 파티션의 개수
--##############################
--#############
--# 4개
--#############
--+SYSTEM is -silent -f Schema_List_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + 30;

-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P1);
-- result: 1
SELECT COUNT(*) FROM T1 PARTITION (P2);
-- result: 3
SELECT COUNT(*) FROM T1 PARTITION (P3);
-- result: 9
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = I1 + 30;

-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P1);
-- result: 1
SELECT COUNT(*) FROM T2 PARTITION (P2);
-- result: 3
SELECT COUNT(*) FROM T2 PARTITION (P3);
-- result: 9
SELECT COUNT(*) FROM T2 PARTITION (P4);

--#############
--# 1개
--#############
--+SYSTEM is -silent -f Schema_List_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

ALTER TABLE T1 
MERGE PARTITIONS P1, P2 INTO PARTITION P1;

ALTER TABLE T1 
MERGE PARTITIONS P3, P4 INTO PARTITION P3;

ALTER TABLE T1 
MERGE PARTITIONS P1, P3 INTO PARTITION P1;

UPDATE T1 SET I1 = I1 + 30;

-- result: 13
SELECT COUNT(*) FROM T1;


ALTER TABLE T2
ENABLE ROW MOVEMENT;

ALTER TABLE T2 
MERGE PARTITIONS P1, P2 INTO PARTITION P1;

ALTER TABLE T2 
MERGE PARTITIONS P3, P4 INTO PARTITION P3;

ALTER TABLE T2 
MERGE PARTITIONS P1, P3 INTO PARTITION P1;

UPDATE T2 SET I1 = I1 + 30;

-- result: 13
SELECT COUNT(*) FROM T2;


--##############################
--+SECTOR; LOB 컬럼이 있는 경우
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 DATE, I2 BLOB, I3 CLOB )
PARTITION BY LIST(I1) 
( PARTITION P1 VALUES ( TO_DATE('2007-05-01', 'YYYY-MM-DD'), TO_DATE('2007-05-15', 'YYYY-MM-DD'), TO_DATE('2007-05-30', 'YYYY-MM-DD') ) TABLESPACE PDT_TBS 
                        LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ), 
  PARTITION P2 VALUES ( TO_DATE('2007-06-01', 'YYYY-MM-DD'), TO_DATE('2007-06-15', 'YYYY-MM-DD'), TO_DATE('2007-06-30', 'YYYY-MM-DD'), NULL ) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES ( TO_DATE('2007-07-01', 'YYYY-MM-DD'), TO_DATE('2007-07-15', 'YYYY-MM-DD'), TO_DATE('2007-07-30', 'YYYY-MM-DD') ) TABLESPACE PDT_TBS4,
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

CREATE INDEX IDX_LOB ON T1(I1);

INSERT INTO T1 VALUES (NULL, 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-05-01', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-05-15', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-05-30', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-06-01', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-06-15', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-06-30', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-07-01', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-07-15', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-07-30', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-08-01', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-08-15', 'YYYY-MM-DD'), 'ABC', 'ABC');
INSERT INTO T1 VALUES (TO_DATE('2007-08-30', 'YYYY-MM-DD'), 'ABC', 'ABC');


ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + 30;

-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P1);
-- result: 1
SELECT COUNT(*) FROM T1 PARTITION (P2);
-- result: 3
SELECT COUNT(*) FROM T1 PARTITION (P3);
-- result: 9
SELECT COUNT(*) FROM T1 PARTITION (P4);



--##################################################################
--+SECTOR; UPDATE 조건에 따른 검사
--##################################################################
--##############################
--+SECTOR; 여러 파티션으로 분산
--##############################
--+SYSTEM is -silent -f Schema_List_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1 + 30;

-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P1);
-- result: 1
SELECT COUNT(*) FROM T1 PARTITION (P2);
-- result: 3
SELECT COUNT(*) FROM T1 PARTITION (P3);
-- result: 9
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = I1 + 30;

-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P1);
-- result: 1
SELECT COUNT(*) FROM T2 PARTITION (P2);
-- result: 3
SELECT COUNT(*) FROM T2 PARTITION (P3);
-- result: 9
SELECT COUNT(*) FROM T2 PARTITION (P4);


--##############################
--+SECTOR; 모두 같은 파티션으로 이동
--##############################
--+SYSTEM is -silent -f Schema_List_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = TO_DATE('2007-05-01', 'YYYY-MM-DD');
-- result: 13
SELECT COUNT(*) FROM T1 PARTITION (P1);
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P2);
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P3);
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P4);

UPDATE T1 SET I1 = TO_DATE('2007-06-01', 'YYYY-MM-DD');
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P1);
-- result: 13
SELECT COUNT(*) FROM T1 PARTITION (P2);
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P3);
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P4);

UPDATE T1 SET I1 = TO_DATE('2007-07-01', 'YYYY-MM-DD');
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P1);
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P2);
-- result: 13
SELECT COUNT(*) FROM T1 PARTITION (P3);
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P4);

UPDATE T1 SET I1 = TO_DATE('2007-08-01', 'YYYY-MM-DD');
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P1);
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P2);
-- result: 0
SELECT COUNT(*) FROM T1 PARTITION (P3);
-- result: 13
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = TO_DATE('2007-05-01', 'YYYY-MM-DD');
-- result: 13
SELECT COUNT(*) FROM T2 PARTITION (P1);
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P2);
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P3);
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P4);

UPDATE T2 SET I1 = TO_DATE('2007-06-01', 'YYYY-MM-DD');
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P1);
-- result: 13
SELECT COUNT(*) FROM T2 PARTITION (P2);
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P3);
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P4);

UPDATE T2 SET I1 = TO_DATE('2007-07-01', 'YYYY-MM-DD');
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P1);
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P2);
-- result: 13
SELECT COUNT(*) FROM T2 PARTITION (P3);
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P4);

UPDATE T2 SET I1 = TO_DATE('2007-08-01', 'YYYY-MM-DD');
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P1);
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P2);
-- result: 0
SELECT COUNT(*) FROM T2 PARTITION (P3);
-- result: 13
SELECT COUNT(*) FROM T2 PARTITION (P4);


--##############################
--+SECTOR; 현재 파티션에 그대로 있는 경우
--##############################
--+SYSTEM is -silent -f Schema_List_Date.sql;

ALTER TABLE T1
ENABLE ROW MOVEMENT;

UPDATE T1 SET I1 = I1;

-- result: 3
SELECT COUNT(*) FROM T1 PARTITION (P1);
-- result: 4
SELECT COUNT(*) FROM T1 PARTITION (P2);
-- result: 3
SELECT COUNT(*) FROM T1 PARTITION (P3);
-- result: 3
SELECT COUNT(*) FROM T1 PARTITION (P4);


ALTER TABLE T2
ENABLE ROW MOVEMENT;

UPDATE T2 SET I1 = I1;

-- result: 3
SELECT COUNT(*) FROM T2 PARTITION (P1);
-- result: 4
SELECT COUNT(*) FROM T2 PARTITION (P2);
-- result: 3
SELECT COUNT(*) FROM T2 PARTITION (P3);
-- result: 3
SELECT COUNT(*) FROM T2 PARTITION (P4);



--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;
