--###########################################################################
--# ported from qp4/Project3/PROJ-1624-GlobalIndex/PROJ-1624-QC/PDT/Design/ALTER_TABLE/ADD/index_partition.sql
--#
--# Body below is byte-identical to the original. The one line this port
--# adds is the premise: the original measures these statements on the
--# $GIT_ hidden-table implementation, this file measures the same
--# statements on the native global index (F07 -- see include/pinNative.sql).
--###########################################################################
--###########################################################################
--# NativeGlobalIndexPort1624 - the premise of every ported .sql case.
--#
--# A .sql case cannot CALL a DEF the way a .tc case calls PIN_DISK_NATIVE(),
--# so the same two statements are pulled in per case with ATC's own include
--# directive:
--#
--#     --+LOAD_SQL <relative path>/include/pinNative.sql;
--#
--# ATC inlines this file into the case transcript between BEGIN/END markers,
--# which is exactly what F07 asks for: the case states its own premise at the
--# head of its own transcript instead of inheriting whatever the instance
--# happens to be configured with.
--#
--#     DISK_GLOBAL_INDEX_ENABLE = 1  -> native  (this suite)
--#     DISK_GLOBAL_INDEX_ENABLE = 0  -> $GIT_   (the original suite)
--#
--# The readout below is not decoration. It is the tooth: if the property is
--# ever 0 when a case runs, this one line differs and the case is red before
--# it has measured anything, instead of quietly measuring the other
--# implementation (disk-natc.md 6 records nine assertions that drifted that
--# way).
--#
--# ASCII only, on purpose: 87 of the ported case bodies are EUC-KR and their
--# bytes must stay untouched, so nothing this port adds may introduce a
--# second encoding into a transcript.
--###########################################################################

ALTER SYSTEM SET DISK_GLOBAL_INDEX_ENABLE = 1;

SELECT CAST(VALUE1 AS VARCHAR(10)) DISK_GLOBAL_INDEX_ENABLE
FROM V$PROPERTY WHERE NAME = 'DISK_GLOBAL_INDEX_ENABLE';

--###################################################################
--# 인덱스 파티션을 직접 지정하는 경우
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

--+APPEND_LST Schema_Index_Partition.sql;
--+SYSTEM is -silent -f Schema_Index_Partition.sql;

--###################################################################
--+ SECTOR; 문법 체크
--###################################################################
-- should be fail
ALTER TABLE T1 
ADD
PARTITION P5 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4 )
    LOB STORE AS ( TABLESPACE PDT_TBS2 );
    
-- should be fail
ALTER TABLE T1 
ADD
PARTITION P6 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4 
                LOB STORE AS ( TABLESPACE PDT_TBS2 ) );


--##############################
--+SECTOR; 파티션드 테이블인지 체크
--##############################
DROP TABLE TEST;
CREATE TABLE TEST( I1 INTEGER, I2 INTEGER );

-- should be fail
ALTER TABLE TEST 
ADD
    PARTITION P5 TABLESPACE PDT_TBS2
        INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4 );

DROP TABLE TEST;


--##############################
--+SECTOR; 지정한 인덱스가 있는지 체크
--##############################
--+SYSTEM is -silent -f Schema_Index_Partition.sql;

-- should be fail
ALTER TABLE T1 
ADD
    PARTITION P5 TABLESPACE PDT_TBS2
        INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4 );

-- should be fail
ALTER TABLE T2 
ADD
    PARTITION P5 TABLESPACE PDT_TBS2
        INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
                IDX4 PARTITION P5_IDX2 TABLESPACE PDT_TBS4 );

-- should be fail
ALTER TABLE T2 
ADD
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX4 PARTITION P6_IDX4 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4 );

-- should be fail
ALTER TABLE T2 
ADD
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P6_IDX3 TABLESPACE PDT_TBS4,
                IDX4 PARTITION P6_IDX4 TABLESPACE PDT_TBS4 );


--##############################
--+SECTOR; 인덱스 파티션 이름 중복 체크
--##############################
--+SYSTEM is -silent -f Schema_Index_Partition.sql;

-- 파티션드 인덱스 이름 중복
-- should be fail
ALTER TABLE T2 
ADD
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX1 PARTITION P6_IDX3 TABLESPACE PDT_TBS4 );

-- 인덱스 파티션 이름 중복
-- should be fail
ALTER TABLE T2 
ADD
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P6_IDX1 TABLESPACE PDT_TBS4 );

-- 이미 있는 인덱스 파티션 이름
-- should be fail
ALTER TABLE T2 
ADD
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P1_IDX3 TABLESPACE PDT_TBS4 );

-- 이미 있는 인덱스 파티션 이름
-- should be fail
ALTER TABLE T2 
ADD
    PARTITION P6 TABLESPACE PDT_TBS3
        INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P2_IDX3 TABLESPACE PDT_TBS4 );

-- 이미 있는 인덱스 파티션 이름
-- should be fail
ALTER TABLE T2 
ADD
    PARTITION P7
        INDEX ( IDX1 PARTITION P7_IDX1 TABLESPACE PDT_TBS3,
                IDX2 PARTITION P7_IDX2 TABLESPACE PDT_TBS4,
                IDX3 PARTITION P4_IDX3 TABLESPACE PDT_TBS4 );



--##################################################################
--+SECTOR; 인덱스 파티션 지정
--##################################################################
--+SYSTEM is -silent -f Schema_Index_Partition.sql;

-- Result: PDT_TBS2, PDT_TBS5, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P1'
ORDER BY B.INDEX_PARTITION_NAME;

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P2'
ORDER BY B.INDEX_PARTITION_NAME;

-- Result: PDT_TBS4, PDT_TBS3, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P3'
ORDER BY B.INDEX_PARTITION_NAME;

-- Result: PDT_TBS5, PDT_TBS2, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P4'
ORDER BY B.INDEX_PARTITION_NAME;


--##############################
--+SECTOR; LOB COLUMN이 없는 경우(인덱스 파티션에 TBS지정할 경우)
--##############################
--+SYSTEM is -silent -f Schema_Index_Partition.sql;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P5 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P5_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P6 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS2,
            IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS3,
            IDX3 PARTITION P6_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS3, PDT_TBS4
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P6'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P7 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P7_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P7_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P7_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P7'
ORDER BY B.INDEX_PARTITION_NAME;


--+SYSTEM is -silent -f Schema_Index_Partition.sql;
-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P8 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P8_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P8_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P8'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P9 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P9_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P9_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P9'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P10 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P10_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P10_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P10'
ORDER BY B.INDEX_PARTITION_NAME;


-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P11 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P11'
ORDER BY B.INDEX_PARTITION_NAME;

-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P12 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P12'
ORDER BY B.INDEX_PARTITION_NAME;

-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P13 TABLESPACE PDT_TBS;

-- Result: PDT_TBS, PDT_TBS, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P13'
ORDER BY B.INDEX_PARTITION_NAME;


--##############################
--+SECTOR; LOB COLUMN이 없는 경우(인덱스 파티션에 TBS지정하지 않을 경우)
--##############################
--+SYSTEM is -silent -f Schema_Index_Partition.sql;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P5 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P5_IDX2,
            IDX3 PARTITION P5_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS2, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P6 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS2,
            IDX2 PARTITION P6_IDX2,
            IDX3 PARTITION P6_IDX3 );

-- Result: PDT_TBS2, PDT_TBS2, PDT_TBS2
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P6'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P7
    INDEX ( IDX1 PARTITION P7_IDX1,
            IDX2 PARTITION P7_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P7_IDX3 );

-- Result: PDT_TBS, PDT_TBS4, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P7'
ORDER BY B.INDEX_PARTITION_NAME;


--+SYSTEM is -silent -f Schema_Index_Partition.sql;
-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P8 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P8_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P8_IDX3 );

-- Result: PDT_TBS2, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P8'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P9
    INDEX ( IDX1 PARTITION P9_IDX1,
            IDX3 PARTITION P9_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS, PDT_TBS4, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P9'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P10
    INDEX ( IDX1 PARTITION P10_IDX1,
            IDX3 PARTITION P10_IDX3 );

-- Result: PDT_TBS, PDT_TBS, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P10'
ORDER BY B.INDEX_PARTITION_NAME;


-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T2 
ADD
    PARTITION P11;

-- Result: PDT_TBS, PDT_TBS, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T2' AND
      A.PARTITION_NAME='P11'
ORDER BY B.INDEX_PARTITION_NAME;


--##############################
--+SECTOR; LOB COLUMN이 있는 경우(인덱스 파티션에 TBS지정할 경우)
--##############################
--+SYSTEM is -silent -f Schema_Index_Partition_Lob.sql;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
ADD
    PARTITION P5 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P5_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P5_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P5_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P5'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
ADD
    PARTITION P6 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P6_IDX1 TABLESPACE PDT_TBS2,
            IDX2 PARTITION P6_IDX2 TABLESPACE PDT_TBS3,
            IDX3 PARTITION P6_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS3, PDT_TBS4
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P6'
ORDER BY B.INDEX_PARTITION_NAME;

-- 모든 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
ADD
    PARTITION P7 TABLESPACE PDT_TBS2
    INDEX ( IDX1 PARTITION P7_IDX1 TABLESPACE PDT_TBS3,
            IDX2 PARTITION P7_IDX2 TABLESPACE PDT_TBS4,
            IDX3 PARTITION P7_IDX3 TABLESPACE PDT_TBS5 );

-- Result: PDT_TBS3, PDT_TBS4, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P7'
ORDER BY B.INDEX_PARTITION_NAME;


--+SYSTEM is -silent -f Schema_Index_Partition_Lob.sql;
-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
ADD
    PARTITION P8 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P8_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P8_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P8'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
ADD
    PARTITION P9 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P9_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P9_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P9'
ORDER BY B.INDEX_PARTITION_NAME;

-- 부분 인덱스 파티션 지정
-- should be success
ALTER TABLE T3 
ADD
    PARTITION P10 TABLESPACE PDT_TBS3
    INDEX ( IDX1 PARTITION P10_IDX1 TABLESPACE PDT_TBS2,
            IDX3 PARTITION P10_IDX3 TABLESPACE PDT_TBS4 );

-- Result: PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P10'
ORDER BY B.INDEX_PARTITION_NAME;


-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T3 
ADD
    PARTITION P11 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P11'
ORDER BY B.INDEX_PARTITION_NAME;

-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T3 
ADD
    PARTITION P12 TABLESPACE PDT_TBS3;

-- Result: PDT_TBS3, PDT_TBS3, PDT_TBS3
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P12'
ORDER BY B.INDEX_PARTITION_NAME;

-- 인덱스 파티션 지정하지 않음
-- should be success
ALTER TABLE T3 
ADD
    PARTITION P13 TABLESPACE PDT_TBS;

-- Result: PDT_TBS, PDT_TBS, PDT_TBS
SELECT D.NAME
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ A,
     SYSTEM_.SYS_INDEX_PARTITIONS_ B,
     SYSTEM_.SYS_TABLES_ C,
     V$TABLESPACES D
WHERE B.TBS_ID = D.ID AND
      A.PARTITION_ID = B.TABLE_PARTITION_ID AND
      A.TABLE_ID = C.TABLE_ID AND
      C.TABLE_NAME='T3' AND
      A.PARTITION_NAME='P13'
ORDER BY B.INDEX_PARTITION_NAME;

--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;
