--######################################################
-- UPDATE RANGE PARTITIOIN ( PK:INTEGER )
--######################################################

--###################################
--+SECTOR; INTIALIZE
--###################################

--+SKIP BEGIN;
DROP TABLE PDT_RANGE;
--+SKIP END;

--#########################################
--+SECTOR; DO JOB #1 (1. Basic Test)
--#########################################

CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

UPDATE PDT_RANGE PARTITION( P1 ) SET F2 = F2;
UPDATE PDT_RANGE PARTITION( P2 ) SET F2 = F2;
UPDATE PDT_RANGE PARTITION( P3 ) SET F2 = F2;
UPDATE PDT_RANGE PARTITION( P4 ) SET F2 = F2;


--#########################################
--+SECTOR; DO JOB #2 (2. Validation Test)
--#########################################

DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

-- should be fail
UPDATE PDT_RANGE PARTITION( P5 ) SET F2 = F2;


--#########################################
--+SECTOR; DO JOB #3 (3. Execution Test)
--#########################################

-------------------------------------
-- 3.1 Partition Pruning ( User )
-------------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

-- please check plan
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_RANGE PARTITION( P1 ) SET F2 = F2;
UPDATE PDT_RANGE PARTITION( P2 ) SET F2 = F2;
UPDATE PDT_RANGE PARTITION( P3 ) SET F2 = F2;
UPDATE PDT_RANGE PARTITION( P4 ) SET F2 = F2;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

ALTER SESSION SET EXPLAIN PLAN = ON;
-- no need execution
UPDATE PDT_RANGE PARTITION( P1 ) SET F2 = F2 
WHERE F1 >= 10 AND F1 < 20;
UPDATE PDT_RANGE PARTITION( P2 ) SET F2 = F2
WHERE F1 >= 20 AND F1 < 30;
ALTER SESSION SET EXPLAIN PLAN = OFF;

-------------------------------------
-- 3.2 Partition Pruning ( System )
-------------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

-- less than 
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 < 10;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 < 20;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 < 30;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 < 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

-- equal
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 = 10;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 = 20;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 = 30;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 = 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

-- greater than
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 > 10;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 > 20;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 > 30;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 > 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

-- less equal than
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 <= 10;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 <= 20;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 <= 30;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 <= 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

-- greater equal than
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 >= 10;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 >= 20;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 >= 30;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 >= 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 >= 10 AND F1 < 20;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 >= 20 AND F1 < 30;
ALTER SESSION SET EXPLAIN PLAN = OFF;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

-- not equal
ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_RANGE SET F2 = F2;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 != 10;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 != 20;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 != 30;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 != 40;
ALTER SESSION SET EXPLAIN PLAN = OFF;

-------------------------------------
-- 3.3 Partition filtering
-------------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO PDT_RANGE VALUES( 0, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );

ALTER SESSION SET EXPLAIN PLAN = ON;
UPDATE PDT_RANGE SET F2 = F2;
UPDATE PDT_RANGE SET F2 = F2 WHERE F2 = 0;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 = F1;
UPDATE PDT_RANGE SET F2 = F2 WHERE F1 = F2;
ALTER SESSION SET EXPLAIN PLAN = OFF;


--###################################
--+SECTOR; FINALIZE
--###################################

DROP TABLE PDT_RANGE;
