--+DECLARE SERVER REPL_SERVER1 DB1;

--+SYSTEM @DB1 server stop;

--+SET_ENV @DB1 ALTIBASE_REPLICATION_SYNC_LOG=1;
--+SET_ENV @DB1 ALTIBASE_REPLICATION_LOG_BUFFER_SIZE=0;

--+SYSTEM @DB1 server start;
