--+SKIP BEGIN;
DROP TABLE LINEITEM_M;
--+SKIP END;

CREATE TABLE LINEITEM_M (
    L_ORDERKEY INTEGER,
    L_PARTKEY INTEGER,
    L_SUPPKEY INTEGER,
    L_LINENUMBER INTEGER,
    L_QUANTITY NUMERIC(15,2),
    L_EXTENDEDPRICE NUMERIC(15,2),
    L_DISCOUNT NUMERIC(15,2),
    L_TAX NUMERIC(15,2),
    L_RETURNFLAG CHAR(1),
    L_LINESTATUS CHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE CHAR(10),
    L_COMMENT VARCHAR(44)
) TABLESPACE SYS_TBS_MEMORY;

--+SYSTEM iloader in -S 127.0.0.1 -U SYS -P MANAGER -d ./lineitem.tbl -f ./lineitem.fmt -t '|' -array 1000

select count(*) from lineitem_m;
