--###########################################################################
--# ported from qp4/Project3/PROJ-1624-GlobalIndex/PROJ-1624-QC/PDT/Design/CREATE_INDEX/LOCAL/RangePartTable.sql
--#
--# Body below is byte-identical to the original. The one line this port
--# adds is the premise: the original measures these statements on the
--# $GIT_ hidden-table implementation, this file measures the same
--# statements on the native global index (F07 -- see include/pinNative.sql).
--###########################################################################
--+LOAD_SQL ../../../../include/pinNative.sql;

--###################################################################
--# CREATE INDEX TEST
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP INDEX IDX1;
DROP INDEX IDX2;
--+SKIP END;

--###################################################################
--+ SECTOR; BASIC TEST
--###################################################################
----------------------------------------
-- CREATING INDEX USING CREATE_TABLE
----------------------------------------
DROP TABLE T1;
CREATE TABLE T1
(
    I1   INTEGER PRIMARY KEY,
    I2   INTEGER
) 
PARTITION BY RANGE( I1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;
INSERT INTO T1 VALUES( 35, 0 );
INSERT INTO T1 VALUES( 30, 0 );
INSERT INTO T1 VALUES( 25, 0 );
INSERT INTO T1 VALUES( 20, 0 );
INSERT INTO T1 VALUES( 15, 0 );
INSERT INTO T1 VALUES( 10, 0 );
INSERT INTO T1 VALUES( 5, 0 );
INSERT INTO T1 VALUES( 0, 0 );

-- BUGBUG
-- should be {0}
SELECT I1 FROM T1
WHERE I1 >= 0 LIMIT 1;

----------------------------------------
-- CREATING INDEX USING CREATE_INDEX
----------------------------------------
DROP TABLE T1;
CREATE TABLE T1
(
    I1   INTEGER,
    I2   INTEGER
) 
PARTITION BY RANGE( I1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;
INSERT INTO T1 VALUES( 35, 0 );
INSERT INTO T1 VALUES( 30, 0 );
INSERT INTO T1 VALUES( 25, 0 );
INSERT INTO T1 VALUES( 20, 0 );
INSERT INTO T1 VALUES( 15, 0 );
INSERT INTO T1 VALUES( 10, 0 );
INSERT INTO T1 VALUES( 5, 0 );
INSERT INTO T1 VALUES( 0, 0 );

-- should be {5}
SELECT I1 FROM T1 PARTITION( P1 ) LIMIT 1;

CREATE INDEX IDX1
ON T1( I1 ) LOCAL;

-- BUGBUG
-- should be {0}
SELECT /*+ INDEX ASC ( T1, IDX1 ) */ I1
FROM T1 PARTITION( P1 ) LIMIT 1;



--###################################################################
--+ SECTOR; 파티션드 테이블인지 체크
--###################################################################
DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

CREATE TABLE T2 ( I1 INTEGER, I2 INTEGER ) TABLESPACE PDT_TBS;

DROP INDEX IDX1;
-- should be success
CREATE INDEX IDX1 ON T1 (I1) LOCAL;

DROP INDEX IDX1;
-- should be fail
CREATE INDEX IDX1 ON T2 (I1) LOCAL;


--###################################################################
--+ SECTOR; 유니크 인덱스 생성(프리픽스드 인덱스인지 체크)
--###################################################################
--###############################
--+ SECTOR; 유니크 제약 체크
--###############################
DROP TABLE T1;
CREATE TABLE T1
(
    I1   INTEGER,
    I2   INTEGER
)
PARTITION BY RANGE( I1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;
INSERT INTO T1 VALUES( 35, 10 );
INSERT INTO T1 VALUES( 30, 15 );
INSERT INTO T1 VALUES( 25, 20 );
INSERT INTO T1 VALUES( 20, 25 );
INSERT INTO T1 VALUES( 15, 30 );
INSERT INTO T1 VALUES( 10, 35 );
INSERT INTO T1 VALUES( 5, 0 );
INSERT INTO T1 VALUES( 0, 5 );

CREATE UNIQUE INDEX IDX1
ON T1( I1 ) LOCAL;

-- should be fail
INSERT INTO T1 VALUES( 35, 10 );
-- should be fail
INSERT INTO T1 VALUES( 30, 15 );
-- should be fail
INSERT INTO T1 VALUES( 25, 20 );
-- should be fail
INSERT INTO T1 VALUES( 20, 25 );
-- should be fail
INSERT INTO T1 VALUES( 15, 30 );
-- should be fail
INSERT INTO T1 VALUES( 10, 35 );
-- should be fail
INSERT INTO T1 VALUES( 5, 0 );
-- should be fail
INSERT INTO T1 VALUES( 0, 5 );

ALTER TABLE T1
ENABLE ROW MOVEMENT;

-- BUGBUG
-- should be fail
-- UPDATE T1 SET I1 = 20
-- WHERE I1 = 30;

--##############################
--+SECTOR; 파티션 키 개수 = 인덱스 키 개수
--##############################
DROP TABLE T1;
DROP TABLE T2;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE UNIQUE INDEX IDX1 ON T1(I1) LOCAL;


DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1,I2,I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES( 350, 0, 0 );
INSERT INTO T1 VALUES( 300, 0, 0 );
INSERT INTO T1 VALUES( 250, 0, 0 );
INSERT INTO T1 VALUES( 200, 0, 0 );
INSERT INTO T1 VALUES( 150, 0, 0 );
INSERT INTO T1 VALUES( 100, 0, 0 );
INSERT INTO T1 VALUES( 50,  0, 0 );
INSERT INTO T1 VALUES( 0,   0, 0 );

-- should be success
CREATE UNIQUE INDEX IDX1 ON T1(I1,I2,I3) LOCAL;

-- BUGBUG
-- Result: {0,50,100,150,200,250,300,350}
SELECT /*+ INDEX ASC ( T1, IDX1 ) */ I1
FROM T1;


DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1,I2,I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE UNIQUE INDEX IDX1 ON T1(I1,I2,I3) LOCAL;


DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1,I2,I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE UNIQUE INDEX IDX1 ON T1(I3,I1,I2) LOCAL;


DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1,I2,I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE UNIQUE INDEX IDX1 ON T1(I1,I3,I2) LOCAL;


--##############################
--+SECTOR; 파티션 키 개수 > 인덱스 키 개수
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE UNIQUE INDEX IDX1 ON T1(I1) LOCAL;


DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE UNIQUE INDEX IDX1 ON T1(I1, I2) LOCAL;


DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE UNIQUE INDEX IDX1 ON T1(I3) LOCAL;


DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE UNIQUE INDEX IDX1 ON T1(I2, I3) LOCAL;


--##############################
--+SECTOR; 파티션 키 개수 < 인덱스 키 개수
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE UNIQUE INDEX IDX1 ON T1(I1,I2) LOCAL;

DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1,I2)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE UNIQUE INDEX IDX1 ON T1(I1,I2,I3) LOCAL;


DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I3, I1)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE UNIQUE INDEX IDX1 ON T1(I3, I1, I2) LOCAL;


DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I3, I1)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE UNIQUE INDEX IDX1 ON T1(I1, I2, I3) LOCAL;

-- should be fail
CREATE UNIQUE INDEX IDX1 ON T1(I3, I2, I1) LOCAL;


--###################################################################
--+ SECTOR; 논프리픽스드 인덱스
--###################################################################
DROP TABLE T1;
CREATE TABLE T1
(
    I1   INTEGER,
    I2   INTEGER
) 
PARTITION BY RANGE( I1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;
INSERT INTO T1 VALUES( 35, 10 );
INSERT INTO T1 VALUES( 30, 15 );
INSERT INTO T1 VALUES( 25, 20 );
INSERT INTO T1 VALUES( 20, 25 );
INSERT INTO T1 VALUES( 15, 30 );
INSERT INTO T1 VALUES( 10, 35 );
INSERT INTO T1 VALUES( 5, 0 );
INSERT INTO T1 VALUES( 0, 5 );

CREATE INDEX IDX1 
ON T1( I2 ) LOCAL;

-- will be {10,15,20,25,30,35,0,5}
SELECT /*+ INDEX ASC ( T1, IDX1 ) */ I2
FROM T1;



--###################################################################
--+ SECTOR; 인덱스의 데이터 타입 체크
--###################################################################
--##############################
--+SECTOR; INTEGER
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE INDEX IDX1 ON T1(I1, I2) LOCAL;
-- should be success
CREATE INDEX IDX2 ON T1(I2, I1) LOCAL;
-- should be success
CREATE INDEX IDX3 ON T1(I3, I2, I1) LOCAL;

DROP INDEX IDX2;
CREATE INDEX IDX2 ON T1(I2, I1) LOCAL;

DROP INDEX IDX1;
DROP INDEX IDX3;

-- should be success
CREATE INDEX IDX3 ON T1(I1, I2) LOCAL;
-- should be success
CREATE INDEX IDX1 ON T1(I3, I2, I1) LOCAL;

--##############################
--+SECTOR; DATE
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 DATE, I2 DATE, I3 DATE )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN ( TO_DATE('2007-12-28', 'YYYY-MM-DD') ),
  PARTITION P2 VALUES LESS THAN ( TO_DATE('2008-12-28', 'YYYY-MM-DD') ),
  PARTITION P3 VALUES LESS THAN ( TO_DATE('2009-12-28', 'YYYY-MM-DD') ),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE INDEX IDX1 ON T1(I1, I2) LOCAL;
-- should be success
CREATE INDEX IDX2 ON T1(I2, I1) LOCAL;
-- should be success
CREATE INDEX IDX3 ON T1(I3, I2, I1) LOCAL;

--##############################
--+SECTOR; VARCHAR
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 VARCHAR(10), I2 VARCHAR(10), I3 VARCHAR(10) )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN ('ABC'),
  PARTITION P2 VALUES LESS THAN ('DEF'),
  PARTITION P3 VALUES LESS THAN ('GHI'),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE INDEX IDX1 ON T1(I1, I2) LOCAL;
-- should be success
CREATE INDEX IDX2 ON T1(I2, I1) LOCAL;
-- should be success
CREATE INDEX IDX3 ON T1(I3, I2, I1) LOCAL;

--##############################
--+SECTOR; INTEGER + DATE + VARCHAR
--##############################
DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 DATE, I3 VARCHAR(1000) )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be success
CREATE INDEX IDX1 ON T1(I1) LOCAL;
-- should be success
CREATE INDEX IDX2 ON T1(I2, I1) LOCAL;
-- should be success
CREATE INDEX IDX3 ON T1(I3, I1, I2) LOCAL;



--###################################################################
--+ SECTOR; 파티션드 인덱스의 TBS 지정 여부
--###################################################################
DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

DROP INDEX IDX1;
-- should be fail
CREATE INDEX IDX1 ON T1 (I1) LOCAL TABLESPACE PDT_TBS;



--###################################################################
--+ SECTOR; 인덱스 파티션 검사
--###################################################################
DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

DROP INDEX IDX1;
-- should be success
CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P1 ON P1,
  PARTITION IDX1_P2 ON P2,
  PARTITION IDX1_P3 ON P3,
  PARTITION IDX1_P4 ON P4 );

DROP INDEX IDX2;
-- should be success
CREATE INDEX IDX2 ON T1 (I3, I2, I1) LOCAL
( PARTITION IDX2_P1 ON P1,
  PARTITION IDX2_P2 ON P2,
  PARTITION IDX2_P3 ON P3,
  PARTITION IDX2_P4 ON P4 );

DROP INDEX IDX3;
-- should be fail
CREATE INDEX IDX3 ON T1 (I3, I2, I1) LOCAL
( PARTITION IDX2_P1 ON P1,
  PARTITION IDX2_P2 ON P2,
  PARTITION IDX2_P3 ON P3,
  PARTITION IDX2_P4 ON P4 );

DROP INDEX IDX3;
-- should be success
CREATE INDEX IDX3 ON T1 (I3, I1) LOCAL
( PARTITION IDX3_P1 ON P1,
  PARTITION IDX3_P2 ON P2,
  PARTITION IDX3_P3 ON P3,
  PARTITION IDX3_P4 ON P4 );

--##############################
--+SECTOR; 인덱스 파티션 이름 중복 검사
--##############################
-- should be fail
CREATE INDEX IDX4 ON T1 (I1, I2) LOCAL
( PARTITION IDX4_P1 ON P1,
  PARTITION IDX4_P3 ON P2,
  PARTITION IDX4_P3 ON P3,
  PARTITION IDX4_P4 ON P4 );

--##############################
--+SECTOR; 테이블 파티션 존재 여부 검사
--##############################
-- should be fail
CREATE INDEX IDX4 ON T1 (I1, I2) LOCAL
( PARTITION IDX4_P1 ON P1,
  PARTITION IDX4_P2 ON P2,
  PARTITION IDX4_P3 ON P5,
  PARTITION IDX4_P4 ON P4 );

--##############################
--+SECTOR; 테이블 파티션 이름 중복 검사
--##############################
-- should be fail
CREATE INDEX IDX4 ON T1 (I1, I2) LOCAL
( PARTITION IDX4_P1 ON P1,
  PARTITION IDX4_P2 ON P2,
  PARTITION IDX4_P3 ON P3,
  PARTITION IDX4_P4 ON P2 );

--##############################
--+SECTOR; 테이블스페이스 검사
--##############################
DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

-- should be success
CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P1 ON P1 TABLESPACE PDT_TBS2,
  PARTITION IDX1_P2 ON P2,
  PARTITION IDX1_P3 ON P3 TABLESPACE PDT_TBS3,
  PARTITION IDX1_P4 ON P4 );

-- Result: PDT_TBS2, PDT_TBS, PDT_TBS3, PDT_TBS5
SELECT D.NAME
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ A, 
     SYSTEM_.SYS_INDICES_ B, 
     SYSTEM_.SYS_TABLES_ C, 
     V$TABLESPACES D
WHERE A.TABLE_ID = B.TABLE_ID AND
      B.TABLE_ID = C.TABLE_ID AND
      A.TBS_ID = D.ID AND
      C.TABLE_NAME = 'T1'
ORDER BY A.INDEX_PARTITION_NAME ASC;


DROP INDEX IDX1;
-- should be fail
CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P1 ON P1 TABLESPACE PDT_TBS2,
  PARTITION IDX1_P2 ON P2,
  PARTITION IDX1_P3 ON P3 TABLESPACE SYS_TBS_DISK_TEMP,
  PARTITION IDX1_P4 ON P4 );

DROP INDEX IDX1;
-- should be fail
CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P1 ON P1 TABLESPACE SYS_TBS_DISK_UNDO,
  PARTITION IDX1_P2 ON P2,
  PARTITION IDX1_P3 ON P3,
  PARTITION IDX1_P4 ON P4 );

DROP INDEX IDX1;
-- should be fail
CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P1 ON P1 TABLESPACE PDT_TBS2,
  PARTITION IDX1_P2 ON P2 TABLESPACE SYS_TBS_MEM_DATA,
  PARTITION IDX1_P3 ON P3,
  PARTITION IDX1_P4 ON P4 );

DROP INDEX IDX1;
-- should be fail
CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P1 ON P1 TABLESPACE PDT_TBS2,
  PARTITION IDX1_P2 ON P2 TABLESPACE ABCDEFG,
  PARTITION IDX1_P3 ON P3,
  PARTITION IDX1_P4 ON P4 );

--##############################
--+SECTOR; 명시한 인덱스 파티션의 개수 체크
--##############################
DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

-- should be fail
CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P1 ON P1 TABLESPACE PDT_TBS2,
  PARTITION IDX1_P2 ON P2,
  PARTITION IDX1_P3 ON P3 TABLESPACE PDT_TBS3,
  PARTITION IDX1_P4 ON P4,
  PARTITION IDX1_P5 ON P5 );



--###################################################################
--+ SECTOR; 명시한 인덱스 파티션 개수
--###################################################################
DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

--##############################
--+SECTOR; 0개
--##############################
DROP INDEX IDX1;
-- should be success
CREATE INDEX IDX1 ON T1 (I1) LOCAL;

SELECT COUNT(DISTINCT A.INDEX_PARTITION_ID)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ A,
     SYSTEM_.SYS_TABLES_ B
WHERE A.TABLE_ID = B.TABLE_ID AND
      B.TABLE_NAME='T1';

-- Result: PDT_TBS, PDT_TBS, PDT_TBS, PDT_TBS5
SELECT D.PARTITION_NAME, E.NAME
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ A,
     SYSTEM_.SYS_INDICES_ B,
     SYSTEM_.SYS_TABLES_ C,
     SYSTEM_.SYS_TABLE_PARTITIONS_ D,
     V$TABLESPACES E
WHERE A.TABLE_ID = B.TABLE_ID AND
      B.TABLE_ID = C.TABLE_ID AND
      A.TABLE_PARTITION_ID = D.PARTITION_ID AND
      A.TBS_ID = E.ID AND
      C.TABLE_NAME = 'T1'
ORDER BY D.PARTITION_ID;


--##############################
--+SECTOR; 0 ~ (테이블파티션 개수-1)
--##############################
DROP INDEX IDX1;
-- should be success
CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P2 ON P2 TABLESPACE PDT_TBS2,
  PARTITION IDX1_P4 ON P4 TABLESPACE PDT_TBS3
);

SELECT A.INDEX_PARTITION_NAME
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ A,
     SYSTEM_.SYS_TABLES_ B
WHERE A.TABLE_ID = B.TABLE_ID AND
      B.TABLE_NAME='T1'
ORDER BY A.INDEX_PARTITION_ID;

-- Result: PDT_TBS, PDT_TBS2, PDT_TBS, PDT_TBS3
SELECT D.PARTITION_NAME, E.NAME
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ A,
     SYSTEM_.SYS_INDICES_ B,
     SYSTEM_.SYS_TABLES_ C,
     SYSTEM_.SYS_TABLE_PARTITIONS_ D,
     V$TABLESPACES E
WHERE A.TABLE_ID = B.TABLE_ID AND
      B.TABLE_ID = C.TABLE_ID AND
      A.TABLE_PARTITION_ID = D.PARTITION_ID AND
      A.TBS_ID = E.ID AND
      C.TABLE_NAME = 'T1'
ORDER BY D.PARTITION_ID;


--##############################
--+SECTOR; 테이블파티션 개수와 동일
--##############################
DROP INDEX IDX1;
-- should be success
CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P4 ON P4,
  PARTITION IDX1_P1 ON P1 TABLESPACE PDT_TBS2,
  PARTITION IDX1_P2 ON P2 TABLESPACE PDT_TBS3,
  PARTITION IDX1_P3 ON P3
);

SELECT A.INDEX_PARTITION_NAME
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ A,
     SYSTEM_.SYS_TABLES_ B
WHERE A.TABLE_ID = B.TABLE_ID AND
      B.TABLE_NAME='T1'
ORDER BY A.INDEX_PARTITION_ID;

-- Result: PDT_TBS2, PDT_TBS3, PDT_TBS, PDT_TBS5
SELECT A.INDEX_PARTITION_NAME, D.PARTITION_NAME, E.NAME
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ A,
     SYSTEM_.SYS_INDICES_ B,
     SYSTEM_.SYS_TABLES_ C,
     SYSTEM_.SYS_TABLE_PARTITIONS_ D,
     V$TABLESPACES E
WHERE A.TABLE_ID = B.TABLE_ID AND
      B.TABLE_ID = C.TABLE_ID AND
      A.TABLE_PARTITION_ID = D.PARTITION_ID AND
      A.TBS_ID = E.ID AND
      C.TABLE_NAME = 'T1'
ORDER BY D.PARTITION_ID;



--###################################################################
--+ SECTOR; 메타 테이블 체크
--###################################################################

DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE(I1, I2, I3)
( PARTITION P1 VALUES LESS THAN (100),
  PARTITION P2 VALUES LESS THAN (200),
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS5
) TABLESPACE PDT_TBS;

CREATE INDEX IDX1 ON T1 (I1) LOCAL
( PARTITION IDX1_P4 ON P4,
  PARTITION IDX1_P1 ON P1 TABLESPACE PDT_TBS2,
  PARTITION IDX1_P2 ON P2 TABLESPACE PDT_TBS3,
  PARTITION IDX1_P3 ON P3
);

--##############################
--+SECTOR; SYS_INDICES_
--##############################
SELECT A.TABLE_ID, A.INDEX_ID, A.INDEX_NAME, A.INDEX_TYPE, A.IS_UNIQUE,
       A.COLUMN_CNT, A.TBS_ID, A.IS_PARTITIONED,
       B.TABLE_NAME, B.TBS_ID, B.IS_PARTITIONED
FROM SYSTEM_.SYS_INDICES_ A, SYSTEM_.SYS_TABLES_ B
WHERE TABLE_NAME='T1' AND
      A.TABLE_ID = B.TABLE_ID
ORDER BY A.TABLE_ID;

--##############################
--+SECTOR; SYS_PART_INDICES_
--##############################
SELECT A.*
FROM SYSTEM_.SYS_PART_INDICES_ A, 
     SYSTEM_.SYS_INDICES_ B, 
     SYSTEM_.SYS_TABLES_ C
WHERE A.TABLE_ID = B.TABLE_ID
    AND B.TABLE_ID = C.TABLE_ID
    AND C.TABLE_NAME='T1'
ORDER BY A.TABLE_ID;

--##############################
--+SECTOR; SYS_INDEX_PARTITIONS_
--##############################
SELECT A.*
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ A, 
     SYSTEM_.SYS_INDICES_ B, 
     SYSTEM_.SYS_TABLES_ C
WHERE A.TABLE_ID = B.TABLE_ID
    AND B.TABLE_ID = C.TABLE_ID
    AND C.TABLE_NAME='T1'
ORDER BY B.TABLE_ID, A.TABLE_PARTITION_ID;

--##############################
--+SECTOR; SYS_PART_KEY_COLUMNS_
--##############################
SELECT A.PARTITION_OBJ_ID, A.OBJECT_TYPE, A.PART_COL_ORDER
FROM SYSTEM_.SYS_PART_KEY_COLUMNS_ A, 
     SYSTEM_.SYS_INDICES_ B, 
     SYSTEM_.SYS_TABLES_ C
WHERE A.PARTITION_OBJ_ID = B.INDEX_ID
    AND B.TABLE_ID = C.TABLE_ID
    AND C.TABLE_NAME='T1'
ORDER BY A.PARTITION_OBJ_ID, A.PART_COL_ORDER;



--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP INDEX IDX1;
DROP INDEX IDX2;
DROP INDEX IDX3;
--+SKIP END;
