#!/usr/local/bin/bash

############################################
# 환경 설정
############################################

#######################
# ATC_HOME, ATC_WORK 설정
#######################
export ATC_HOME=$ATAF_TEST_CASE
export ATC_WORK=$ATAF_TEST_RESULT/work
export PATH=$PATH:.:$ATC_HOME/scripts

#######################
# ATAF_RESULT_SUFFIX 설정
#######################
if [ "$ATAF_RESULT_SUFFIX" = "" ]
then
    bit_test=`altibase -v | awk '{ printf("%s ",$3); }' | grep 32bit`
    subString=`altibase -v | awk '{ printf("%s ",$3); }'`

    if [ "$bit_test" = "" ]
    then
    bit=64;
    else
    bit=32;
    fi
    export ATAF_RESULT_SUFFIX=_A4_${bit}
fi

#######################
# ATAF_ORACLE_SUFFIX 설정
#######################
if [ "$ATAF_ORACLE_SUFFIX" = "" ]
then
    oracleSuffix1=`echo $subString | awk -F_ '{ printf("%s",$1); printf("_"); printf("%s", $2); }'`
    oracleSuffix2=$ATAF_RESULT_SUFFIX

    if [ "$oracleSuffix1" = "XEON_LINUX" ]
    then
    oracleSuffix1="AMD64_LINUX"
    fi

    if [ "$bit" = "64" ]
    then
    real_oracleSuffix=`echo $oracleSuffix1 $HOSTNAME | awk '{printf("_A4_64"); printf(","); printf("_%s", $1); printf("_A4_64"); printf(","); printf("_%s", $2); printf("_A4_64"); }'`
    else
    real_oracleSuffix=`echo $oracleSuffix1 $HOSTNAME | awk '{printf("_A4_64"); printf(","); printf("_%s", $1); printf("_A4_64"); printf(","); printf("_%s", $2); printf("_A4_64"); printf(","); printf("_A4_32"); printf(","); printf("_%s", $1); printf("_A4_32");  printf(","); printf("_%s", $2); printf("_A4_32"); }'`
    fi

    export ATAF_ORACLE_SUFFIX=$real_oracleSuffix
fi

############################################
# MAIN
############################################
if [ "$LANG" = "" ]
then
echo "Please set environment variable LANG"
exit
fi

lang=$LANG

if [ $# -eq 1 ]
then
    CommonCase=$1
    MyCase=$1
    SkipCase=none
    ArgCnt=1
elif [ $# -eq 2 ]
then
    CommonCase=$1
    MyCase=$2
    SkipCase=none
    ArgCnt=2
elif [ $# -eq 3 ]
then
    if [ $2 == "--skip" ]
    then
        CommonCase=$1
        MyCase=$1
        SkipCase=$3
        ArgCnt=1
    else
       echo "Usage: atsclnt CommonCase --skip SkipCase"
       echo ""
       exit
    fi
else
    echo "[ USAGE ]"
    echo "Usage: atsclnt CommonCase [MyCase]"
    echo ""
    exit
fi

unset  LC_CTYPE
export LC_ALL=C

rm -rf $ATAF_TEST_RESULT/work &> /dev/null
mkdir -p $ATAF_TEST_RESULT/work/log &> /dev/null
altibase -v > $ATAF_TEST_RESULT/work/altibase.info

if [ "$ATAF_TEST_CASE" != "$ATAF_TEST_RESULT" ]
then

old_pwd=`pwd`
mkdir -p $ATAF_TEST_RESULT/src
cp -r $ATAF_TEST_CASE/src/ses $ATAF_TEST_RESULT/src/ses &> /dev/null
cp -r $ATAF_TEST_CASE/include $ATAF_TEST_RESULT/include &> /dev/null
cd $ATAF_TEST_RESULT/src/ses && make clean &> /dev/null
cd $ATAF_TEST_RESULT/src/ses && make &> /dev/null
cd $old_pwd

fi

####################################
# set default properties
####################################
${ALTIBASE_HOME}/bin/is -atc -silent -f $ATAF_TEST_CASE/scripts/system-default-properties.sql &> /dev/null

time atsc -c $CommonCase -m $MyCase -l $lang -n $ArgCnt -i $SkipCase 2> $ATAF_TEST_RESULT/work/log/exception.log

ps -ef | grep "./serverkill.sh" |  awk '{print $2}' | xargs -n1 kill -9 &> /dev/null
