--###################################################################
--# CREATE TABLE TEST
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
DROP USER YNKANG CASCADE;
--+SKIP END;
CREATE USER YNKANG IDENTIFIED BY YNKANG DEFAULT TABLESPACE PDT_TBS3;
GRANT ALL PRIVILEGES TO YNKANG;

ALTER SESSION SET DEFAULT_DATE_FORMAT='DD-MON-RRRR';


--###################################################################
--+ SECTOR; 파싱 검사
--###################################################################

--##############################
--+SECTOR; 기본 파티션 개수 체크
--##############################
DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (0);
INSERT INTO T1 VALUES (100);
INSERT INTO T1 VALUES (150);
INSERT INTO T1 VALUES (200);
INSERT INTO T1 VALUES (250);
INSERT INTO T1 VALUES (300);
INSERT INTO T1 VALUES (350);

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

DROP TABLE T1;
-- should be fail
CREATE TABLE T1 ( I1 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be fail
CREATE TABLE T1 ( I1 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2 VALUES DEFAULT,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;


--##############################
--+SECTOR; MAXROWS 사용 유무 체크
--##############################
DROP TABLE T1;
-- should be fail
CREATE TABLE T1 ( I1 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) MAXROWS 1000 TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be fail
CREATE TABLE T1 ( I1 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS MAXROWS 1000;

DROP TABLE T1;
-- should be fail
CREATE TABLE T1 ( I1 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1 MAXROWS 100,
  PARTITION P2 MAXROWS 100,
  PARTITION P3 MAXROWS 100,
  PARTITION P4 MAXROWS 100
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be fail
CREATE TABLE T1 ( I1 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1 MAXROWS 100,
  PARTITION P2 MAXROWS 100,
  PARTITION P3 MAXROWS 100,
  PARTITION P4 MAXROWS 100
) MAXROWS 1000 TABLESPACE PDT_TBS;



--##################################################################
--+SECTOR; 파티션 키 컬럼에 대한 검사
--##################################################################
--##############################
--+SECTOR; 파티션 키 컬럼이 테이블에 존재하는 컬럼인지 체크
--##############################
DROP TABLE T1;
--should be fail
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY HASH (I4)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

--##############################
--+SECTOR; 파티션 키 컬럼의 데이터 타입이 대소 비교 가능한 타입인지 체크
--##############################
DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 BIGINT, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 BIT(10), I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be fail
CREATE TABLE T1 ( I1 BLOB, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 BYTE, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be fail
CREATE TABLE T1 ( I1 CLOB, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 DATE, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 DOUBLE, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 FLOAT, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 NIBBLE, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 NUMBER, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 NUMERIC, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 REAL, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 SMALLINT, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 VARBIT, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 VARCHAR, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

--##############################
--+SECTOR; 파티션 키 컬럼 개수 체크
--##############################
DROP TABLE T1;
-- should be fail 
CREATE TABLE T1 ( 
    I1     INTEGER, 
    I2     INTEGER
)
PARTITION BY HASH (I1, I2)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;



--##################################################################
--+SECTOR; 각 파티션에 대한 검사
--##################################################################
--##############################
--+SECTOR; 파티션 이름 중복 검사
--##############################
DROP TABLE T1;
-- should be fail
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P4,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;



--##############################
--+SECTOR; 파티션 키 조건 값 검사(상수)
--##############################
DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 INTEGER )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (0);
INSERT INTO T1 VALUES (100);
INSERT INTO T1 VALUES (150);
INSERT INTO T1 VALUES (200);
INSERT INTO T1 VALUES (250);
INSERT INTO T1 VALUES (300);
INSERT INTO T1 VALUES (350);

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


DROP TABLE T1;
-- should be success
-- integer: ~ 2147483647
CREATE TABLE T1 ( I1 BIGINT )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (0);
INSERT INTO T1 VALUES (2147483648);
INSERT INTO T1 VALUES (2947483648);
INSERT INTO T1 VALUES (3147483648);
INSERT INTO T1 VALUES (3947483648);
INSERT INTO T1 VALUES (4147483648);
INSERT INTO T1 VALUES (4947483648);

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 BIT(10) )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (BIT'0000000000');
INSERT INTO T1 VALUES (BIT'1010101010');
INSERT INTO T1 VALUES (BIT'1010101011');
INSERT INTO T1 VALUES (BIT'1010101110');
INSERT INTO T1 VALUES (BIT'1010101111');
INSERT INTO T1 VALUES (BIT'1010111010');
INSERT INTO T1 VALUES (BIT'1010111011');

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 BYTE(10) )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES ('0000000000');
INSERT INTO T1 VALUES ('1010101010');
INSERT INTO T1 VALUES ('1010101011');
INSERT INTO T1 VALUES ('1010101110');
INSERT INTO T1 VALUES ('1010101111');
INSERT INTO T1 VALUES ('1010111010');
INSERT INTO T1 VALUES ('1010111011');

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 DATE )
PARTITION BY HASH ( I1 )
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (TO_DATE('2007-01-01', 'YYYY-MM-DD'));
INSERT INTO T1 VALUES (TO_DATE('2007-04-01', 'YYYY-MM-DD'));
INSERT INTO T1 VALUES (TO_DATE('2007-04-30', 'YYYY-MM-DD'));
INSERT INTO T1 VALUES (TO_DATE('2007-05-01', 'YYYY-MM-DD'));
INSERT INTO T1 VALUES (TO_DATE('2007-05-30', 'YYYY-MM-DD'));
INSERT INTO T1 VALUES (TO_DATE('2007-06-01', 'YYYY-MM-DD'));
INSERT INTO T1 VALUES (TO_DATE('2007-07-01', 'YYYY-MM-DD'));

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 DOUBLE )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (0);
INSERT INTO T1 VALUES (123.456);
INSERT INTO T1 VALUES (193.456);
INSERT INTO T1 VALUES (223.456);
INSERT INTO T1 VALUES (293.456);
INSERT INTO T1 VALUES (323.456);
INSERT INTO T1 VALUES (393.456);

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 FLOAT )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (0);
INSERT INTO T1 VALUES (123.456);
INSERT INTO T1 VALUES (193.456);
INSERT INTO T1 VALUES (223.456);
INSERT INTO T1 VALUES (293.456);
INSERT INTO T1 VALUES (323.456);
INSERT INTO T1 VALUES (393.456);

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);

DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 NIBBLE(10) )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES ('0000000000');
INSERT INTO T1 VALUES ('1010101010');
INSERT INTO T1 VALUES ('1010101011');
INSERT INTO T1 VALUES ('1010101110');
INSERT INTO T1 VALUES ('1010101111');
INSERT INTO T1 VALUES ('1010111010');
INSERT INTO T1 VALUES ('1010111011');

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 NUMERIC)
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (0);
INSERT INTO T1 VALUES (123.456);
INSERT INTO T1 VALUES (193.456);
INSERT INTO T1 VALUES (223.456);
INSERT INTO T1 VALUES (293.456);
INSERT INTO T1 VALUES (323.456);
INSERT INTO T1 VALUES (393.456);

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 REAL )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (0);
INSERT INTO T1 VALUES (123.456);
INSERT INTO T1 VALUES (193.456);
INSERT INTO T1 VALUES (223.456);
INSERT INTO T1 VALUES (293.456);
INSERT INTO T1 VALUES (323.456);
INSERT INTO T1 VALUES (393.456);

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 SMALLINT)
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES (0);
INSERT INTO T1 VALUES (100);
INSERT INTO T1 VALUES (150);
INSERT INTO T1 VALUES (200);
INSERT INTO T1 VALUES (250);
INSERT INTO T1 VALUES (300);
INSERT INTO T1 VALUES (350);

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);


DROP TABLE T1;
-- should be success
CREATE TABLE T1 ( I1 VARCHAR(10) )
PARTITION BY HASH (I1)
( PARTITION P1,
  PARTITION P2,
  PARTITION P3,
  PARTITION P4
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (NULL);
INSERT INTO T1 VALUES ('0');
INSERT INTO T1 VALUES ('AAAAA');
INSERT INTO T1 VALUES ('ABAAA');
INSERT INTO T1 VALUES ('BBBBB');
INSERT INTO T1 VALUES ('BCBBB');
INSERT INTO T1 VALUES ('CCCCC');
INSERT INTO T1 VALUES ('CDCCC');

SELECT COUNT(*) FROM T1 PARTITION (P1);
SELECT COUNT(*) FROM T1 PARTITION (P2);
SELECT COUNT(*) FROM T1 PARTITION (P3);
SELECT COUNT(*) FROM T1 PARTITION (P4);



--##################################################################
--+SECTOR; DISTRIBUTION
--##################################################################
DROP TABLE T1;
CREATE TABLE T1
(
    I1   INTEGER,
    I2   INTEGER
)
PARTITION BY HASH( I1 )
(
    PARTITION P1,
    PARTITION P2,
    PARTITION P3,
    PARTITION P4
) TABLESPACE PDT_TBS;

CREATE OR REPLACE PROCEDURE PROC_INSERT( FROM_IDX IN INTEGER,
                                         TO_IDX   IN INTEGER )
AS
BEGIN
    FOR I IN FROM_IDX .. TO_IDX LOOP
        INSERT INTO T1 VALUES ( I, I );
    END LOOP;
END;
/

EXECUTE PROC_INSERT( 1, 10000 );

SELECT COUNT(*) FROM T1 PARTITION( P1 );
SELECT COUNT(*) FROM T1 PARTITION( P2 );
SELECT COUNT(*) FROM T1 PARTITION( P3 );
SELECT COUNT(*) FROM T1 PARTITION( P4 );



--##################################################################
--+SECTOR; FINALIZATION
--##################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP PROCEDURE PROC_INSERT;
DROP USER YNKANG CASCADE;
--+SKIP END;
