#!/bin/sh
#
# ALTIBASE Server Startup/Shutdown Script
#
# $Id: server 59306 2013-04-08 08:00:35Z donlet $

ADMIN="${ALTIBASE_HOME}/bin/isql -u sys -p manager -sysdba -noprompt"
ISQL="${ALTIBASE_HOME}/bin/isql -s localhost -u sys -p manager -silent"

# TASK-5894 Permit sysdba via IPC
FUNC_CHECK_ISQL_CONN()
{
	case $ISQL_CONNECTION in
		[Ii][Pp][Cc])
		unset ISQL_CONNECTION
		;;

		*)
		;;
	esac
}

if [ "$1" = "status" ]; then
	MODE=`echo $* | cut -f 2-4 -d ' '`
	if [ "$MODE" = "status" ]; then
		MODE=
	fi
fi

case "$1" in
'start')
# for window natc
    if [ -f ${ALTIBASE_HOME}/bin/chkFileLock ]; then
        chkFileLock >> ${ALTIBASE_HOME}/flock.log
    fi
	${ADMIN} << EOF
startup
quit
EOF
	;;

'stop')
	# TASK-5894 Permit sysdba via IPC
	FUNC_CHECK_ISQL_CONN

	${ADMIN} << EOF > /dev/null
ALTER SYSTEM SET CHECKPOINT_BULK_WRITE_PAGE_COUNT = 0;
ALTER SYSTEM SET CHECKPOINT_BULK_WRITE_SLEEP_SEC  = 0;
ALTER SYSTEM SET CHECKPOINT_BULK_WRITE_SLEEP_USEC = 0;
quit;
EOF
	killCheckServer > ${ALTIBASE_HOME}/trc/killCheckServer.log 2>&1
	${ADMIN} << EOF
shutdown immediate;
quit;
EOF
	;;
'kill')
	${ADMIN} << EOF
shutdown abort
quit
EOF
	;;
'status')
	${ADMIN} << EOF
select * from tab;
quit
EOF

    ;;
'create')
if [ $# = 3 ]; then
    rm -f live-altibase.txt;
    ${ISQL}  << EOF > /dev/null
spool  live-altibase.txt;
EOF
    if [ -f live-altibase.txt ]; then
        echo " server is running !!!! \n "
        echo " you must shutdown first before server create " 
        rm -f live-altibase.txt;
    else
	    ${ADMIN} << EOF
startup process;
create database mydb INITSIZE=10M noarchivelog character set $2 national character set $3;
quit
EOF
        ${ADMIN} << EOF > /dev/null
ALTER SYSTEM SET CHECKPOINT_BULK_WRITE_PAGE_COUNT = 0;
ALTER SYSTEM SET CHECKPOINT_BULK_WRITE_SLEEP_SEC  = 0;
ALTER SYSTEM SET CHECKPOINT_BULK_WRITE_SLEEP_USEC = 0;
shutdown abort;
quit;
EOF
fi
else
echo "Usage: server create [DB Character-set] [National Character-set]"
exit 1
fi
	;;
'restart')
	# TASK-5894 Permit sysdba via IPC
	FUNC_CHECK_ISQL_CONN

	${ADMIN} << EOF > /dev/null
ALTER SYSTEM SET CHECKPOINT_BULK_WRITE_PAGE_COUNT = 0;
ALTER SYSTEM SET CHECKPOINT_BULK_WRITE_SLEEP_SEC  = 0;
ALTER SYSTEM SET CHECKPOINT_BULK_WRITE_SLEEP_USEC = 0;
quit
EOF
        ${ADMIN} << EOF
shutdown immediate
quit
EOF
	${ADMIN} << EOF
startup
quit
EOF
	;;
*)
	echo "Usage: server { start | stop | kill | status | create db_charset national_charset | restart }"
	exit 1
	;;
esac
exit 0
