###############################################################################
# 테스트 프로퍼티 
###############################################################################
__FORCE_COMPRESSION_COLUMN=1
__FORCE_PARALLEL_DEGREE=3
__FORCE_EXECUTION_CACHE=1
__FORCE_INDEX_DIRECTKEY=1
__MEM_BTREE_DEFAULT_MAX_KEY_SIZE=24
#add  20150803 kimhyun
RESULT_CACHE_ENABLE=1
TOP_RESULT_CACHE_MODE=0
#add related Ager property kimhyun 20150924
MAX_LOGICAL_AGER_COUNT=10
MIN_LOGICAL_AGER_COUNT=1
LOGICAL_AGER_COUNT_=3
DELETE_AGER_COUNT_=3
#DELETE_AGER_COMMIT_INTERVAL=1
__SM_AGER_DISABLE=0
__PARELLEL_LOGICAL_AGER=1
#add 20151112 by kimjina
FAST_UNLOCK_LOG_ALLOC_MUTEX=1
