--######################################################
-- INDEX LOCAL PARTITIOIN ON RANGE PDT( PK:INTEGER )
--######################################################

--###################################
--+SECTOR; INTIALIZE
--###################################

--+SKIP BEGIN;
DROP TABLE PDT_RANGE;
--+SKIP END;


--#########################################
--+SECTOR; DO JOB #1 (1. Basic Test)
--#########################################

----------------------------------------
-- 2.1 CREATING INDEX USING CREATE_TABLE
----------------------------------------
CREATE TABLE PDT_RANGE
(
    F1   INTEGER PRIMARY KEY,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;
INSERT INTO PDT_RANGE VALUES( 35, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );
INSERT INTO PDT_RANGE VALUES( 25, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 15, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 5, 0 );
INSERT INTO PDT_RANGE VALUES( 0, 0 );

-- should be {0}
SELECT F1 FROM PDT_RANGE
WHERE F1 >= 0 LIMIT 1;

----------------------------------------
-- 2.2 CREATING INDEX USING CREATE_INDEX
----------------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;
INSERT INTO PDT_RANGE VALUES( 35, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );
INSERT INTO PDT_RANGE VALUES( 25, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 15, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 5, 0 );
INSERT INTO PDT_RANGE VALUES( 0, 0 );

-- should be {5}
SELECT F1 FROM PDT_RANGE PARTITION( P1 ) LIMIT 1;

CREATE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL;

-- should be {0}
SELECT /*+ INDEX ASC ( PDT_RANGE, IDX_LOCAL ) */ F1
FROM PDT_RANGE PARTITION( P1 ) LIMIT 1;

--#########################################
--+SECTOR; DO JOB #2 (2. Validation Test)
--#########################################

----------------------------
-- 2.1 파티셔너블 객체 검사 
----------------------------
CREATE TABLE T
(
    F1   INTEGER,
    F2   INTEGER
);
-- should be fail
CREATE INDEX IDX_LOCAL 
ON T( F1 ) LOCAL;

-----------------------------------
-- 2.2 유니크 인덱스 생성 여부 검사 
-----------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE UNIQUE INDEX IDX_LOCAL 
ON PDT_RANGE( F2 ) LOCAL;

-----------------------------------
-- 2.3 인덱스 파티션 개수 검사 
-----------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL
(
    PARTITION IDX_P1 ON P1,
    PARTITION IDX_P2 ON P2,
    PARTITION IDX_P3 ON P3,
    PARTITION IDX_P4 ON P4,
    PARTITION IDX_P5 ON P5
);

-- should be fail
CREATE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL
(
    PARTITION IDX_P1 ON P1,
    PARTITION IDX_P5 ON P5
);

-- should be success
CREATE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL
(
    PARTITION IDX_P1 ON P1
);

-----------------------------------
-- 2.4 인덱스 이름 중복 검사
-----------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- should be fail
CREATE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL
(
    PARTITION IDX_P1 ON P1,
    PARTITION IDX_P2 ON P2,
    PARTITION IDX_P3 ON P2,
    PARTITION IDX_P4 ON P4
);

-- should be fail
CREATE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL
(
    PARTITION IDX_P1 ON P1,
    PARTITION IDX_P2 ON P2,
    PARTITION IDX_P2 ON P3,
    PARTITION IDX_P4 ON P4
);


-----------------------------------
-- 2.5 테이블스페이스 검사 
-----------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

-- memory tablespace
-- should be fail
CREATE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL
(
    PARTITION IDX_P1 ON P1 TABLESPACE SYS_TBS_MEM_DATA
);

-- should be fail
-- temporary tablespace
CREATE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL
(
    PARTITION IDX_P1 ON P1 TABLESPACE SYS_TBS_TEMP
);

-- should be fail
-- undo tablespace
CREATE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL
(
    PARTITION IDX_P1 ON P1 TABLESPACE SYS_TBS_UNDO
);

--#########################################
--+SECTOR; DO JOB #3 (3. Execution Test)
--#########################################

-----------------------------------------
-- 3.1 Preserved Order(프리픽스드 인덱스)
-----------------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;
INSERT INTO PDT_RANGE VALUES( 35, 0 );
INSERT INTO PDT_RANGE VALUES( 30, 0 );
INSERT INTO PDT_RANGE VALUES( 25, 0 );
INSERT INTO PDT_RANGE VALUES( 20, 0 );
INSERT INTO PDT_RANGE VALUES( 15, 0 );
INSERT INTO PDT_RANGE VALUES( 10, 0 );
INSERT INTO PDT_RANGE VALUES( 5, 0 );
INSERT INTO PDT_RANGE VALUES( 0, 0 );

CREATE UNIQUE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL;

-- should be {0,5,10,15,20,25,30,35}
SELECT /*+ INDEX ASC ( PDT_RANGE, IDX_LOCAL ) */ F1
FROM PDT_RANGE;

-----------------------------------------------
-- 3.2 Non-Preserved Order(논프리픽스드 인덱스)
-----------------------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;
INSERT INTO PDT_RANGE VALUES( 35, 10 );
INSERT INTO PDT_RANGE VALUES( 30, 15 );
INSERT INTO PDT_RANGE VALUES( 25, 20 );
INSERT INTO PDT_RANGE VALUES( 20, 25 );
INSERT INTO PDT_RANGE VALUES( 15, 30 );
INSERT INTO PDT_RANGE VALUES( 10, 35 );
INSERT INTO PDT_RANGE VALUES( 5, 0 );
INSERT INTO PDT_RANGE VALUES( 0, 5 );

CREATE UNIQUE INDEX IDX_LOCAL 
ON PDT_RANGE( F2 ) LOCAL;

-- will be {10,15,20,25,30,35,0,5}
SELECT /*+ INDEX ASC ( PDT_RANGE, IDX_LOCAL ) */ F2
FROM PDT_RANGE;

-----------------------------------------
-- 3.3 Unique violation
-----------------------------------------
DROP TABLE PDT_RANGE;
CREATE TABLE PDT_RANGE
(
    F1   INTEGER,
    F2   INTEGER
) 
PARTITION BY RANGE( F1 )
(
    PARTITION P1 VALUES LESS THAN ( 10 ),
    PARTITION P2 VALUES LESS THAN ( 20 ),
    PARTITION P3 VALUES LESS THAN ( 30 ),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;
INSERT INTO PDT_RANGE VALUES( 35, 10 );
INSERT INTO PDT_RANGE VALUES( 30, 15 );
INSERT INTO PDT_RANGE VALUES( 25, 20 );
INSERT INTO PDT_RANGE VALUES( 20, 25 );
INSERT INTO PDT_RANGE VALUES( 15, 30 );
INSERT INTO PDT_RANGE VALUES( 10, 35 );
INSERT INTO PDT_RANGE VALUES( 5, 0 );
INSERT INTO PDT_RANGE VALUES( 0, 5 );

CREATE UNIQUE INDEX IDX_LOCAL 
ON PDT_RANGE( F1 ) LOCAL;

-- should be fail
INSERT INTO PDT_RANGE VALUES( 35, 10 );
-- should be fail
INSERT INTO PDT_RANGE VALUES( 30, 15 );
-- should be fail
INSERT INTO PDT_RANGE VALUES( 25, 20 );
-- should be fail
INSERT INTO PDT_RANGE VALUES( 20, 25 );
-- should be fail
INSERT INTO PDT_RANGE VALUES( 15, 30 );
-- should be fail
INSERT INTO PDT_RANGE VALUES( 10, 35 );
-- should be fail
INSERT INTO PDT_RANGE VALUES( 5, 0 );
-- should be fail
INSERT INTO PDT_RANGE VALUES( 0, 5 );

ALTER TABLE PDT_RANGE
ENABLE ROW MOVEMENT;

-- should be fail
UPDATE PDT_RANGE SET F1 = 20
WHERE F1 = 30;

--###################################
--+SECTOR; FINALIZE
--###################################

DROP TABLE PDT_RANGE;
