--###################################################################
--# ALTER TABLE ... ADD COLUMN
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

CREATE TABLE T1( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE (I1)
(
    PARTITION P1 VALUES LESS THAN (100) TABLESPACE PDT_TBS2,
    PARTITION P2 VALUES LESS THAN (200) TABLESPACE PDT_TBS3,
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE PDT_TBS;

INSERT INTO T1 VALUES (0, 100, 100);
INSERT INTO T1 VALUES (50, 100, 100);
INSERT INTO T1 VALUES (100, 100, 100);
INSERT INTO T1 VALUES (150, 100, 100);
INSERT INTO T1 VALUES (200, 100, 100);
INSERT INTO T1 VALUES (250, 100, 100);
INSERT INTO T1 VALUES (300, 100, 100);
INSERT INTO T1 VALUES (350, 100, 100);


CREATE TABLE T2( I1 INTEGER, I2 INTEGER, I3 INTEGER )
PARTITION BY RANGE (I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100) TABLESPACE PDT_TBS2,
    PARTITION P2 VALUES LESS THAN (200) TABLESPACE PDT_TBS3,
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT TABLESPACE PDT_TBS4
) TABLESPACE PDT_TBS;

INSERT INTO T2 VALUES (0, 100, 100);
INSERT INTO T2 VALUES (50, 100, 100);
INSERT INTO T2 VALUES (100, 100, 100);
INSERT INTO T2 VALUES (150, 100, 100);
INSERT INTO T2 VALUES (200, 100, 100);
INSERT INTO T2 VALUES (250, 100, 100);
INSERT INTO T2 VALUES (300, 100, 100);
INSERT INTO T2 VALUES (350, 100, 100);

CREATE INDEX IDX1 ON T2(I1, I3);
CREATE INDEX IDX2 ON T2(I3, I1, I2);
CREATE INDEX IDX3 ON T2(I2, I3);

CREATE INDEX IDX4 ON T2(I1) LOCAL
(
    PARTITION IDX1_P3 ON P3,
    PARTITION IDX1_P4 ON P4
);


--###################################################################
--+ SECTOR; BASIC TEST
--###################################################################

ALTER TABLE T1 ADD COLUMN ( I4 INTEGER );
INSERT INTO T1 VALUES ( 1,1,1,1 );
INSERT INTO T1 VALUES ( 2,2,2,2 );
ALTER TABLE T1 DROP COLUMN I4;


ALTER TABLE T2 ADD COLUMN ( I4 INTEGER );
INSERT INTO T2 VALUES ( 1,1,1,1 );
INSERT INTO T2 VALUES ( 2,2,2,2 );
ALTER TABLE T2 DROP COLUMN I4;


--#########################################################################
--+ SECTOR; PARSING + VALIDATION
--#########################################################################
---------------------------------------------------
-- 문법 체크
---------------------------------------------------
-- should be fail
ALTER TABLE T1 ADD COLUMN ( I4 INTEGER )
(
    PARTITION P1,
    PARTITION P2
);

-- should be fail
ALTER TABLE T1 ADD COLUMN ( I4 INTEGER )
(
    PARTITION P1 TABLESPACE PDT_TBS LOB STORE AS ( TABLESPACE PDT_TBS2 ),
    PARTITION P2 LOB STORE AS ( TABLESPACE PDT_TBS3 )
);


---------------------------------------------------
-- 파티션드 테이블인지 체크
---------------------------------------------------
--+SKIP BEGIN;
DROP TABLE TEST;
--+SKIP END;

CREATE TABLE TEST ( I1 INTEGER, I2 BLOB );

-- should be fail
ALTER TABLE TEST ADD COLUMN ( I4 INTEGER )
(
    PARTITION P1 LOB STORE AS ( BUFFER ),
    PARTITION P2 LOB STORE AS ( LOGGING )
);

--+SKIP BEGIN;
DROP TABLE TEST;
--+SKIP END;

---------------------------------------------------
-- 해당 파티션이 존재하는지 체크
---------------------------------------------------
-- should be fail
ALTER TABLE T1 ADD COLUMN ( I4 INTEGER, I5 BLOB )
(
    PARTITION P1 LOB STORE AS ( TABLESPACE PDT_TBS2 ),
    PARTITION P5 LOB STORE AS ( TABLESPACE PDT_TBS3 ),
    PARTITION P3 LOB STORE AS ( TABLESPACE PDT_TBS4 )
);

---------------------------------------------------
-- LOB 컬럼이 있는지 체크
---------------------------------------------------
-- should be fail
ALTER TABLE T1 ADD COLUMN ( I4 INTEGER, I5 INTEGER )
(
    PARTITION P1 LOB STORE AS ( TABLESPACE PDT_TBS2 ),
    PARTITION P3 LOB STORE AS ( TABLESPACE PDT_TBS3 ),
    PARTITION P4 LOB STORE AS ( TABLESPACE PDT_TBS4 )
);

---------------------------------------------------
-- LOB 컬럼 지정이 잘못된 경우
---------------------------------------------------
-- should be fail
ALTER TABLE T1 ADD COLUMN ( I4 BLOB, I5 INTEGER, I6 CLOB )
(
    PARTITION P1 LOB STORE AS ( TABLESPACE PDT_TBS2 ),
    PARTITION P3 LOB(I6, I5) STORE AS ( TABLESPACE PDT_TBS3 ),
    PARTITION P4 LOB(I4) STORE AS ( TABLESPACE PDT_TBS4 )
);



--###################################################################
--+ SECTOR; LOB COLUMN TEST
--###################################################################
DROP TABLE T1;

--#         I1          I2          I3
--# P1   PDT_TBS     PDT_TBS2    PDT_TBS2
--# P2   PDT_TBS3    PDT_TBS3    PDT_TBS5
--# P3   PDT_TBS4    PDT_TBS4    PDT_TBS5
CREATE TABLE T1 ( I1 INTEGER, I2 BLOB, I3 CLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (50) TABLESPACE PDT_TBS
                                    LOB(I2, I3) STORE AS ( TABLESPACE PDT_TBS2 ), 
  PARTITION P2 VALUES LESS THAN (100) TABLESPACE PDT_TBS3,
  PARTITION P3 VALUES DEFAULT
) TABLESPACE PDT_TBS4 LOB(I3) STORE AS ( TABLESPACE PDT_TBS5 );

INSERT INTO T1 VALUES ( 0,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 1,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 2,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 3,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 4,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 5,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 50,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 51,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 52,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 53,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 54,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 55,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 100,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 101,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 102,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 103,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 104,   'ABC', 'DEF' );
INSERT INTO T1 VALUES ( 105,   'ABC', 'DEF' );

CREATE INDEX IDX5 ON T1(I1) LOCAL; 


--##############################
--+SECTOR; INTEGER
--##############################
ALTER TABLE T1 ADD COLUMN ( I4 INTEGER );

INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 1 );
INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 1 );

ALTER TABLE T1 DROP COLUMN I4;

--##############################
--+SECTOR; BLOB
--##############################
--###############
--# 파티션드 테이블에 LOB 컬럼 지정
--###############
ALTER TABLE T1 ADD COLUMN ( I4 BLOB  )
LOB (I4) STORE AS ( TABLESPACE PDT_TBS5 );

INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF' );
INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF' );


-- Result: PDT_TBS2, PDT_TBS2, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P1'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS3, PDT_TBS5, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P2'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS4, PDT_TBS5, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P3'
ORDER BY LOBS.COLUMN_ID ASC;

ALTER TABLE T1 DROP COLUMN I4;


--###############
--# 각 파티션 별 LOB 컬럼 지정
--###############
ALTER TABLE T1 ADD COLUMN ( I4 BLOB  )
LOB STORE AS ( TABLESPACE PDT_TBS2 )
(
    PARTITION P3 LOB STORE AS ( TABLESPACE PDT_TBS3 ),
    PARTITION P2 LOB (I4) STORE AS ( TABLESPACE PDT_TBS4 )
);

INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF' );
INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF' );


-- Result: PDT_TBS2, PDT_TBS2, PDT_TBS2
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P1'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS3, PDT_TBS5, PDT_TBS4
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P2'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS4, PDT_TBS5, PDT_TBS3
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P3'
ORDER BY LOBS.COLUMN_ID ASC;

ALTER TABLE T1 DROP COLUMN I4;


--##############################
--+SECTOR; BLOB + INTEGER + BLOB
--##############################
--###############
--# 모든 파티션 지정
--###############
ALTER TABLE T1 ADD COLUMN ( I4 BLOB, I5 INTEGER, I6 BLOB )
(
    PARTITION P1 LOB STORE AS ( TABLESPACE PDT_TBS3  ),
    PARTITION P2 LOB (I6) STORE AS ( TABLESPACE PDT_TBS4 ),
    PARTITION P3 LOB (I4) STORE AS ( TABLESPACE PDT_TBS5 )
);

INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF', 222, 'EEE' );
INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF', 222, 'EEE' );


-- Result: PDT_TBS2, PDT_TBS2, PDT_TBS3, PDT_TBS3
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P1'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS3, PDT_TBS5, PDT_TBS3, PDT_TBS4
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P2'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS4, PDT_TBS5, PDT_TBS5, PDT_TBS4
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P3'
ORDER BY LOBS.COLUMN_ID ASC;

ALTER TABLE T1 DROP COLUMN I4;
ALTER TABLE T1 DROP COLUMN I5;
ALTER TABLE T1 DROP COLUMN I6;


--###############
--# 일부 파티션 지정
--###############
ALTER TABLE T1 ADD COLUMN ( I4 BLOB, I5 INTEGER, I6 BLOB )
(
    PARTITION P1 LOB STORE AS ( TABLESPACE PDT_TBS4  ),
    PARTITION P3 LOB (I6) STORE AS ( TABLESPACE PDT_TBS5 )
);

INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF', 222, 'EEE' );
INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF', 222, 'EEE' );


-- Result: PDT_TBS2, PDT_TBS2, PDT_TBS4, PDT_TBS4
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P1'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS3, PDT_TBS5, PDT_TBS3, PDT_TBS3
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P2'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS4, PDT_TBS5, PDT_TBS4, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P3'
ORDER BY LOBS.COLUMN_ID ASC;

ALTER TABLE T1 DROP COLUMN I4;
ALTER TABLE T1 DROP COLUMN I5;
ALTER TABLE T1 DROP COLUMN I6;


--###############
--# 파티션드 테이블에도 LOB 컬럼 지정
--###############
ALTER TABLE T1 ADD COLUMN ( I4 BLOB, I5 INTEGER, I6 BLOB )
LOB (I4) STORE AS ( TABLESPACE PDT_TBS3 )
(
    PARTITION P1 LOB STORE AS ( TABLESPACE PDT_TBS4  ),
    PARTITION P3 LOB (I6) STORE AS ( TABLESPACE PDT_TBS5 )
);

INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF', 222, 'EEE' );
INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF', 222, 'EEE' );


-- Result: PDT_TBS2, PDT_TBS2, PDT_TBS4, PDT_TBS4
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P1'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS3, PDT_TBS5, PDT_TBS3, PDT_TBS3
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P2'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS4, PDT_TBS5, PDT_TBS3, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P3'
ORDER BY LOBS.COLUMN_ID ASC;

ALTER TABLE T1 DROP COLUMN I4;
ALTER TABLE T1 DROP COLUMN I5;
ALTER TABLE T1 DROP COLUMN I6;


ALTER TABLE T2 ADD COLUMN ( I4 BLOB, I5 INTEGER, I6 BLOB )
LOB (I4) STORE AS ( TABLESPACE PDT_TBS3 )
(
    PARTITION P1 LOB STORE AS ( TABLESPACE PDT_TBS4  ),
    PARTITION P3 LOB (I6) STORE AS ( TABLESPACE PDT_TBS5 )
);

INSERT INTO T2 VALUES ( 222, 222, 222, 'FFF', 222, 'EEE' );
INSERT INTO T2 VALUES ( 222, 222, 222, 'FFF', 222, 'EEE' );


-- Result: PDT_TBS4, PDT_TBS4
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T2' AND
      PART.PARTITION_NAME = 'P1'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS3, PDT_TBS3
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T2' AND
      PART.PARTITION_NAME = 'P2'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS3, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T2' AND
      PART.PARTITION_NAME = 'P3'
ORDER BY LOBS.COLUMN_ID ASC;

ALTER TABLE T2 DROP COLUMN I4;
ALTER TABLE T2 DROP COLUMN I5;
ALTER TABLE T2 DROP COLUMN I6;


--###############
--# LOB 컬럼 반복 지정
--###############
---------------------------------------------------
-- SYS_PART_KEY_COLUMNS_
---------------------------------------------------
-- should be 3
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLES_ TAB,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_PART_KEY_COLUMNS_ PARTKEY
WHERE TAB.TABLE_NAME='T1' AND
      TAB.TABLE_ID = PART.TABLE_ID AND
      PART.TABLE_ID = PARTKEY.PARTITION_OBJ_ID;

---------------------------------------------------
-- SYS_PART_LOBS_
---------------------------------------------------
-- should be 6
SELECT COUNT(*)
FROM SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLES_ TAB
WHERE LOBS.TABLE_ID = TAB.TABLE_ID AND
      TAB.TABLE_NAME='T1';


ALTER TABLE T1 ADD COLUMN ( I4 BLOB, I5 INTEGER, I6 BLOB )
LOB (I4) STORE AS ( TABLESPACE PDT_TBS  )
LOB (I6) STORE AS ( TABLESPACE PDT_TBS2 )
(
    PARTITION P1 LOB (I6) STORE AS ( TABLESPACE PDT_TBS3 )
                 LOB (I4) STORE AS ( TABLESPACE PDT_TBS4 ),
    PARTITION P3 LOB (I6) STORE AS ( TABLESPACE PDT_TBS5 )
);

INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF', 222, 'EEE' );
INSERT INTO T1 VALUES ( 222, 'ABC', 'DEF', 'FFF', 222, 'EEE' );

---------------------------------------------------
-- SYS_PART_KEY_COLUMNS_
---------------------------------------------------
-- should be 3
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLES_ TAB,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_PART_KEY_COLUMNS_ PARTKEY
WHERE TAB.TABLE_NAME='T1' AND
      TAB.TABLE_ID = PART.TABLE_ID AND
      PART.TABLE_ID = PARTKEY.PARTITION_OBJ_ID;

---------------------------------------------------
-- SYS_PART_LOBS_
---------------------------------------------------
-- should be 12
SELECT COUNT(*)
FROM SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLES_ TAB
WHERE LOBS.TABLE_ID = TAB.TABLE_ID AND
      TAB.TABLE_NAME='T1';


-- Result: PDT_TBS2, PDT_TBS2, PDT_TBS4, PDT_TBS3
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P1'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS3, PDT_TBS5, PDT_TBS, PDT_TBS2
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P2'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS4, PDT_TBS5, PDT_TBS, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T1' AND
      PART.PARTITION_NAME = 'P3'
ORDER BY LOBS.COLUMN_ID ASC;

ALTER TABLE T1 DROP COLUMN I4;
ALTER TABLE T1 DROP COLUMN I5;
ALTER TABLE T1 DROP COLUMN I6;

---------------------------------------------------
-- SYS_PART_KEY_COLUMNS_
---------------------------------------------------
-- should be 8
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLES_ TAB,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_PART_KEY_COLUMNS_ PARTKEY
WHERE TAB.TABLE_NAME='T2' AND
      TAB.TABLE_ID = PART.TABLE_ID AND
      PART.TABLE_ID = PARTKEY.PARTITION_OBJ_ID;

---------------------------------------------------
-- SYS_PART_LOBS_
---------------------------------------------------
-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLES_ TAB
WHERE LOBS.TABLE_ID = TAB.TABLE_ID AND
      TAB.TABLE_NAME='T2';


ALTER TABLE T2 ADD COLUMN ( I4 BLOB, I5 INTEGER, I6 BLOB )
LOB (I4) STORE AS ( TABLESPACE PDT_TBS  )
LOB (I6) STORE AS ( TABLESPACE PDT_TBS2 )
(
    PARTITION P1 LOB (I6) STORE AS ( TABLESPACE PDT_TBS3 )
                 LOB (I4) STORE AS ( TABLESPACE PDT_TBS4 ),
    PARTITION P3 LOB (I6) STORE AS ( TABLESPACE PDT_TBS5 )
);

INSERT INTO T2 VALUES ( 222, 222, 222, 'FFF', 222, 'EEE' );
INSERT INTO T2 VALUES ( 222, 222, 222, 'FFF', 222, 'EEE' );

---------------------------------------------------
-- SYS_PART_KEY_COLUMNS_
---------------------------------------------------
-- should be 8
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLES_ TAB,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_PART_KEY_COLUMNS_ PARTKEY
WHERE TAB.TABLE_NAME='T2' AND
      TAB.TABLE_ID = PART.TABLE_ID AND
      PART.TABLE_ID = PARTKEY.PARTITION_OBJ_ID;

---------------------------------------------------
-- SYS_PART_LOBS_
---------------------------------------------------
-- should be 8
SELECT COUNT(*)
FROM SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLES_ TAB
WHERE LOBS.TABLE_ID = TAB.TABLE_ID AND
      TAB.TABLE_NAME='T2';


-- Result: PDT_TBS4, PDT_TBS3
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T2' AND
      PART.PARTITION_NAME = 'P1'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS, PDT_TBS2
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T2' AND
      PART.PARTITION_NAME = 'P2'
ORDER BY LOBS.COLUMN_ID ASC;

-- Result: PDT_TBS, PDT_TBS5
SELECT TBS.NAME
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS, SYSTEM_.SYS_TABLE_PARTITIONS_ PART, V$TABLESPACES TBS
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      PART.PARTITION_ID = LOBS.PARTITION_ID AND
      LOBS.TBS_ID = TBS.ID AND
      TAB.TABLE_NAME = 'T2' AND
      PART.PARTITION_NAME = 'P3'
ORDER BY LOBS.COLUMN_ID ASC;

ALTER TABLE T2 DROP COLUMN I4;
ALTER TABLE T2 DROP COLUMN I5;
ALTER TABLE T2 DROP COLUMN I6;



--###################################################################
--+ SECTOR; FINALIZATION
--###################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

