--+IGNORE ;
--+SYSTEM fitclean;
--+SYSTEM ses3.sh;
--+SYSTEM lib_make.sh;
--+SYSTEM server kill ;
--+SYSTEM echo y | shmutil -e;
--+SYSTEM echo y | destroydb -n mydb;
--+SYSTEM echo y |  createdb -M 10;
--+SYSTEM server start;
