--+SYSTEM clean;
--+SYSTEM server start;

CONNECT SYS/MANAGER AS SYSDBA;
ALTER SYSTEM STOP FLUSHER 0;
ALTER SYSTEM STOP FLUSHER 1;
CONNECT SYS/MANAGER;

CREATE TABLE T1 ( I1 CHAR(3000) ) TABLESPACE SYS_TBS_DISK_DATA;
CREATE INDEX T1X ON T1 ( I1 );
INSERT INTO T1 VALUES( 1 );
INSERT INTO T1 VALUES( 2 );
INSERT INTO T1 VALUES( 3 );
INSERT INTO T1 VALUES( 4 );
INSERT INTO T1 VALUES( 5 );
INSERT INTO T1 VALUES( 6 );
INSERT INTO T1 VALUES( 7 );
INSERT INTO T1 VALUES( 8 );

SELECT ROWNUM AS I1 FROM T1;

--+SYSTEM server kill;
--+SYSTEM rm -rf $ALTIBASE_HOME/dbs2
--+SYSTEM rm -rf $ALTIBASE_HOME/logs2
--+SYSTEM cp -rf $ALTIBASE_HOME/dbs $ALTIBASE_HOME/dbs2 
--+SYSTEM cp -rf $ALTIBASE_HOME/logs $ALTIBASE_HOME/logs2 
--+SYSTEM source gensh.sh

--+SYSTEM prop-add.sh _EMERGENCY_STARTUP_POLICY=1;
