--###########################################################################
--# ported from qp4/Project3/PROJ-1624-GlobalIndex/PROJ-1624-QC/PDT/Design/ALTER_TABLE/ALTER_COLUMN_LOB/basic.sql
--#
--# Body below is byte-identical to the original. The one line this port
--# adds is the premise: the original measures these statements on the
--# $GIT_ hidden-table implementation, this file measures the same
--# statements on the native global index (F07 -- see include/pinNative.sql).
--###########################################################################
--###########################################################################
--# NativeGlobalIndexPort1624 - the premise of every ported .sql case.
--#
--# A .sql case cannot CALL a DEF the way a .tc case calls PIN_DISK_NATIVE(),
--# so the same two statements are pulled in per case with ATC's own include
--# directive:
--#
--#     --+LOAD_SQL <relative path>/include/pinNative.sql;
--#
--# ATC inlines this file into the case transcript between BEGIN/END markers,
--# which is exactly what F07 asks for: the case states its own premise at the
--# head of its own transcript instead of inheriting whatever the instance
--# happens to be configured with.
--#
--#     DISK_GLOBAL_INDEX_ENABLE = 1  -> native  (this suite)
--#     DISK_GLOBAL_INDEX_ENABLE = 0  -> $GIT_   (the original suite)
--#
--# The readout below is not decoration. It is the tooth: if the property is
--# ever 0 when a case runs, this one line differs and the case is red before
--# it has measured anything, instead of quietly measuring the other
--# implementation (disk-natc.md 6 records nine assertions that drifted that
--# way).
--#
--# ASCII only, on purpose: 87 of the ported case bodies are EUC-KR and their
--# bytes must stay untouched, so nothing this port adds may introduce a
--# second encoding into a transcript.
--###########################################################################

ALTER SYSTEM SET DISK_GLOBAL_INDEX_ENABLE = 1;

SELECT CAST(VALUE1 AS VARCHAR(10)) DISK_GLOBAL_INDEX_ENABLE
FROM V$PROPERTY WHERE NAME = 'DISK_GLOBAL_INDEX_ENABLE';

--###################################################################
--# ALTER TABLE ... ALTER COLUMN LOB
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
--+SKIP END;

CREATE TABLE T1( I1 INTEGER, I2 CLOB DEFAULT 'DEFAULT', I3 BLOB )
PARTITION BY RANGE (I1)
(
    PARTITION P1 VALUES LESS THAN (2),
    PARTITION P2 VALUES LESS THAN (3),
    PARTITION P3 VALUES LESS THAN (4),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE SYS_TBS_DISK_DATA;

INSERT INTO T1 VALUES ( 1, 'CLOB1', 'FF' );
INSERT INTO T1 VALUES ( 2, 'CLOB2', 'FFFF' );
INSERT INTO T1 VALUES ( 3, 'CLOB3', 'FFFFFF' );
INSERT INTO T1 VALUES ( 4, 'CLOB4', 'FFFFFFFF' );
INSERT INTO T1 VALUES ( 5, 'CLOB5', 'FFFFFFFFFF' );

--#########################################################################
--+ SECTOR; BASIC TEST
--#########################################################################
---------------------------------------------------
-- 문법 체크
---------------------------------------------------
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING )
(
    PARTITION P1,
    PARTITION P2
);

-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING )
(
    PARTITION P1 LOB STORE AS ( TABLESPACE SYS_TBS_DISK_DATA ),
    PARTITION P2 LOB STORE AS ( LOGGING BUFFER )
);

-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING )
(
    PARTITION P1 LOB STORE AS ( BUFFER LOGGING BUFFER ),
    PARTITION P2 LOB STORE AS ( LOGGING BUFFER )
);

-- should be fail
ALTER TABLE T1 ALTER COLUMN
(
    PARTITION P1 LOB STORE AS ( BUFFER LOGGING BUFFER ),
    PARTITION P2 LOB STORE AS ( LOGGING BUFFER )
);


---------------------------------------------------
-- 파티션드 테이블인지 체크
---------------------------------------------------
--+SKIP BEGIN;
DROP TABLE TEST;
--+SKIP END;

CREATE TABLE TEST ( I1 INTEGER, I2 BLOB );

-- should be fail
ALTER TABLE TEST ALTER COLUMN LOB STORE AS ( LOGGING )
(
    PARTITION P1 LOB STORE AS ( BUFFER ),
    PARTITION P2 LOB STORE AS ( LOGGING )
);

--+SKIP BEGIN;
DROP TABLE TEST;
--+SKIP END;

---------------------------------------------------
-- 해당 파티션이 존재하는지 체크
---------------------------------------------------
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING )
(
    PARTITION P1 LOB STORE AS ( BUFFER ),
    PARTITION P5 LOB STORE AS ( LOGGING ),
    PARTITION P3 LOB STORE AS ( LOGGING )
);



--#########################################################################
--+ SECTOR; 1. OPT_LOB_ATTRIBUTE_LIST [OPT_PARTITIOIN_LOB_ATTRIBUTE_LIST]
--#########################################################################

---------------------------------------------------
-- 1.1 LOB STORE
---------------------------------------------------

SELECT RTRIM(RPAD(SUBSTR(I2, 1), 4000, ' ')), LENGTHB(I3) FROM T1;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( NOLOGGING );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( BUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( NOBUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( NOLOGGING NOBUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( TABLESPACE SYS_TBS_MEM_DATA );
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( TABLESPACE SYS_TBS_DISK_DATA );
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( );

---------------------------------------------------
-- 1.2 LOB( clob_column ) STORE
---------------------------------------------------

SELECT RTRIM(RPAD(SUBSTR(I2, 1), 4000, ' ')), LENGTHB(I3) FROM T1;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( LOGGING );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( NOLOGGING );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( BUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( NOBUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( LOGGING BUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( NOLOGGING NOBUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( TABLESPACE SYS_TBS_MEM_DATA );
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( TABLESPACE SYS_TBS_DISK_DATA );
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( );

---------------------------------------------------
-- 1.3 LOB( blob_column ) STORE
---------------------------------------------------

SELECT RTRIM(RPAD(SUBSTR(I2, 1), 4000, ' ')), LENGTHB(I3) FROM T1;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( LOGGING );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( NOLOGGING );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( BUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( NOBUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( LOGGING BUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( NOLOGGING NOBUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( TABLESPACE SYS_TBS_MEM_DATA );
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( TABLESPACE SYS_TBS_DISK_DATA );
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( );

---------------------------------------------------
-- 1.4 LOB( * ) STORE
---------------------------------------------------

SELECT RTRIM(RPAD(SUBSTR(I2, 1), 4000, ' ')), LENGTHB(I3) FROM T1;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( LOGGING );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( NOLOGGING );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( BUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( NOBUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( LOGGING BUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( NOLOGGING NOBUFFER );
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( TABLESPACE SYS_TBS_MEM_DATA );
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( TABLESPACE SYS_TBS_DISK_DATA );
-- should be fail
ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( );


--###########################################################################
--+ SECTOR; 2. OPT_LOB_ATTRIBUTE_LIST OPT_PARTITIOIN_LOB_ATTRIBUTE_LIST
--###########################################################################

---------------------------------------------------
-- 2.1 LOB STORE
---------------------------------------------------

SELECT RTRIM(RPAD(SUBSTR(I2, 1), 4000, ' ')), LENGTHB(I3) FROM T1;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING )
( 
    PARTITION P2 LOB STORE AS ( NOLOGGING )
);
-- (P1,T,T),(P1,T,T),(P2,F,T),(P2,F,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( NOLOGGING )
( 
    PARTITION P2 LOB STORE AS ( LOGGING )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( BUFFER )
( 
    PARTITION P2 LOB STORE AS ( NOBUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,F),(P2,T,F),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( NOBUFFER )
( 
    PARTITION P2 LOB STORE AS ( BUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( LOGGING BUFFER )
( 
    PARTITION P2 LOB STORE AS ( NOLOGGING NOBUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,F,F),(P2,F,F),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB STORE AS ( NOLOGGING NOBUFFER )
( 
    PARTITION P2 LOB STORE AS ( LOGGING BUFFER )
);
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

---------------------------------------------------
-- 2.2 LOB( clob_column ) STORE
---------------------------------------------------

SELECT RTRIM(RPAD(SUBSTR(I2, 1), 4000, ' ')), LENGTHB(I3) FROM T1;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( LOGGING )
( 
    PARTITION P2 LOB(I2) STORE AS ( NOLOGGING )
);
-- (P1,T,T),(P1,T,T),(P2,F,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( NOLOGGING )
( 
    PARTITION P2 LOB(I2) STORE AS ( LOGGING )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( BUFFER )
( 
    PARTITION P2 LOB(I2) STORE AS ( NOBUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,F),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( NOBUFFER )
( 
    PARTITION P2 LOB(I2) STORE AS ( BUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( LOGGING BUFFER )
( 
    PARTITION P2 LOB(I2) STORE AS ( NOLOGGING NOBUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,F,F),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2) STORE AS ( NOLOGGING NOBUFFER )
( 
    PARTITION P2 LOB(I2) STORE AS ( LOGGING BUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

---------------------------------------------------
-- 2.3 LOB( blob_column ) STORE
---------------------------------------------------

SELECT RTRIM(RPAD(SUBSTR(I2, 1), 4000, ' ')), LENGTHB(I3) FROM T1;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( LOGGING )
( 
    PARTITION P2 LOB(I3) STORE AS ( NOLOGGING )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,F,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( NOLOGGING )
( 
    PARTITION P2 LOB(I3) STORE AS ( LOGGING )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( BUFFER )
( 
    PARTITION P2 LOB(I3) STORE AS ( NOBUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,F),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( NOBUFFER )
( 
    PARTITION P2 LOB(I3) STORE AS ( BUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( LOGGING BUFFER )
( 
    PARTITION P2 LOB(I3) STORE AS ( NOLOGGING NOBUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,F,F),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I3) STORE AS ( NOLOGGING NOBUFFER )
( 
    PARTITION P2 LOB(I3) STORE AS ( LOGGING BUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

---------------------------------------------------
-- 2.4 LOB( * ) STORE
---------------------------------------------------

SELECT RTRIM(RPAD(SUBSTR(I2, 1), 4000, ' ')), LENGTHB(I3) FROM T1;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( LOGGING )
( 
    PARTITION P2 LOB(I2, I3) STORE AS ( NOLOGGING )
);
-- (P1,T,T),(P1,T,T),(P2,F,T),(P2,F,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( NOLOGGING )
( 
    PARTITION P2 LOB(I2, I3) STORE AS ( LOGGING )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( BUFFER )
( 
    PARTITION P2 LOB(I2, I3) STORE AS ( NOBUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,F),(P2,T,F),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( NOBUFFER )
( 
    PARTITION P2 LOB(I2, I3) STORE AS ( BUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( LOGGING BUFFER )
( 
    PARTITION P2 LOB(I2, I3) STORE AS ( NOLOGGING NOBUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,F,F),(P2,F,F),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

ALTER TABLE T1 ALTER COLUMN LOB(I2, I3) STORE AS ( NOLOGGING NOBUFFER )
( 
    PARTITION P2 LOB(I2, I3) STORE AS ( LOGGING BUFFER )
);
-- (P1,T,T),(P1,T,T),(P2,T,T),(P2,T,T),(P3,T,T),(P3,T,T),(P4,T,T),(P4,T,T)
SELECT PART.PARTITION_NAME, LOBS.LOGGING, LOBS.BUFFER
FROM SYSTEM_.SYS_TABLES_ TAB, SYSTEM_.SYS_PART_LOBS_ LOBS,
     SYSTEM_.SYS_TABLE_PARTITIONS_ PART
WHERE TAB.TABLE_ID = LOBS.TABLE_ID AND
      TAB.TABLE_NAME = 'T1' AND PART.PARTITION_ID = LOBS.PARTITION_ID
ORDER BY PART.PARTITION_NAME, LOBS.COLUMN_ID;

--###################################################################
--+ SECTOR; FINALIZATION
--###################################################################

--+SKIP BEGIN;
DROP TABLE T1;
--+SKIP END;

