--###########################################################################
--# ported from qp4/Project3/PROJ-1624-GlobalIndex/PROJ-1624-QC/PDT/Design/DROP_TABLESPACE/basic.sql
--#
--# Body below is byte-identical to the original. The one line this port
--# adds is the premise: the original measures these statements on the
--# $GIT_ hidden-table implementation, this file measures the same
--# statements on the native global index (F07 -- see include/pinNative.sql).
--###########################################################################
--###########################################################################
--# NativeGlobalIndexPort1624 - the premise of every ported .sql case.
--#
--# A .sql case cannot CALL a DEF the way a .tc case calls PIN_DISK_NATIVE(),
--# so the same two statements are pulled in per case with ATC's own include
--# directive:
--#
--#     --+LOAD_SQL <relative path>/include/pinNative.sql;
--#
--# ATC inlines this file into the case transcript between BEGIN/END markers,
--# which is exactly what F07 asks for: the case states its own premise at the
--# head of its own transcript instead of inheriting whatever the instance
--# happens to be configured with.
--#
--#     DISK_GLOBAL_INDEX_ENABLE = 1  -> native  (this suite)
--#     DISK_GLOBAL_INDEX_ENABLE = 0  -> $GIT_   (the original suite)
--#
--# The readout below is not decoration. It is the tooth: if the property is
--# ever 0 when a case runs, this one line differs and the case is red before
--# it has measured anything, instead of quietly measuring the other
--# implementation (disk-natc.md 6 records nine assertions that drifted that
--# way).
--#
--# ASCII only, on purpose: 87 of the ported case bodies are EUC-KR and their
--# bytes must stay untouched, so nothing this port adds may introduce a
--# second encoding into a transcript.
--###########################################################################

ALTER SYSTEM SET DISK_GLOBAL_INDEX_ENABLE = 1;

SELECT CAST(VALUE1 AS VARCHAR(10)) DISK_GLOBAL_INDEX_ENABLE
FROM V$PROPERTY WHERE NAME = 'DISK_GLOBAL_INDEX_ENABLE';

--###################################################################
--# DROP TABLESPACE
--###################################################################

--###################################################################
--+SECTOR; PREPARATION
--###################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS5
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;
--+SKIP END;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS2
DATAFILE 'TBS2.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS3
DATAFILE 'TBS3.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS4
DATAFILE 'TBS4.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS5
DATAFILE 'TBS5.dbf'
SIZE 10M
AUTOEXTEND ON;



--###################################################################
--+ SECTOR; LOB 컬럼이 없는 경우
--###################################################################

--##############################
--+SECTOR; 인덱스 파티션 없는 경우
--##############################

--------------------------------
-- 테이블 파티션이 하나의 TBS에 다 들어가 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

--------------------------------
-- 테이블 파티션이 다른 TBS에 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS2,
    PARTITION P3 VALUES LESS THAN (300) TABLESPACE TBS3,
    PARTITION P4 VALUES DEFAULT TABLESPACE TBS4
) TABLESPACE TBS1;

-- should be fail
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;


--##############################
--+SECTOR; 인덱스 파티션이 있는 경우
--##############################

--------------------------------
-- 테이블 파티션, 인덱스 파티션이 하나의 TBS에 다 들어가 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1;

CREATE INDEX IDX1 ON T1(I1) LOCAL;
CREATE INDEX IDX2 ON T1(I2) LOCAL;
CREATE INDEX IDX3 ON T1(I1, I2) LOCAL;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

--------------------------------
-- 인덱스 파티션이 다른 TBS에 들어가 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1;

CREATE INDEX IDX1 ON T1(I1) LOCAL
(
    PARTITION P1_IDX1 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX1 ON P2 TABLESPACE TBS2,
    PARTITION P3_IDX1 ON P3 TABLESPACE TBS3,
    PARTITION P4_IDX1 ON P4 TABLESPACE TBS4
);

CREATE INDEX IDX2 ON T1(I2) LOCAL
(
    PARTITION P1_IDX2 ON P1 TABLESPACE TBS4,
    PARTITION P2_IDX2 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX2 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX2 ON P4 TABLESPACE TBS1
);

CREATE INDEX IDX3 ON T1(I1, I2) LOCAL
(
    PARTITION P1_IDX3 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX3 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX3 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX3 ON P4 TABLESPACE TBS4
);

-- should be fail
DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

--------------------------------
-- 테이블 파티션, 인덱스 파티션이 모두 다른 TBS에 있는 경우
--------------------------------
DROP TABLE T1;

CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER )
PARTITION BY RANGE(I1, I2)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS2,
    PARTITION P3 VALUES LESS THAN (300) TABLESPACE TBS3,
    PARTITION P4 VALUES DEFAULT TABLESPACE TBS4
) TABLESPACE TBS1;

CREATE INDEX IDX1 ON T1(I1) LOCAL
(
    PARTITION P1_IDX1 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX1 ON P2 TABLESPACE TBS2,
    PARTITION P3_IDX1 ON P3 TABLESPACE TBS3,
    PARTITION P4_IDX1 ON P4 TABLESPACE TBS4
);

CREATE INDEX IDX2 ON T1(I2) LOCAL
(
    PARTITION P1_IDX2 ON P1 TABLESPACE TBS4,
    PARTITION P2_IDX2 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX2 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX2 ON P4 TABLESPACE TBS1
);

CREATE INDEX IDX3 ON T1(I1, I2) LOCAL
(
    PARTITION P1_IDX3 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX3 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX3 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX3 ON P4 TABLESPACE TBS4
);

-- should be fail
DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be fail
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;


--##############################
--+SECTOR; 외래키가 있는 경우
--##############################
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

CREATE TABLE T1 ( I1 INTEGER UNIQUE, I2 INTEGER )
PARTITION BY RANGE(I1)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1;
CREATE INDEX IDX1 ON T1(I2) LOCAL;
CREATE INDEX IDX2 ON T1(I1, I2) LOCAL;

CREATE TABLE T2 ( I1 INTEGER UNIQUE, I2 INTEGER ) TABLESPACE TBS2;
CREATE INDEX IDX3 ON T2(I2);
CREATE INDEX IDX4 ON T2(I1, I2);

CREATE TABLE T3 ( I1 INTEGER UNIQUE, I2 INTEGER )
PARTITION BY RANGE(I1)
(
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (300),
    PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS3;
CREATE INDEX IDX5 ON T3(I2) LOCAL;
CREATE INDEX IDX6 ON T3(I1, I2) LOCAL;


ALTER TABLE T2 ADD CONSTRAINT T2_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T3 ADD CONSTRAINT T3_FK FOREIGN KEY(I2) REFERENCES T2(I1);


-- should be success
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS2
DATAFILE 'TBS2.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS3
DATAFILE 'TBS3.dbf'
SIZE 10M
AUTOEXTEND ON;

DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;


--###################################################################
--+ SECTOR; LOB 컬럼이 있는 경우
--###################################################################

--##############################
--+SECTOR; 인덱스 파티션 없는 경우
--##############################

--------------------------------
-- 테이블 파티션이 하나의 TBS에 다 들어가 있는 경우
--------------------------------
DROP TABLE T1;
CREATE TABLE T1 ( I1 INTEGER, I2 INTEGER, I3 BLOB, I4 CLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE TBS4
                                    LOB(I3, I4) STORE AS ( TABLESPACE TBS2 ), 
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS3,
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1 LOB(I4) STORE AS ( TABLESPACE TBS5 );

CREATE INDEX IDX1 ON T1(I1) LOCAL
(
    PARTITION P1_IDX1 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX1 ON P2 TABLESPACE TBS2,
    PARTITION P3_IDX1 ON P3 TABLESPACE TBS3,
    PARTITION P4_IDX1 ON P4 TABLESPACE TBS4
);

CREATE INDEX IDX2 ON T1(I2) LOCAL
(
    PARTITION P1_IDX2 ON P1 TABLESPACE TBS4,
    PARTITION P2_IDX2 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX2 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX2 ON P4 TABLESPACE TBS1
);

CREATE INDEX IDX3 ON T1(I1, I2) LOCAL
(
    PARTITION P1_IDX3 ON P1 TABLESPACE TBS1,
    PARTITION P2_IDX3 ON P2 TABLESPACE TBS3,
    PARTITION P3_IDX3 ON P3 TABLESPACE TBS2,
    PARTITION P4_IDX3 ON P4 TABLESPACE TBS4
);

-- should be success
DROP TABLESPACE TBS5
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

-- should be success
DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;


--##############################
--+SECTOR; 외래키가 있는 경우
--##############################
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS2
DATAFILE 'TBS2.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS3
DATAFILE 'TBS3.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS4
DATAFILE 'TBS4.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS5
DATAFILE 'TBS5.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLE T1 ( I1 INTEGER UNIQUE, I2 INTEGER, I3 BLOB, I4 CLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE TBS4
                                    LOB(I3, I4) STORE AS ( TABLESPACE TBS2 ), 
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS3,
  PARTITION P3 VALUES LESS THAN (300),
  PARTITION P4 VALUES DEFAULT
) TABLESPACE TBS1 LOB(I4) STORE AS ( TABLESPACE TBS5 );
CREATE INDEX IDX1 ON T1(I2) LOCAL;
CREATE INDEX IDX2 ON T1(I1, I2) LOCAL;

CREATE TABLE T2 ( I1 INTEGER UNIQUE, I2 INTEGER ) TABLESPACE TBS2;
CREATE INDEX IDX3 ON T2(I2);
CREATE INDEX IDX4 ON T2(I1, I2);

CREATE TABLE T3 ( I1 INTEGER UNIQUE, I2 INTEGER, I3 BLOB, I4 CLOB )
PARTITION BY RANGE (I1)
( PARTITION P1 VALUES LESS THAN (100) TABLESPACE TBS4
                                    LOB(I3, I4) STORE AS ( TABLESPACE TBS2 ), 
  PARTITION P2 VALUES LESS THAN (200) TABLESPACE TBS1,
  PARTITION P3 VALUES DEFAULT
) TABLESPACE TBS3 LOB(I4) STORE AS ( TABLESPACE TBS5 );
CREATE INDEX IDX5 ON T3(I2) LOCAL;
CREATE INDEX IDX6 ON T3(I1, I2) LOCAL;


ALTER TABLE T2 ADD CONSTRAINT T2_FK FOREIGN KEY(I2) REFERENCES T1(I1);
ALTER TABLE T3 ADD CONSTRAINT T3_FK FOREIGN KEY(I2) REFERENCES T2(I1);

-- should be success
DROP TABLESPACE TBS5
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

-- should be success
DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be success
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_TABLE_PARTITIONS_ PART,
     SYSTEM_.SYS_TABLES_ TAB
WHERE TAB.TABLE_NAME='T1' AND
      PART.TABLE_ID=TAB.TABLE_ID;

-- should be 0
SELECT COUNT(*)
FROM SYSTEM_.SYS_INDEX_PARTITIONS_ PART,
     SYSTEM_.SYS_INDICES_ IND
WHERE PART.INDEX_ID = IND.INDEX_ID;

--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;
--+SKIP END;

CREATE TABLESPACE TBS1
DATAFILE 'TBS1.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS2
DATAFILE 'TBS2.dbf'
SIZE 10M
AUTOEXTEND ON;

CREATE TABLESPACE TBS3
DATAFILE 'TBS3.dbf'
SIZE 10M
AUTOEXTEND ON;



--###################################################################
--+ SECTOR; FINALIZATION
--###################################################################
--+SKIP BEGIN;
DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS3
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS4
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE TBS5
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;
--+SKIP END;


